{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.sygnal.enabled }}
{{- $sygnalName := include "matrix-synapse.externalname" (dict "global" . "external" "sygnal") -}}
{{- $component := "matrix-sygnal" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $sygnalName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sygnal/sygnal-configuration.yaml") . | sha256sum }}
        checksum/fcmkey: {{ .Values.sygnal.fcmkey_keyvalue | toPrettyJson | sha256sum }}
        checksum/ioskey: {{ .Values.sygnal.ioskey_keyvalue | default "" | sha256sum }}
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      securityContext:
        {{- .Values.sygnal.podSecurityContext | toYaml | nindent 8 }}
      {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      containers:
        - name: matrix-sygnal
          image: "{{ printf "%s/%s:%s" .Values.sygnal.image.registry .Values.sygnal.image.repository .Values.sygnal.image.tag }}"
          imagePullPolicy: {{ .Values.sygnal.image.pullPolicy }}
          env:
            - name: SYGNAL_CONF
              value: /sygnal.yaml
          ports:
            - containerPort: 5000
              name: sygnal-port
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- .Values.sygnal.resources | toYaml | nindent 12 }}
          securityContext:
            {{- .Values.sygnal.securityContext | toYaml | nindent 12 }}
          {{- with .Values.sygnal.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.sygnal.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.sygnal.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /sygnal.yaml
              subPath: sygnal.yaml
              readOnly: true
            {{- if .Values.sygnal.fcmkey_filename }}
            - name: secrets
              mountPath: /{{ .Values.sygnal.fcmkey_filename }}
              subPath: {{ .Values.sygnal.fcmkey_filename }}
              readOnly: true
            {{- end }}
            {{- if .Values.sygnal.ioskey_filename }}
            - name: secrets
              mountPath: /{{ .Values.sygnal.ioskey_filename }}
              subPath: {{ .Values.sygnal.ioskey_filename }}
              readOnly: true
            {{- end }}
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - mountPath: /tmp
              name: sygnal-tmp
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          secret:
            secretName: matrix-sygnal
        - name: secrets
          secret:
            secretName: {{ .Values.sygnal.existingSecret }}
        - name: sygnal-tmp
          emptyDir:
            sizeLimit: 10Mi
            medium: Memory
{{ end }}
