---
apiVersion: v2
name: bundesmessenger
description: BWI Matrix BundesMessenger 
icon: https://matrix.org/images/matrix-logo.svg
appVersion: 1.58.0

type: application
version: 2.3.2
maintainers:
  - name: Christian Steinke
    email: christian.steinke@bwi.de
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ~8.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ~16.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
