---
apiVersion: v2
name: bundesmessenger
version: 1.2.3
description: BWI Matrix BundesMessenger
home: https://gitlab.opencode.de/bwi/bundesmessenger/backend/helm-chart/
icon: https://gitlab.opencode.de/bwi/bundesmessenger/backend/helm-chart/-/raw/main/docs/images/bum_core_sw.svg

type: application
appVersion: 1.78.0
maintainers:
  - name: BWI GmbH
    email: bundesmessenger@bwi.de
    url: https://messenger.bwi.de/
  - name: Christian Steinke
    email: christian.steinke@bwi.de
  - name: Dirk Klimpel
    email: dirk.klimpel@bwi.de

keywords:
  - BundesMessenger
  - Messaging
  - communications
  - collaboration

dependencies:
  - name: redis
    version: ^17.3.17
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: ^12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
