---
apiVersion: v2
name: bundesmessenger
description: BWI Matrix BundesMessenger 
icon: https://matrix.org/images/matrix-logo.svg
version: 0.9.8

type: application
appVersion: 1.64.0
maintainers:
  - name: Christian Steinke
    email: christian.steinke@bwi.de

dependencies:
  - name: redis
    version: ^16.1.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: ^10.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

