#!/usr/bin/env python3
"""
Comprehensive German to English translation script for values.yaml
"""
import re

def translate_values_yaml(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Comprehensive translation mappings (most specific first)
    translations = {
        # Complete phrases - context-specific
        "ServiceAccounts für den signingkey-Job": "ServiceAccounts for the signingkey job",
        "Name des ServiceAccounts für den signingkey-Job": "Name of the ServiceAccount for the signingkey job",
        "Null für die Verwendung eines Standardnamens für den ServiceAccount": "Null to use a default name for the ServiceAccount",
        "Mit dem Job wird zur Installation ein Signierschlüssel erzeugt": "The job creates a signing key during installation",
        "Nach der Erstellung des Keys oder bei manuallyer Einbindung eines Keys (`extraConfig.old_signing_keys`)": "After creating the key or when manually including a key (`extraConfig.old_signing_keys`)",
        "sollte der Job deaktiviert werden": "the job should be disabled",
        "Repository/Image Configuration for Synapse-signing-key-job. Es wird dringend": "Repository/Image configuration for Synapse signing-key job. It is strongly",
        "recommended, dass die gleiche Configuration wie vom Synapse bzw. den Workernodes genutzt wird": "recommended to use the same configuration as for Synapse or the worker nodes",
        "bei Nichtsetzen vom Tag, wird das Tag aus dem Chart.yaml übernommen (recommended)": "if tag is not set, the tag from Chart.yaml is used (recommended)",
        "Geben Sie ein bestehendes Signierschlüssel-Secret an, das im Voraus erstellt werden muss": "Specify an existing signing key secret that must be created in advance",
        "Configuration für die Container security policy": "Configuration for the container security policy",
        "Resources für das Image der Erzeugung vom Signierschlüssel": "Resources for the signing key generation image",
        "Wenn `true` sind alle Listener und Anbindungspunkte `0.0.0.0`,": "If `true` all listeners and binding points are `0.0.0.0`,",
        "wenn `false` sind einige Listener bzw. Anbindungspunkte `::` (IPv6)": "if `false` some listeners or binding points are `::` (IPv6)",
        "Derzeit wird nur reine IPv4 (https://github.com/element-hq/synapse/issues/13107)": "Currently only pure IPv4 (https://github.com/element-hq/synapse/issues/13107)",
        "oder Dual-Stack Umgebungen unterstützt, keine reine IPv6 Umgebung.": "or dual-stack environments are supported, no pure IPv6 environment.",
        "Jeden Wert, der nicht von diesem Block behandelt wird, sollten Sie stattdessen in": "Any value not handled by this block should instead be set in",
        "im Abschnitt `extraConfig` unten einstellen.": "the `extraConfig` section below.",
        "Die öffentlich zugängliche URL für die Synapse-Instanz.": "The publicly accessible URL for the Synapse instance.",
        "Lautet standardmäßig `https://<publicServerName>`.": "Defaults to `https://<publicServerName>`.",
        "Das Loglevel für Synapse.": "The log level for Synapse.",
        "Wenn das komplette Logging z.B. für Debugging verändert werden soll,": "If the complete logging should be changed e.g. for debugging,",
        "muss useRecommendedLogging auf false gesetzt werden.": "useRecommendedLogging must be set to false.",
        "Warning: Es wird recommended, wenn das logLevel auf DEBUG erhöht wird,": "Warning: It is recommended that if the logLevel is increased to DEBUG,",
        "das Logging für `synapse.storage.SQL` via extraLoggers zu reduzieren, da sonst": "the logging for `synapse.storage.SQL` should be reduced via extraLoggers, otherwise",
        "alle SQL-Abfragen protokolliert werden. Diese enthalten sensible Informationen wie z.B. Zugriffstoken.": "all SQL queries will be logged. These contain sensitive information such as access tokens.",
        "Aktiviert eine Standardkonfiguration für das Logging um unnötige Details nicht zu erfassen.": "Enables a default configuration for logging to avoid capturing unnecessary details.",
        "Die Deaktivierung ist nötig, wenn z.B. das logLevel für alles auf DEBUG erhöht werden soll.": "Disabling is necessary if e.g. the logLevel should be increased to DEBUG for everything.",
        "Die Settings befinden sich in der Datei /files/default_logging.yaml": "The settings are located in the file /files/default_logging.yaml",
        "Geben Sie hier zusätzliche Logger-Configurationen an.": "Specify additional logger configurations here.",
        "Diese Configuration wird mit dem useRecommendedLogging zusammengeführt, wobei": "This configuration is merged with useRecommendedLogging, where",
        "extraLoggers die höhere Priorität hat und bei Bedarf die Standardkonfiguration überschreibt.": "extraLoggers has higher priority and overwrites the default configuration if needed.",
        "Erfassung Nutzungsstatistiken (Hostname, Synapse-Version und -Uptime, total_users usw.) an die Entwickler melden": "Report usage statistics (hostname, Synapse version and uptime, total_users, etc.) to the developers",
        "Collect metrics, enabled": "Collect metrics, enabled",
        "Geheimnis zum Registrieren neuer Nutzer.": "Secret for registering new users.",
        "Dieser Wert wird standardmäßig auf eine zufällige Zeichenfolge gesetzt, wenn": "This value defaults to a random string if",
        "er nicht angegeben ist.": "not specified.",
        "Macaroon-Schlüssel für diverse Signaturen.": "Macaroon key for various signatures.",
        "Verwendet wird der Macaroon-Schlüssel zum Generieren und Überprüfen von": "The macaroon key is used to generate and verify",
        "- Access-Tokens von Gastnutzern,": "- Access tokens of guest users,",
        "- Login-Tokens während SSO-Logins und": "- Login tokens during SSO logins and",
        "- Abmeldelinks in Emails.": "- Logout links in emails.",
        "Geheimnis zum Generieren und Überprüfen von AGB-Bestätigungslinks.": "Secret for generating and verifying terms and conditions confirmation links.",
        "Existiert das Secret mit dem angegebenen Namen noch nicht, so wird es": "If the secret with the specified name does not exist yet, it will be",
        "automatisch generiert.": "automatically generated.",
        "Geheimnis zur Kommunikation zwischen Workern.": "Secret for communication between workers.",
        "Extra listener, die zum Listener des Hauptprozesses hinzugefügt werden können": "Extra listeners that can be added to the main process listener",
        "Eine Gruppe von vertrauenswürdigen Servern, die zu kontaktieren sind,": "A group of trusted servers to contact",
        "wenn ein anderer Server nicht auf eine Signierschlüssel-Anfrage antwortet.": "when another server does not respond to a signing key request.",
        "empty Array, da so nur bekannte Server direkt angefragt werden,": "empty Array, so only known servers are queried directly,",
        "oder das Event verfällt; Example:": "or the event expires; Example:",
        "Beliebige weitere Synapse-Configuration": "Any additional Synapse configuration",
        "Vorkonfiguriert nach Best Practise BWI GmbH:": "Preconfigured according to Best Practice BWI GmbH:",
        "Durch das automatische Annehmen von Einladungen wird gesteuert, ob Benutzern eine Einladungsanfrage": "Automatic invitation acceptance controls whether users are shown an invitation request",
        "angezeigt wird oder ob sie stattdessen automatisch einem Raum beitreten, wenn sie eine Einladung erhalten.": "or whether they automatically join a room when they receive an invitation.",
        "Es muss sicher gestellt werden, dass der Worker existent ist.": "It must be ensured that the worker exists.",
        "Vorherige Signing-Keys.": "Previous signing keys.",
        "Maximale Dateigröße für Uploads von Medien.": "Maximum file size for media uploads.",
        "Zu beachten ist, dass dies auch vom Reverse Proxy erlaubt werden muss, siehe:": "Note that this must also be allowed by the reverse proxy, see:",
        "Die maximale zulässige Dateigröße für ein Benutzer-Profilbild.": "The maximum allowed file size for a user profile picture.",
        "Angabe wann Medien von Repository gelöscht werden. Für die Zeitdauer gilt": "Specification of when media is deleted from repository. For the time period applies",
        "das Datum des letzten Zugriffs / Downloads.": "the date of last access / download.",
        "Zeitdauer wie lange eigene Medien vorgehalten werden.": "Time period how long own media is retained.",
        "Wenn sie gelöscht werden, sind sie für den Benutzer nicht mehr abrufbar.": "When they are deleted, they are no longer accessible to the user.",
        "Zeitdauer wie lange Medien von fremden Servern im Cache vorgehalten werden.": "Time period how long media from remote servers is kept in cache.",
        "Bei Bedarf werden diese vom remote Server erneut heruntergeladen.": "If needed, these are downloaded again from the remote server.",
        "Authentication required for user search": "Authentication required for user search",
        "Limit requests for users with shared rooms, disabled": "Limit requests for users with shared rooms, disabled",
        "Send profile data when chat is started": "Send profile data when chat is started",
        "Public rooms without login/authentication, disabled!": "Public rooms without login/authentication, disabled!",
        "Block invitations from unprivileged users, disabled": "Block invitations from unprivileged users, disabled",
        "IP whitelist for federation and push services required": "IP whitelist for federation and push services required",
        "Display presence status, disabled (Load)": "Display presence status, disabled (Load)",
        "Allow user search, enabled": "Allow user search, enabled",
        "Create user directory, enabled (prerequisite for user search)": "Create user directory, enabled (prerequisite for user search)",
        "Search all users, enabled": "Search all users, enabled",
        "Prefer local users in search results": "Prefer local users in search results",
        "Users can change display names, disabled": "Users can change display names, disabled",
        "Only room members can configure an alias for a room.": "Only room members can configure an alias for a room.",
        "Meldet und löscht alle Geräte, auf die länger als die angegebene Zeitspanne": "Reports and deletes all devices that have not been accessed for longer than",
        "nicht zugegriffen wurde.": "the specified time period.",
        "Maximum retention time for user IPs": "Maximum retention time for user IPs",
        "Benutzer vergessen Räume beim Verlassen automatisch.": "Users automatically forget rooms when leaving.",
        "Nur wenn alle Nutzer einen Raum verlassen und vergessen haben,": "Only when all users have left and forgotten a room",
        "wird er automatisch vom Server gelöscht.": "will it be automatically deleted from the server.",
        "Zeitraum nachdem lokal vergessene Räume aus der Datenbank": "Time period after which locally forgotten rooms are deleted from the database.",
        "gelöscht werden. Wenn der Wert undefiniert oder null ist, wird nichts gelöscht.": "If the value is undefined or null, nothing is deleted.",
        "Nachrichtenaufbewahrungsrichtlinien einschalten (auf Raumebene)": "Enable message retention policies (on room level)",
        "URL preview, disabled": "URL preview, disabled",
        "embedded URL display from third parties": "embedded URL display from third parties",
        "thirdParty Identifier lookup (3pid), disabled": "thirdParty Identifier lookup (3pid), disabled",
        "Guest access, disabled": "Guest access, disabled",
        "Configuration for password login": "Configuration for password login",
        "Allow password login, enabled": "Allow password login, enabled",
        "Wird automatisch ausgeschaltet, falls `mas.enabled`.": "Automatically disabled if `mas.enabled`.",
        "local user database, enabled": "local user database, enabled",
        "Wenn dies deaktiviert wird, müssen andere `password_providers` definiert werden.": "If this is disabled, other `password_providers` must be defined.",
        "Use password policy, enabled": "Use password policy, enabled",
        "Minimum password length in characters": "Minimum password length in characters",
        "Number must be used": "Number must be used",
        "Special character must be used": "Special character must be used",
        "Lowercase letter must be used": "Lowercase letter must be used",
        "Uppercase letter must be used": "Uppercase letter must be used",
        "Push module sends message content via Google/Apple push services, disabled": "Push module sends message content via Google/Apple push services, disabled",
        "Encryption for new rooms; enabled by default for all rooms": "Encryption for new rooms; enabled by default for all rooms",
        "Enable user and room statistics, enabled": "Enable user and room statistics, enabled",
        "Beachten Sie, dass das Deaktivieren dazu führen kann, dass bestimmte Funktionen": "Note that disabling may cause certain features",
        "(z. B. das Raumverzeichnis) nicht korrekt funktionieren.": "(e.g. the room directory) not to work correctly.",
        "Room search, enabled": "Room search, enabled",
        "Publication rights for the room list.": "Publication rights for the room list.",
        "OpenTracing ist ein Werkzeug, das einen Einblick": "OpenTracing is a tool that provides insight",
        "in den kausalen Zusammenhang der Arbeit in und zwischen Servern gibt.": "into the causal relationship of work within and between servers.",
        "Die einzelnen Server verfolgen Ereignisse und melden": "Individual servers track events and report",
        "sie an einen zentralen Server - im Fall von Synapse: Jaeger.": "them to a central server - in the case of Synapse: Jaeger.",
        "dynamic thumbnails, enabled": "dynamic thumbnails, enabled",
        "Experimentelle Features.": "Experimental features.",
        "öffentliche Räume über Föderation erlauben, disabled": "allow public rooms over federation, disabled",
        "Allowlist (Matrix-Server-Namen) für Föderation": "Allowlist (Matrix server names) for federation",
        "Eine Liste von Matrix-Servern, von denen die eigenen Benutzer": "A list of Matrix servers from which own users",
        "keine Medien herunterladen dürfen.": "are not allowed to download media.",
        "Liste der CA-Files im PEM-Format für die föderierten Instanzen.": "List of CA files in PEM format for federated instances.",
        "Diese müssen als Secret im Namespace des Deployments vorliegen,": "These must exist as a secret in the namespace of the deployment,",
        "da sie im Synapse-Container gemountet werden.": "as they are mounted in the Synapse container.",
        "Hinweis: Stellen Sie sicher, dass Sie eine PEM-Datei verwenden, die die": "Note: Make sure you use a PEM file that contains the",
        "vollständige Zertifikatskette einschließlich aller Zwischenzertifikate": "complete certificate chain including all intermediate certificates",
        "enthält (wenn Sie beispielsweise certbot verwenden, verwenden": "(if you use certbot for example, use",
        "fullchain.pem als Ihr Zertifikat, nicht cert.pem).": "fullchain.pem as your certificate, not cert.pem).",
        "Der Pfad wird durch Secretname und Zertifikatsname(inklusive \".pem\"-Endung)": "The path is specified by secret name and certificate name(including \".pem\" extension)",
        "angegeben": "specified",
        "Aus dem Pfad wird der Name des Secrets abgeleitet. Bei dem angegebenen Zertifikat": "The name of the secret is derived from the path. For the specified certificate",
        "\"/SECRETNAME1/myCA1.pem\" muss sich im Secret \"SECRETNAME1\" die Datei \"myCA1.pem\"": "\"/SECRETNAME1/myCA1.pem\" the file \"myCA1.pem\" must be in the secret \"SECRETNAME1\"",
        "befinden. Sie müssen das Secret manuell selbst vorab anlegen.": "You must create the secret manually in advance.",
        "Definiert einige Unteroptionen im Zusammenhang mit der Föderation": "Defines some sub-options related to federation",
        "Die folgenden Optionen beziehen sich auf die Configuration der Timeout- und": "The following options relate to the configuration of timeout and",
        "Wiederholungslogik für eine Föderations-Anfrage, unabhängig von den anderen Anfragen.": "retry logic for a federation request, independent of other requests.",
        "Der Algorithmus mit kurzer Wiederholung (short-retry) wird verwendet,": "The short-retry algorithm is used,",
        "wenn etwas oder jemand auf eine Antwort auf die Anfrage wartet,": "when something or someone is waiting for a response to the request,",
        "während der Algorithmus mit langer Wiederholung (long-retry) für Anfragen": "while the long-retry algorithm is used for requests",
        "verwendet wird, die im Hintergrund ausgeführt werden,": "that are executed in the background,",
        "wie z. B. das Senden einer Föderationstransaktion.": "such as sending a federation transaction.",
        "Timeout für die Föderation-Anfragen": "Timeout for federation requests",
        "maximale Verzögerung, die für den short-retry verwendet werden soll": "maximum delay to be used for short-retry",
        "maximale Verzögerung, die für den long-retry verwendet werden soll": "maximum delay to be used for long-retry",
        "maximale Anzahl von Wiederholungsversuchen für den short-retry": "maximum number of retry attempts for short-retry",
        "maximale Anzahl von Wiederholungsversuchen für den long-retry": "maximum number of retry attempts for long-retry",
        "Die folgenden Optionen steuern die Wiederholungslogik bei der": "The following options control the retry logic when",
        "Kommunikation mit einem bestimmten Homeserver.": "communicating with a specific homeserver.",
        "Im Gegensatz zu den vorherigen Configurationoptionen gelten diese": "Unlike the previous configuration options, these",
        "Werte für alle Anforderungen für ein bestimmtes Ziel und der Status des": "values apply to all requests for a specific destination and the status of the",
        "Backoffs wird in der Datenbank gespeichert.": "backoff is stored in the database.",
        "Der anfängliche Backoff (Interval), nach erstem Fehlschlag": "The initial backoff (interval), after first failure",
        "Multiplier für wiederholende Fehler zum anfängliche Backoff (Interval)": "Multiplier for repeated failures to the initial backoff (interval)",
        "Eine Kappungsgrenze (Limit) des Backoff (Interval)": "A cap (limit) of the backoff (interval)",
        "Geben Sie hier eine beliebige - geheime - Synapse-Configuration an;": "Specify any - secret - Synapse configuration here;",
        "Diese Werte werden in Secrets anstelle von Configmaps gespeichert": "These values are stored in secrets instead of configmaps",
        "Configuration, die auf den Haupt-Synapse-Container anzuwenden ist.": "Configuration to be applied to the main Synapse container.",
        "wird nachfolgend einzeln aufgeschlüsselt": "is detailed individually below",
        "Nur wirklich anwendbar, wenn das Deployment ein RWO PV angehängt hat (z.B. wenn Media Repository": "Only really applicable if the deployment has a RWO PV attached (e.g. if Media Repository",
        "für den Haupt-Synapse-Container activated ist)": "is enabled for the main Synapse container)",
        "Da Replikate = 1 sind, kann eine Aktualisierung \"hängen bleiben\", da der vorherige Container mit dem": "Since replicas = 1, an update can \"get stuck\" because the previous container with the",
        "PV verbunden bleibt und der \"neu-aufgebaute\" Container nie starten kann. Das Ändern der Strategie auf \"Recreate\" wird": "PV remains connected and the \"newly built\" container can never start. Changing the strategy to \"Recreate\" will",
        "den einzelnen vorherigen Container beenden, so dass der neue, ankommende Container sich mit dem PV verbinden kann": "terminate the single previous container so that the new, incoming container can connect to the PV",
        "Annotations, die auf den Haupt-Synapse-Container anzuwenden sind.": "Annotations to apply to the main Synapse container.",
        "Labels, die auf den Haupt-Synapse-Container anzuwenden sind.": "Labels to apply to the main Synapse container.",
        "Zusätzliche Umgebungsvariablen, die auf den Haupt-Synapse-pod anzuwenden sind.": "Additional environment variables to apply to the main Synapse pod.",
        "Dies ist unter anderem für die Nutzung eines ausgehenden Proxies": "This is required for using an outgoing proxy among other things",
        "(https://element-hq.github.io/synapse/latest/setup/forward_proxy.html) notwendig.": "(https://element-hq.github.io/synapse/latest/setup/forward_proxy.html).",
        "Warning: U.U. sind die gleichen Settings zusätzlich unter \"workers.default\"": "Warning: The same settings may need to be configured additionally under \"workers.default\"",
        "bzw. für den Sygnal selbst zu konfigurieren.": "or for Sygnal itself.",
        "Der Sygnal muss in der \"no_proxy\" Ausnahme enthalten sein, da Synapse": "Sygnal must be included in the \"no_proxy\" exception, as Synapse",
        "ihn sonst versucht via Proxy zu erreichen. Für die BuM Apps ist dies \"push-local\".": "would otherwise try to reach it via proxy. For BuM apps this is \"push-local\".",
        "Zusätzliche in Synapse zu mountende Datenträger (Volumes)": "Additional volumes to be mounted in Synapse",
        "Zusätzliche in Synapse zu mountende Datenträgerpfade (Volumes)": "Additional volume mounts to be mounted in Synapse",
        "Zusätzliche Befehle, die beim Starten von Synapse ausgeführt werden": "Additional commands to be executed when starting Synapse",
        "Configuration für die Pod-Security policy, Synapse wird immer als": "Configuration for pod security policy, Synapse always runs as",
        "sein eigener Benutzer ausgeführt, auch wenn dies nicht eingestellt ist.": "its own user, even if this is not configured.",
        "Beachten Sie, dass eine Änderung dieser Setting auch die Verwendung der volumePermission": "Note that changing this setting may also require using the volumePermission",
        "Hilfsprogramm verwenden müssen, abhängig von Ihrem Speicher.": "utility, depending on your storage.",
        "weitere Example:": "more examples:",
        "Configuration für die Container security policy, siehe oben": "Configuration for container security policy, see above",
        "podSecurityContext für weitere relevante Informationen.": "podSecurityContext for more relevant information.",
        "Begrenzungen und Anforderungen für CPU-Resources werden in CPU-Einheiten gemessen.": "Limits and requests for CPU resources are measured in CPU units.",
        "In Kubernetes entspricht eine CPU-Einheit einem physischen CPU-Kern oder einem virtuellen Kern,": "In Kubernetes, one CPU unit corresponds to one physical CPU core or one virtual core,",
        "je nachdem, ob es sich bei dem Knoten um einen physischen Host oder eine virtuelle Maschine handelt,": "depending on whether the node is a physical host or a virtual machine,",
        "die innerhalb einer physischen Maschine ausgeführt wird.": "running inside a physical machine.",
        "Anteilige Anforderungen sind zulässig.": "Fractional requests are allowed.",
        "Wenn Sie einen Container definieren und spec.containers[].resources.requests.cpu auf 0,5 setzen,": "If you define a container and set spec.containers[].resources.requests.cpu to 0.5,",
        "fordern Sie nur halb so viel CPU-Zeit an, als wenn Sie 1,0 CPU anfordern würden.": "you are requesting only half as much CPU time as if you requested 1.0 CPU.",
        "Für CPU-Resources entspricht der Mengenausdruck 0,1 dem Ausdruck 100m,": "For CPU resources, the quantity expression 0.1 is equivalent to the expression 100m,",
        "was als \"einhundert Millicpu\" gelesen werden kann.": "which can be read as \"one hundred millicpu\".",
        "Manche Leute sagen \"einhundert Millicores\", und das bedeutet dasselbe.": "Some people say \"one hundred millicores\", and that means the same thing.",
        "CPU resource limits to apply to the main Synapse container.": "CPU resource limits to apply to the main Synapse container.",
        "RAM resource limits to apply to the main Synapse container.": "RAM resource limits to apply to the main Synapse container.",
        "CPU resource requests to apply to the main Synapse container.": "CPU resource requests to apply to the main Synapse container.",
        "RAM resource requests to apply to the main Synapse container.": "RAM resource requests to apply to the main Synapse container.",
        "Zu verwendende Configuration für den Pfad des Healthchecks": "Configuration to use for the healthcheck path",
        "Zu verwendende Configuration für den Port des Healthchecks": "Configuration to use for the healthcheck port",
        "Configuration des Pfads vom Bereitschaftscheck": "Configuration of the readiness check path",
        "Configuration des Ports vom Bereitschaftscheck": "Configuration of the readiness check port",
        "Anzahl der Fehlversuche, damit Startzeit für Worker bei 60 Sekunden landet; Timeout default bei 10 Sekunden": "Number of failure attempts so that start time for worker lands at 60 seconds; timeout default at 10 seconds",
        "Configuration des Pfads vom Startup-Check": "Configuration of the startup check path",
        "DEFAULT gilt für alle Synapse-Worker-Container.": "DEFAULT applies to all Synapse worker containers.",
        "Configuration des Ports vom Startup-Check": "Configuration of the startup check port",
        "Node Selektoren, die für den Haupt-Synapse-Container festgelegt werden.": "Node selectors to be set for the main Synapse container.",
        "Die folgenden Taints sind eingebaut:": "The following taints are built-in:",
        "Der Knoten ist nicht bereit. Dies entspricht dem Attribut NodeCondition Ready auf \"False\" gesetzt.": "The node is not ready. This corresponds to the NodeCondition Ready attribute set to \"False\".",
        "Der Knoten ist vom Node Controller nicht erreichbar.": "The node is not reachable from the Node Controller.",
        "Dies entspricht dem Attribut NodeCondition Ready auf \"Unknown\" gesetzt.": "This corresponds to the NodeCondition Ready attribute set to \"Unknown\".",
        "Der Knoten hat Speicherbesonderheiten mit hohen Lasten auf den RAM": "The node has memory peculiarities with high loads on RAM",
        "Der Knoten hat IO-Last auf die Festplatte.": "The node has IO load on the disk.",
        "Im Falle einer hohen Festplattenauslastung auf den Knoten kann dies zu einer": "In case of high disk utilization on the node, this can lead to",
        "Verlangsamung der Anwendung führen, so dass es besser ist, die Container zu verlagern.": "slowdown of the application, so it is better to relocate the containers.",
        "Ein Knoten hat Prozess-Last(PID-Druck).": "A node has process load (PID pressure).",
        "Die Prozess-ID ist eine begrenzte Ressource und ihre Sättigung": "The process ID is a limited resource and its saturation",
        "kann zu einer Verlangsamung der Anwendungen führen, so dass es besser ist,": "can lead to slowdown of applications, so it is better to",
        "Container an einen anderen Ort zu verlagern.": "relocate containers to another location.",
        "Das Netzwerk des Knotens ist nicht verfügbar. Wie oben erklärt.": "The node's network is unavailable. As explained above.",
        "Der Knoten ist nicht planbar.": "The node is not schedulable.",
        "Jeder andere Grund, der dazu führt, dass der Knoten für das Hosting von Container ungeeignet ist,": "Any other reason that makes the node unsuitable for hosting containers,",
        "z. B. wenn der Cluster verkleinert und der Knoten entfernt wird.": "e.g. when the cluster is downsized and the node is removed.",
        "Tolerations bzw. Taints die für den Haupt-Synapse-Container genutzt werden sollen.": "Tolerations or taints to be used for the main Synapse container.",
        "Affinität zur Wahl von Nodes für die für den Haupt-Synapse-Container genutzt werden sollen.": "Affinity for selecting nodes to be used for the main Synapse container.",
        "Configuration für die Handhabung von Synapse-Workern (im Folgenden weiter Worker),": "Configuration for handling Synapse workers (hereinafter referred to as workers),",
        "die nützlich sind für die Handhabung von Hochlast-Einsätzen bzw. Hochverfügbarkeitseinsätzen.": "which are useful for handling high-load deployments or high-availability deployments.",
        "Weitere Informationen finden Sie unter": "For more information, see",
        "Standardkonfiguration für Worker.": "Default configuration for workers.",
        "Wird an alle Worker vererbt und kann für jeden Workertyp überschrieben werden.": "Is inherited by all workers and can be overridden for each worker type.",
        "DEFAULT Worker enable.": "DEFAULT Worker enable.",
        "DEFAULT Die Anzahl der Worker-Replikate.": "DEFAULT The number of worker replicas.",
        "Beachten Sie, dass einige Worker eine besondere Behandlung erfordern.": "Note that some workers require special handling.",
        "Siehe dazu die Documentation: https://element-hq.github.io/synapse/latest/workers.html": "See the documentation: https://element-hq.github.io/synapse/latest/workers.html",
        "DEFAULT gilt für alle Synapse-Worker-Container": "DEFAULT applies to all Synapse worker containers",
        "Nur wirklich anwendbar, wenn das Deployment ein RWO PV angehängt hat (z.B. Media Repository)": "Only really applicable if the deployment has a RWO PV attached (e.g. Media Repository)",
        "Zusätzliche Configuration für die Worker.": "Additional configuration for workers.",
        "DEFAULT Annotations, die auf alle Synapse-Worker-Container anzuwenden sind.": "DEFAULT Annotations to apply to all Synapse worker containers.",
        "DEFAULT Zusätzliche Umgebungsvariablen, die auf alle Synapse-Worker-Container anzuwenden sind": "DEFAULT Additional environment variables to apply to all Synapse worker containers",
        "Zusätzliche Volumes, die dem Worker hinzugefügt werden sollen.": "Additional volumes to be added to the worker.",
        "DEFAULT gilt für alle Synapse-Worker-Container. Nützlich für das": "DEFAULT applies to all Synapse worker containers. Useful for the",
        "Media-Repo oder zum Hinzufügen von Python-Modulen. Daher besser im": "Media repo or for adding Python modules. Therefore better in the",
        "entsprechenden Configurationteil der spez. Worker.": "corresponding configuration part of the specific worker.",
        "Zusätzliche zu mountende Datenträgerpfade (siehe volumes)": "Additional volume mounts to be mounted (see volumes)",
        "Informationen zum Pod-Security context, die den Worker-Pods mitgeteilt werden sollen.": "Pod security context information to be communicated to the worker pods.",
        "Configuration für die Container security policy": "Configuration for container security policy",
        "CPU resource limits to apply to all Synapse worker containers.": "CPU resource limits to apply to all Synapse worker containers.",
        "DEFAULT gilt für alle Synapse-Worker-Container.": "DEFAULT applies to all Synapse worker containers.",
        "Empfohlen gesondert zu verwalten": "Recommended to manage separately",
        "RAM resource limits to apply to all Synapse worker containers.": "RAM resource limits to apply to all Synapse worker containers.",
        "CPU resource requests to apply to all Synapse worker containers.": "CPU resource requests to apply to all Synapse worker containers.",
        "RAM resource requests to apply to all Synapse worker containers.": "RAM resource requests to apply to all Synapse worker containers.",
        "Zu verwendende Configuration für den Pfad des Healthchecks": "Configuration to use for the healthcheck path",
        "Zu verwendende Configuration für den Port des Healthchecks": "Configuration to use for the healthcheck port",
        "Node Selektor Configuration, die auf alle Synapse-Worker-Container anzuwenden sind.": "Node selector configuration to apply to all Synapse worker containers.",
        "Tolerations/Tains Configuration, die auf alle Synapse-Worker-Container anzuwenden sind.": "Tolerations/Taints configuration to apply to all Synapse worker containers.",
        "Affinitäts-Configuration, die auf alle Synapse-Worker-Container anzuwenden sind.": "Affinity configuration to apply to all Synapse worker containers.",
        "Entsprechende Endpunkte für den Worker.": "Corresponding endpoints for the worker.",
        "Pfade für die Ingress-Configuration des Workers, Client-Server-Kommunikation.": "Paths for the ingress configuration of the worker, client-server communication.",
        "Pfade für die Ingress-Configuration des Workers, Server-Server-Kommunikation.": "Paths for the ingress configuration of the worker, server-server communication.",
        "Configuration für das Auto-Scaling der Applikation.": "Configuration for auto-scaling of the application.",
        "schalte das HPA für die Container ein.": "enable HPA for the containers.",
        "Dazu muss entsprechende Configuration in die separaten Sektionen eingefügt werden.": "For this, corresponding configuration must be inserted into the separate sections.",
        "Hinweis: Kann für alle spezifischen Worker benutzt werden.": "Note: Can be used for all specific workers.",
        "Eine Ausnahme besteht für Stream Writer Worker mit \"listeners: [replication]\".": "An exception exists for Stream Writer workers with \"listeners: [replication]\".",
        "Auf Grund der Synapse und HPA Architektur ist dies nicht möglich. Wenn diese Worker genutzt werden,": "Due to the Synapse and HPA architecture, this is not possible. If these workers are used,",
        "wird empfohlen die Anzahl der worker manually via \"replicaCount\" zu konfigurieren.": "it is recommended to configure the number of workers manually via \"replicaCount\".",
        "minimale Anzahl der Worker-Container": "minimum number of worker containers",
        "maximale Anzahl der Worker-Container": "maximum number of worker containers",
        "Prozentsatz für CPU-Auslastung um Scaling zu triggern": "Percentage for CPU utilization to trigger scaling",
        "Prozentsatz für RAM-Auslastung um Scaling zu triggern": "Percentage for RAM utilization to trigger scaling",
        "Der generische Worker kann für die meisten Endpunkte verwendet werden.": "The generic worker can be used for most endpoints.",
        "Seien Sie vorsichtig, wenn Sie die Sync-Endpunkte enable, da sie große Mengen an": "Be careful when enabling the sync endpoints, as they can consume large amounts of",
        "Resources verbrauchen können. Weitere Informationen finden Sie unter der obigen Informations-URL.": "resources. For more information, see the information URL above.",
        "Ein angemessener Lastausgleich mit der K8s-Ingress-Ressource ist möglicherweise nicht möglich.": "Appropriate load balancing with the K8s ingress resource may not be possible.",
        "Enable von Workern": "Enable workers",
        "entsprechende Endpunkte für den generischen Worker": "corresponding endpoints for the generic worker",
        "Pfade für die Ingress-Configuration des Workers, mit 'publicServerName' Domain gesetzt": "Paths for the ingress configuration of the worker, with 'publicServerName' domain set",
        "werden in der values.yaml gesetzt und können dort eingesehen werden": "are set in values.yaml and can be viewed there",
        "Sync requests": "Sync requests",
        "Client API requests": "Client API requests",
        "Encryption requests": "Encryption requests",
        "Registration/login requests": "Registration/login requests",
        "Event sending requests": "Event sending requests",
        "User directory search requests": "User directory search requests",
        "Worker event streams, deaktiviert!": "Worker event streams, disabled!",
        "See https://element-hq.github.io/synapse/latest/workers.html#stream-writers": "See https://element-hq.github.io/synapse/latest/workers.html#stream-writers",
        "auskommentiert, da nicht auf generic worker sondern zum master": "commented out, because not on generic worker but to master",
        "The typing event stream": "The typing event stream",
        "The to_device event stream": "The to_device event stream",
        "The account_data event stream": "The account_data event stream",
        "The receipts event stream": "The receipts event stream",
        "The presence event stream": "The presence event stream",
        "Pfade für die Ingress-Configuration des Workers, mit 'serverName' Domain gesetzt": "Paths for the ingress configuration of the worker, with 'serverName' domain set",
        "Federation requests": "Federation requests",
        "Inbound federation transaction request": "Inbound federation transaction request",
        "Anzahl der Worker-Container": "Number of worker containers",
        "Hinweis: Wenn autoscaling.enabled=true und replicaCount geringer als autoscaling.minReplicas": "Note: If autoscaling.enabled=true and replicaCount is less than autoscaling.minReplicas",
        "oder wenn nicht gesetzt, dann wird autoscaling.minReplicas übernommen": "or if not set, then autoscaling.minReplicas is used",
        "Configuration für das auto-scaling der Applikation.": "Configuration for auto-scaling of the application.",
        "Um den allgemeinen Worker in spezifische Belange aufzuteilen - zum Example den Empfang von Föderationstransaktionen;": "To split the general worker into specific concerns - for example receiving federation transactions;",
        "Hinweis: Diese Worker sollten eingehenden Datenverkehr basierend auf der Quell-IP routen lassen, was": "Note: These workers should route incoming traffic based on source IP, which",
        "noch als TODO offen ist.": "is still open as a TODO.",
        "Aktiviere spez. Worker für Föderationsanfragen": "Enable specific worker for federation requests",
        "Wenn dieser Worker genutzt wird, können die URLs aus dem": "If this worker is used, the URLs from the",
        "generic_worker entfernt werden.": "generic_worker can be removed.",
        "Zusätzliche Listener für Föderationsworker": "Additional listeners for federation workers",
        "Server-Side Pfade für die Ingress-Configuration des Föderations-Workers": "Server-side paths for the ingress configuration of the federation worker",
        "Dieser Worker übernimmt die Übermittlung von Push-Benachrichtigungen.": "This worker handles the delivery of push notifications.",
        "(pusher-worker -> Sygnal -> Push-Provider (Apple od. Google))": "(pusher-worker -> Sygnal -> Push-Provider (Apple or Google))",
        "Ein lokaler Sygnal-Service und -Container ist Bestandteil des Helm-Charts.": "A local Sygnal service and container is part of the Helm chart.",
        "Die Pusher-Worker werden als `pusher_instances` in die Synapse-Configuration": "The pusher workers are included in the Synapse configuration as `pusher_instances`",
        "übernommen.": ".",
        "Worker für das Senden von Daten an registrierte Anwendungsdienste.": "Worker for sending data to registered application services.",
        "Hinweis: Es kann nur eine Instanz dieses Workers ausgeführt werden. Diese": "Note: Only one instance of this worker can be run. This",
        "wird als `notify_appservices_from_worker` in die Synapse-Configuration": "is included in the Synapse configuration as `notify_appservices_from_worker`",
        "Sender von Verbundverkehr (federation traffic) an andere Matrix-Server.": "Sender of federation traffic to other Matrix servers.",
        "Die Föderationssender-Worker werden als `federation_sender_instances` in die": "The federation sender workers are included in the",
        "Synapse-Configuration übernommen.": "Synapse configuration.",
        "Enable der Föderationssender-Worker.": "Enable federation sender workers.",
        "Worker zur Bereitstellung und Speicherung von Medien.": "Worker for providing and storing media.",
        "Einer der Worker wird als `media_instance_running_background_jobs` in die": "One of the workers is included in the",
        "Synapse-Configuration übernommen.": "Synapse configuration as `media_instance_running_background_jobs`.",
        "Hinweis: Die Ausführung mehrerer Instanzen führt zu Konflikten mit": "Note: Running multiple instances leads to conflicts with",
        "Hintergrundaufgaben.": "background jobs.",
        "Enable des Media-Worker": "Enable media worker",
        "Zusätzliche Listener für Media-Worker": "Additional listeners for media workers",
        "Pfade für die Ingress-Configuration des Media-Workers, mit 'publicServerName' Domain gesetzt": "Paths for the ingress configuration of the media worker, with 'publicServerName' domain set",
        "Pfade für die Ingress-Configuration des Media-Workers, mit 'serverName' Domain gesetzt": "Paths for the ingress configuration of the media worker, with 'serverName' domain set",
        "CPU resource limits to apply to the media_repository container.": "CPU resource limits to apply to the media_repository container.",
        "RAM resource limits to apply to the media_repository container.": "RAM resource limits to apply to the media_repository container.",
        "CPU resource requests to apply to the media_repository container.": "CPU resource requests to apply to the media_repository container.",
        "RAM resource requests to apply to the media_repository container.": "RAM resource requests to apply to the media_repository container.",
        "Zusätzliche Configuration für die Worker": "Additional configuration for workers",
        "Dieser Worker aktualisiert das Benutzerverzeichnis und kann darin suchen.": "This worker updates the user directory and can search in it.",
        "Jeder generic_worker kann im Benutzerverzeichnis suchen, daher ist der": "Any generic_worker can search in the user directory, therefore the",
        "Worker optional.": "worker is optional.",
        "Hinweis: Es kann nur eine Instanz dieses Workers ausgeführt werden. Diese": "Note: Only one instance of this worker can be run. This",
        "wird als `update_user_directory_from_worker` in die Synapse-Configuration": "is included in the Synapse configuration as `update_user_directory_from_worker`",
        "Enable des Nutzersuch-Workers.": "Enable user search worker.",
        "Zusätzliche Listener für NutzerSuch-Worker": "Additional listeners for user search workers",
        "Pfade für die Ingress-Configuration des Nutzersuch-Workers, mit 'publicServerName' Domain gesetzt": "Paths for the ingress configuration of the user search worker, with 'publicServerName' domain set",
        "Configuration des Background-Workers.": "Configuration of the background worker.",
        "Hinweis: Es kann nur eine Instanz dieses Workers ausgeführt werden. Diese": "Note: Only one instance of this worker can be run. This",
        "wird als `run_background_tasks_on` in die Synapse-Configuration übernommen.": "is included in the Synapse configuration as `run_background_tasks_on`.",
        "Enable des Background-Workers.": "Enable background worker.",
        "Enable der Persistenz-Configuration für die Media-Repository-Funktion.": "Enable persistence configuration for the media repository function.",
        "Diese PVC wird entweder in Synapse oder einem media_repo-Worker eingehängt.": "This PVC is mounted either in Synapse or a media_repo worker.",
        "Hinweis: Wenn Sie in der Lage sein wollen, dies zu skalieren, müssen Sie den": "Note: If you want to be able to scale this, you must set the",
        "accessMode auf RWX/ReadWriteMany setzen.": "accessMode to RWX/ReadWriteMany.",
        "Name des VolumeClaims": "Name of the volume claim",
        "leerer Wert lässt dynamisches Provisionieren zu": "empty value allows dynamic provisioning",
        "Name der entsprechenden Storage-Klasse": "Name of the corresponding storage class",
        "Zugriffsmodus": "Access mode",
        "Größe des zu nutzenden Volumes": "Size of the volume to use",
        "Enable des Init-Containers zur Rechtekorrektur,": "Enable init container for permission correction,",
        "um die Rechte auf dem Volume für Media anzupassen": "to adjust the rights on the volume for media",
        "Nutzer-ID": "User ID",
        "Gruppen-ID": "Group ID",
        "Security context for the init container": "Security context for the init container",
        "das Repository für das zu nutzende Image zur Rechtebereinigung": "the repository for the image to use for permission cleanup",
        "das Tag für das zu nutzende Image zur Rechtebereinigung": "the tag for the image to use for permission cleanup",
        "Hinweis: noch kein finaler Tag, build version 10 als Alternative zu latest": "Note: not yet a final tag, build version 10 as alternative to latest",
        "da latest-Tag, PullPolicy immer für das zu nutzende Image zur Rechtebereinigung": "since latest tag, PullPolicy always for the image to use for permission cleanup",
        "Liste von Kubernetes Pull-Secrets.": "List of Kubernetes pull secrets.",
        "Resourcengrenzen des Init-Containers zur Rechtekorrektur.": "Resource limits of the init container for permission correction.",
        "Configuration für den Hauptdienst von Synapse.": "Configuration for the main Synapse service.",
        "Um TLS in Synapse selbst zu verwenden, fügen Sie einen TLS-Listener hinzu und ändern Sie die Ports": "To use TLS in Synapse itself, add a TLS listener and change the ports",
        "die hier konfiguriert sind.": "configured here.",
        "Typ des Auszuliefernden Endpunktes für den Hauptdienst von Synapse": "Type of endpoint to be provided for the main Synapse service",
        "interner Port des Auszuliefernden Endpunktes für den Hauptdienst von Synapse": "internal port of the endpoint to be provided for the main Synapse service",
        "externer Port des Auszuliefernden Endpunktes für den Hauptdienst von Synapse": "external port of the endpoint to be provided for the main Synapse service",
}

    # Apply all translations
    for german, english in translations.items():
        content = content.replace(german, english)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Translation complete! File written to: {output_file}")

if __name__ == "__main__":
    translate_values_yaml("values.yaml", "values.yaml")
