{{/* SPDX-FileCopyrightText: 2024–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.mas.enabled }}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") -}}
{{- $component := "matrix-authentication-service" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    component: {{ $component }}
data:
  config.yaml: |
    http:
      # Public URL base used when building absolute public URLs
      public_base: "https://{{ include "matrix-synapse.masUri" . }}"

      # OIDC issuer advertised by the service. Defaults to `public_base`
      issuer: "https://{{ include "matrix-synapse.masUri" . }}"

      # Each listener can serve multiple resources, and listen on multiple TCP ports or UNIX sockets.
      listeners:
      - name: metrics
        resources:
          - name: prometheus
        binds:
          # First option: listen to the given address
        {{- if not .Values.ipv4Only }}
          - address: '[::]:9090'
        {{- else }}
          - address: '0.0.0.0:9090'
        {{- end }}
        proxy_protocol: false

      - name: health
        resources:
          - name: health
        binds:
          # First option: listen to the given address
        {{- if not .Values.ipv4Only }}
          - address: '[::]:9099'
        {{- else }}
          - address: '0.0.0.0:9099'
        {{- end }}
        proxy_protocol: false

      - name: adminapi
        resources:
          - name: adminapi
          - name: discovery
        binds:
          # First option: listen to the given address
        {{- if not .Values.ipv4Only }}
          - address: '[::]:8081'
        {{- else }}
          - address: '0.0.0.0:8081'
        {{- end }}
        proxy_protocol: false

      # The name of the listener, used in logs and metrics
      - name: web
        # List of resources to serve
        resources:
          # Serves the .well-known/openid-configuration document
          - name: discovery
          # Serves the human-facing pages, such as the login page
          - name: human
          # Serves the OAuth 2.0/OIDC endpoints
          - name: oauth
          ## Serves the Matrix C-S API compatibility endpoints
          - name: compat
          ## Serve the GraphQL API used by the frontend,
          ## and optionally the GraphQL playground
          - name: graphql
            playground: false
          ## Serve the given folder on the /assets/ path
          - name: assets
            path: /usr/local/share/mas-cli/assets

        # List of addresses and ports to listen to
        binds:
        {{- if not .Values.ipv4Only }}
          - address: '[::]:8080'
        {{- else }}
          - address: '0.0.0.0:8080'
        {{- end }}

        # Whether to enable the PROXY protocol on the listener
        proxy_protocol: false

    templates:
      # From where to load the templates
      # This is relative to the current working directory, *not* the config file
      path: /usr/local/share/mas-cli/templates
      # Path to the frontend assets manifest file
      assets_manifest: /usr/local/share/mas-cli/manifest.json

    telemetry:
      tracing:
        # The default: don't export traces
        propagators: []
        exporter: none

      metrics:
        # The default: don't export metrics
        #exporter: none

        # Export metrics to an OTLP-compatible endpoint
        #exporter: otlp
        #endpoint: https://localhost:4317

        # Export metrics by exposing a Prometheus endpoint
        # This requires mounting the `prometheus` resource to an HTTP listener
        exporter: prometheus

    secrets:
      encryption_file: /mas/secret/encryption
      # keys: are collected at startup and written to a separate config.

    # extraConfig
    {{- include "matrix-synapse.filteredMasConfig" (dict "global" . "secrets" false) | nindent 4 }}

{{- end }}
