{{/* SPDX-FileCopyrightText: 2024–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.mas.enabled ( not .Values.mas.migration.enabled ) }}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") -}}
{{- $component := "matrix-authentication-service" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
        {{- with .Values.mas.labels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/matrix-authentication-service/matrix-authentication-service-configuration.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.mas.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.mas.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      automountServiceAccountToken: false
      initContainers:
        - name: generate-dbpass
          securityContext:
            {{- toYaml .Values.mas.securityContext | nindent 12 }}
          env:
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-synapse.maspostgresql.secret-name" . }}
                  key: {{ include "matrix-synapse.maspostgresql.secret-key" . }}
          command:
            - sh
            - -c
            - |
              awk -v pass="$POSTGRES_PASS" '
                { gsub(/POSTGRES_PASS/, pass); print }
              ' /mas/config/mas-secret.yaml > /mas/dbpass/mas-secret.yaml
          image: "{{ printf "%s/%s:%s" .Values.mas.image.registry .Values.mas.image.repository .Values.mas.image.tag }}"
          resources:
            {{- toYaml .Values.mas.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /mas/config
            - name: secrets
              mountPath: /mas/secrets
            - name: dbpass
              mountPath: /mas/dbpass
      containers:
        - name: {{ $component }}
          command:
            - mas-cli
            - server
            - --config=/mas/config/config.yaml
            - --config=/mas/dbpass/mas-secret.yaml
          image: "{{ printf "%s/%s:%s" .Values.mas.image.registry .Values.mas.image.repository .Values.mas.image.tag }}"
          imagePullPolicy: {{ .Values.mas.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.mas.securityContext | nindent 12 }}
          env:
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "matrix-synapse.maspostgresql.secret-name" . }}
                  key: {{ include "matrix-synapse.maspostgresql.secret-key" . }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: health
              containerPort: 9099
              protocol: TCP
            - name: adminapi
              containerPort: 8081
              protocol: TCP
          {{- with .Values.mas.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.mas.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.mas.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /mas/config
            - name: secrets
              mountPath: /mas/secret
            - name: secret-signingkeys
              mountPath: /mas/secret/signingkey
            - name: dbpass
              mountPath: /mas/dbpass
          {{- with .Values.mas.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mas.resources | nindent 12 }}
      volumes:
        - name: dbpass
          emptyDir:
            sizeLimit: 10Mi
        - name: config
          projected:
            sources:
            - configMap:
                name: {{ $name }}
                items:
                  - key: config.yaml
                    path: config.yaml
            - secret:
                name: {{ $name }}
                items:
                  - key: mas-secret.yaml
                    path: mas-secret.yaml
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ .Values.mas.encryption.existingSecret | quote }}
                  items:
                    - key: {{ .Values.mas.encryption.existingSecretKey | quote }}
                      path: encryption
              {{- if and
                  ($secretName := include "matrix-synapse.mas.matrixSharedSecret.secretName" .)
                  ($secretKey := include "matrix-synapse.mas.matrixSharedSecret.secretKey" .)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: matrix-shared-secret
              {{- end }}
        - name: secret-signingkeys
          secret:
            secretName: {{ .Values.mas.signingkeys.existingSecret | quote }}
      {{- with .Values.mas.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
