{{/* SPDX-FileCopyrightText: 2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.adminPortal.enabled }}
{{- if and
    (eq .Values.adminPortal.auditLog.database "sqlite")
    .Values.adminPortal.auditLog.sqlite.persistence.enabled
    (not .Values.adminPortal.auditLog.sqlite.persistence.existingClaim)
-}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "adminportal") -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.adminPortal.auditLog.sqlite.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.adminPortal.auditLog.sqlite.persistence.size | quote }}
  {{- if .Values.adminPortal.auditLog.sqlite.persistence.storageClass }}
    {{- if (eq "-" .Values.adminPortal.auditLog.sqlite.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.adminPortal.auditLog.sqlite.persistence.storageClass }}"
    {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
