{{- if and .Values.ingress.enabled .Values.webclient.enabled }}
{{- $webclientUri := .Values.webclient.uri | required "webclient.uri is required." -}}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}
{{- $component := "webclient" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  {{- range .Values.ingress.tls }}
    {{- if has $webclientUri .hosts }}
  tls:
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ $webclientUri }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ $webclientName }}
                port:
                  number: 8080
            pathType: Prefix
{{- end }}
