{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}
{{- $component := "webclient" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $webclientName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/webclient/webclient-configuration.yaml") . | sha256sum }}
        checksum/config-nginx: {{ include (print $.Template.BasePath "/nginx-conf.yaml") . | sha256sum }}
      labels:
        {{- include "matrix-synapse.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.webclient.podSecurityContext | nindent 8 }}
      initContainers:
      - name: config-build
        image: "{{ printf "%s/%s:%s" .Values.webclient.image.registry .Values.webclient.image.repository .Values.webclient.image.tag }}"
        imagePullPolicy: {{ .Values.webclient.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.webclient.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.webclient.resources | nindent 10 }}
        command:
          - sh
          - -c
          - |
            jq -s '.[0] * .[1]' /app/config.sample.json /tmp/temp.json > /opt/config.json
        volumeMounts:
          - name: config
            mountPath: /opt/
          - name: temp
            mountPath: /tmp/temp.json
            subPath: temp.json
      containers:
      - name: element
          {{- with .Values.webclient.extraEnv }}
        env:
            {{- . | toYaml | nindent 10 }}
          {{- end }}
        image: "{{ printf "%s/%s:%s" .Values.webclient.image.registry .Values.webclient.image.repository .Values.webclient.image.tag }}"
        imagePullPolicy: {{ .Values.webclient.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.webclient.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.webclient.resources | nindent 10 }}
        volumeMounts:
          - name: config
            mountPath: /app/config.json
            subPath: config.json
          - name: files
            mountPath: /etc/nginx/sites-enabled/default.conf
            subPath: default.conf
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: nginx-conf-d
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: tmp
            mountPath: /tmp
          {{- with .Values.webclient.extraVolumeMounts }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
        - name: temp
          configMap:
            name: {{ $webclientName }}-tempconf
            items:
            - key: temp.json
              path: temp.json
        - name: config
          emptyDir:
            sizeLimit: 100Ki
        - name: tmp
          emptyDir:
            sizeLimit: 50M
            medium: Memory
        - name: files
          configMap:
            name: {{ $webclientName }}
        - name: nginx-conf
          configMap:
            name: nginx-conf-default
        - name: nginx-conf-d
          configMap:
            name: nginx-conf-d
        {{- with .Values.webclient.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
{{- end }}
