{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}
# The config.json file is to be put into Kubernetes as a config file in such a way that
# the element web instance can read it.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $webclientName }}-tempconf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
data:
  override_default_config.json: |
{{- $defaultConfig := dict
  "default_server_config" (dict
    "m.homeserver" (dict
      "base_url" (include "matrix-synapse.publicServerURL" .)
      "server_name" .Values.webclient.displayName
    )
  )
  "enable_presence_by_hs_url" (dict
    (include "matrix-synapse.publicServerURL" .) (.Values.extraConfig.presence.enabled | default false)
  )
  "permalink_prefix" (printf "https://%s" .Values.webclient.uri)
  "content_scanner" (dict
    "enabled" true
  )
}}

{{- if .Values.call.enabled }}
  {{- $defaultConfig = merge $defaultConfig (dict
    "element_call" (dict
      "url" (printf "https://%s" .Values.call.uri)
      "use_exclusively" true
      "participant_limit" 5
      "brand" "BundesMessenger Call"
    )
    "features" (dict
      "feature_group_calls" true
    )
  )}}
{{- end -}}

{{- if .Values.additionalConfig.locationSharing.enabled }}
  {{- $defaultConfig = merge $defaultConfig (dict
    "bwi_setting_defaults" (dict
      "BwiFeature.locationShareTypesEnabled" (list "Pin")
      "BwiFeature.disableGeolocation" false
      "BwiFeature.hideOSMLink" true
    )
  )}}
{{- end }}

{{- $customConfig := .Values.webclient.extraConfig | default dict }}
{{- $mergedConfig := mergeOverwrite $defaultConfig $customConfig }}
{{- $mergedConfig | toPrettyJson | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $webclientName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
data:
  default.conf: |
    # Default server configuration
    #
    server {
      listen 8080 default_server;
      {{- if not .Values.ipv4Only }}
      listen [::]:8080 default_server;
      {{- end }}
      # SSL configuration
      #
      # listen 443 ssl default_server;
      # listen [::]:443 ssl default_server;
      #
      # Note: You should disable gzip for SSL traffic.
      # See: https://bugs.debian.org/773332
      #
      # Read up on ssl_ciphers to ensure a secure configuration.
      # See: https://bugs.debian.org/765782
      #
      # Self signed certs generated by the ssl-cert package
      # Don't use them in a production server!
      #
      # include snippets/snakeoil.conf;

      root /app/;

      # Add index.php to the list if you are using PHP
      index index.html index.htm index.nginx-debian.html;

      # X-Header for CORS-Policy
      include /etc/nginx/conf.d/cors_headers.conf;

      server_name _;
      # livenessProbe auf /status, logging deaktiviert
      location /status {
        return 200;
        access_log off;
      }
      location ~ /config.{{ .Values.webclient.uri }}.json {
        rewrite /config.{{ .Values.webclient.uri }}.json /config.json break;
      }
      location = /favicon.ico {
        alias /app/bwi/img/favicon.ico;
      }
      location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
      }

      # pass PHP scripts to FastCGI server
      #
      #location ~ \.php$ {
      #       include snippets/fastcgi-php.conf;
      #
      #       # With php-fpm (or other unix sockets):
      #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
      #       # With php-cgi (or other tcp sockets):
      #       fastcgi_pass 127.0.0.1:9000;
      #}

      # deny access to .htaccess files, if Apache's document root
      # concurs with nginx's one
      #
      #location ~ /\.ht {
      #       deny all;
      #}
    }
{{- end }}
