{{- if .Values.mas.enabled }}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") -}}
{{- $component := "matrix-authentication-service" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        {{- include "matrix-synapse.monitoringLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/matrix-authentications-service/matrix-authentication-service-configuration.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.mas.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      initContainers:
        - name: initconfig
          command:
            - sh
            - -c
            - |
                mas-cli config generate -o /tmp/tmpconf.yaml && sed -i '1,/transport/d;/passwords/,$d' /tmp/tmpconf.yaml
                mas-cli config dump --config=/tmp/tmpconf.yaml --config=/mas/config/conf.d/config.yaml --config=/mas/config/conf.d/mas-secret.yaml > /mas/config/config.yaml
                mas-cli config check --config=/mas/config/config.yaml
                mas-cli database migrate --config=/mas/config/config.yaml
                mas-cli config sync --prune --config=/mas/config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /mas/config/conf.d/config.yaml
              subPath: config.yaml
            - name: secrets
              mountPath: /mas/config/conf.d/mas-secret.yaml
              subPath: mas-secret.yaml
            - name: tmpconf
              mountPath: /mas/config
            - name: tmpdir
              mountPath: /tmp
          image: "{{ .Values.mas.image.repository }}:{{ .Values.mas.image.tag }}"
          imagePullPolicy: {{ .Values.mas.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.mas.securityContext | nindent 12 }}
      containers:
        - name: {{ $component }}
          ## command: [ "mas-cli", "server", "--config=/mas/config/config.yaml" ]
          command:
            - sh
            - -c
            - |
                mas-cli server --config=/mas/config/config.yaml
          image: "{{ .Values.mas.image.repository }}:{{ .Values.mas.image.tag }}"
          imagePullPolicy: {{ .Values.mas.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.mas.securityContext | nindent 12 }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- with .Values.mas.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.mas.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.mas.startupProbe }}
          startupProbe:
              {{- .Values.mas.startupProbe | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmpconf
              mountPath: /mas/config
            - name: tmpdir
              mountPath: /tmp
          {{- if .Values.demomode.enabled }}
            - name: demoscript
              mountPath: /script
          {{- end }}
          {{- with .Values.mas.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mas.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ $name }}
        - name: secrets
          secret:
            secretName: {{ $name }}
            items:
              - key: mas-secret.yaml
                path: mas-secret.yaml
        - name: tmpconf
          emptyDir:
            sizeLimit: 10Mi
            medium: Memory
        - name: tmpdir
          emptyDir:
            sizeLimit: 10Mi
            medium: Memory

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  ports:
    - name: "web"
      port: 8080
      targetPort: 8080
{{- end }}