{{- if and .Values.monitoring.enabled .Values.mas.enabled }}
{{- $monitoringService := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service-metrics") -}}
{{- $component := "matrix-authentication-service" -}}

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ $monitoringService }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ $component }}
spec:
  jobLabel: app.kubernetes.io/component
  selector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - {{ $component }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    relabelings:
    # set "instance"
    - action: replace
      replacement: {{ .Release.Namespace }}
      targetLabel: instance
    # keep only needed labels ("^__.*__$" is needed by prometheus operator)
    - action: labelkeep
      regex: instance|job|^__.*__$
{{- end }}