{{/* SPDX-FileCopyrightText: 2023–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkpolicies.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-to-dns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.networkpolicies.egressIpBlock }}
    {{- $groups := dict -}}
    {{- range $i, $entry := .Values.networkpolicies.egressIpBlock }}
      {{- $parts := splitList ":" $entry -}}
      {{- if eq (len $parts) 1 }}
        {{- $cidr := index $parts 0 -}}
        {{- if not (hasKey $groups "none") }}
          {{- $_ := set $groups "none" (list) }}
        {{- end }}
        {{- $_ := set $groups "none" (append (get $groups "none") $cidr) }}
      {{- else }}
        {{- $cidr := index $parts 0 -}}
        {{- $port := index $parts 1 -}}
        {{- if not (hasKey $groups $port) }}
          {{- $_ := set $groups $port (list) }}
        {{- end }}
        {{- $_ := set $groups $port (append (get $groups $port) $cidr) }}
      {{- end }}
    {{- end }}
    {{- range $port, $cidrs := $groups }}
    - to:
      {{- range $cidrs }}
      - ipBlock:
          cidr: {{ . | quote }}
      {{- end }}
      {{- if ne $port "none" }}
      ports:
        - protocol: TCP
          port: {{ $port }}
      {{- end }}
    {{- end }}
    {{- else }}
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchExpressions:
            - key: k8s-app
              operator: In
              values:
                - {{ .Values.networkpolicies.dnsLabel }}
      {{- end }}
{{- end }}
