{{/* SPDX-FileCopyrightText: 2023–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkpolicies.enabled }}
{{- if .Values.mas.enabled }}
{{- $component := "matrix-authentication-service" -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ $component }}-allow-egress-postgres
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.workers.generic_worker.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: generic-worker
      ports:
      - protocol: TCP
        port: 8083
    {{- else }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: synapse
      ports:
      - protocol: TCP
        port: 8008
    {{- end }}
    {{- if .Values.maspostgresql.enabled }}
    {{- /* internal maspostgresql from this chart */}}
    - to:
      - podSelector:
          matchExpressions:
            {{- toYaml .Values.networkpolicies.maspostgresql.labelSelector | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ .Values.maspostgresql.service.targetPort }}
    {{- else if .Values.networkpolicies.maspostgresql.externalPostgresIP }}
    {{- /* external postgresql outside cluster selected by IP
          set an IP has higher priority than a label */}}
    - to:
      - ipBlock:
          cidr: "{{ .Values.networkpolicies.maspostgresql.externalPostgresIP }}/32"
      ports:
      - protocol: TCP
        port: {{ .Values.externalmasPostgresql.port }}
    {{- else }}
    {{- /* external postgresql inside cluster selected by label */}}
    - to:
      - podSelector:
          matchExpressions:
            {{- toYaml .Values.networkpolicies.maspostgresql.labelSelector | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ .Values.externalmasPostgresql.port }}
    {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ $component }}-allow-ingress-and-metrics
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Values.networkpolicies.ingressNamespace }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
      - protocol: TCP
        port: 8080
    - ports:
      - protocol: TCP
        port: 9090
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: synapse
      ports:
      - protocol: TCP
        port: 8080
    - from:
    {{- range $worker, $config := .Values.workers }}
      {{- if $config.enabled }}
      {{- $name := $worker | replace "_" "-" }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $name }}
      {{- end }}
    {{- end }}
      ports:
      - protocol: TCP
        port: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ $component }}-adminapi-allow-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Values.networkpolicies.ingressNamespace }}
      ports:
      - protocol: TCP
        port: 8081
{{- end }}
{{- end }}
