{{/* SPDX-FileCopyrightText: 2023–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkpolicies.enabled }}
{{- $component := "synapse" -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ $component }}-allow-egress-sygnal-postgres-redis
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  policyTypes:
    - Egress
  egress:
    {{- if .Values.postgresql.enabled }}
    {{- /* internal postgresql from this chart */}}
    - to:
      - podSelector:
          matchExpressions:
            {{- toYaml .Values.networkpolicies.postgresql.labelSelector | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ .Values.postgresql.service.targetPort }}
    {{- else if .Values.networkpolicies.postgresql.externalPostgresIP }}
    {{- /* external postgresql outside cluster selected by IP
          set an IP has higher priority than a label */}}
    - to:
      - ipBlock:
          cidr: "{{ .Values.networkpolicies.postgresql.externalPostgresIP }}/32"
      ports:
      - protocol: TCP
        port: {{ .Values.externalPostgresql.port }}
    {{- else }}
    {{- /* external postgresql inside cluster selected by label */}}
    - to:
      - podSelector:
          matchExpressions:
            {{- toYaml .Values.networkpolicies.postgresql.labelSelector | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ .Values.externalPostgresql.port }}
    {{- end }}
    {{- if .Values.redis.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: redis
      ports:
      - protocol: TCP
        port: 6379
    {{ else }}
    - to:
      - ipBlock:
          cidr: "{{ .Values.externalRedis.host }}/32"
      ports:
      - protocol: TCP
        port: 6379
    {{- end }}
    {{- if .Values.sygnal.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-sygnal
      ports:
      - protocol: TCP
        port: 5000
    {{- end }}
    {{- if .Values.mas.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-authentication-service
      ports:
      - protocol: TCP
        port: 8080
    {{- end }}
    {{- range $worker, $config := .Values.workers }}
      {{- if and $config.enabled (has "replication" $config.listeners) }}
        {{- $name := $worker | replace "_" "-" }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $name }}
      ports:
      - protocol: TCP
        port: 9093
      {{- end }}
    {{- end }}
    {{- if .Values.networkpolicies.fwProxyList }}
      {{- range .Values.networkpolicies.fwProxyList }}
    - to:
      - ipBlock:
          cidr: {{ (split ":" . )._0 | quote }}
        ports:
        - protcoll: TCP
          port: {{ (split ":" . )._1 | quote }}
      {{- end }}
    {{- else }}
    {{- /* Federation traffic to internet if no proxy is given */}}
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ $component }}-allow-from-ingress-genericworker-metrics
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Values.networkpolicies.ingressNamespace }}
      ports:
      - protocol: TCP
        port: 8008
    - from:
    {{- range $worker, $config := .Values.workers }}
      {{- if $config.enabled }}
      {{- $name := $worker | replace "_" "-" }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $name }}
      {{- end }}
    {{- end }}
      ports:
      - protocol: TCP
        port: 9093
    - ports:
      - protocol: TCP
        port: 9090
    {{- if not .Values.workers.media_repository.enabled }}
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-content-scanner
      ports:
      - protocol: TCP
        port: 8008
    {{- end }}
    {{- if .Values.mas.enabled }}
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-authentication-service
      ports:
      - protocol: TCP
        port: 8008
    {{- end }}
{{- end }}
