{{/* SPDX-FileCopyrightText: 2023–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.networkpolicies.enabled }}
  {{- range $worker, $config := .Values.workers }}
    {{- if $config.enabled }}
{{- $name := $worker | replace "_" "-" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-allow-egress-synapse-sygnal-postgres-redis
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $name }}
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: synapse
    {{- range $worker_egress, $config_egress := $.Values.workers }}
      {{- if and $config_egress.enabled (has "replication" $config_egress.listeners) }}
        {{- $name_egress := $worker_egress | replace "_" "-" }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $name_egress }}
      {{- end }}
    {{- end }}
      ports:
      - protocol: TCP
        port: 9093
    {{- if $.Values.postgresql.enabled }}
    {{- /* internal postgresql from this chart */}}
    - to:
      - podSelector:
          matchLabels:
            {{- $.Values.networkpolicies.postgres.selectorLabels | default (dict "app.kubernetes.io/name" "postgresql") | toYaml | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ $.Values.postgresql.containerPorts.postgresql | default 5432 }}
    {{- else if $.Values.networkpolicies.postgres.externalPostgresIP }}
    {{- /* external postgresql outside cluster selected by IP
          set an IP has higher priority than a label */}}
    - to:
      - ipBlock:
          cidr: "{{ $.Values.networkpolicies.postgres.externalPostgresIP }}/32"
      ports:
      - protocol: TCP
        port: {{ $.Values.externalPostgresql.port | default 5432 }}
    {{- else }}
    {{- /* external postgresql inside cluster selected by label */}}
    - to:
      - podSelector:
          matchLabels:
           {{- $.Values.networkpolicies.postgres.selectorLabels | toYaml | nindent 12 }}
      ports:
      - protocol: TCP
        port: {{ $.Values.externalPostgresql.port | default 5432 }}
    {{- end }}
    {{- if $.Values.redis.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: redis
      ports:
      - protocol: TCP
        port: 6379
    {{ else }}
    - to:
      - ipBlock:
          cidr: "{{ $.Values.externalRedis.host }}/32"
      ports:
      - protocol: TCP
        port: 6379
    {{- end }}
    {{- if and $.Values.sygnal.enabled (eq $worker "pusher") }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-sygnal
      ports:
      - protocol: TCP
        port: 5000
    {{- end }}
    {{- if $.Values.mas.enabled }}
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: matrix-authentication-service
      ports:
      - protocol: TCP
        port: 8080
    {{- end }}
    {{- if $.Values.networkpolicies.fwProxyList }}
      {{- range $.Values.networkpolicies.fwProxyList }}
    - to:
      - ipBlock:
          cidr: {{ (split ":" . )._0 | quote }}
        ports:
        - protcoll: TCP
          port: {{ (split ":" . )._1 | quote }}
      {{- end }}
    {{- else }}
    {{- /* Federation traffic to internet if no proxy is given */}}
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-allow-ingress-and-metrics
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ $name }}
  policyTypes:
    - Ingress
  ingress:
    {{- if has "replication" $config.listeners }}
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: synapse
    {{- range $worker_ingress, $config_ingress := $.Values.workers }}
      {{- if $config_ingress.enabled }}
      {{- $name_ingress := $worker_ingress | replace "_" "-" }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $name_ingress }}
      {{- end }}
    {{- end }}
      ports:
      - protocol: TCP
        port: 9093
    {{- end }}
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ $.Values.networkpolicies.ingressNamespace }}
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ $.Release.Namespace }}
      ports:
      - protocol: TCP
        port: 8083
    - ports:
      - protocol: TCP
        port: 9090
    {{- end }}
  {{- end }}
{{- end }}
