{{/* SPDX-FileCopyrightText: 2022–2024 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.schadcodescanner.enabled }}
{{- if and .Values.schadcodescanner.persistence.enabled (not .Values.schadcodescanner.persistence.existingClaim) -}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "schadcodescanner") -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
  {{- if .Values.schadcodescanner.persistence.enabled }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.schadcodescanner.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.schadcodescanner.persistence.size | quote }}
        {{- if .Values.schadcodescanner.persistence.storageClass }}
          {{- if (eq "-" .Values.schadcodescanner.persistence.storageClass) }}
  storageClassName: ""
          {{- else }}
  storageClassName: "{{ .Values.schadcodescanner.persistence.storageClass }}"
          {{- end }}
        {{- end }}
{{- end -}}
{{- end -}}
