---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
  log.yaml: |
    version: 1
    formatters:
      precise:
       format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
        synapse:
            level: {{ .Values.config.logLevel | default "INFO" }}
        synapse.storage.SQL:
            # beware: increasing this to DEBUG will make synapse log sensitive
            # information such as access tokens.
            level: {{ .Values.config.logLevelSQL | default "INFO" }}
    root:
        level: {{ .Values.config.logLevel | default "INFO" }}
        handlers: [console]
  homeserver.yaml: |
    # NOTE:
    # Secrets are stored in separate configs to better fit K8s concepts

    ## Server ##

    server_name: {{ required "You need to specify a serverName" .Values.serverName | quote }}
    public_baseurl: {{ .Values.config.publicBaseurl | default (printf "https://%s" (.Values.publicServerName | default .Values.serverName)) | quote }}
    pid_file: /homeserver.pid
    web_client: False
    soft_file_limit: 0
    log_config: "/synapse/config/log.yaml"
    report_stats: {{ required "You need to specify config.reportStats" .Values.config.reportStats }}

    ## Ports ##

    listeners:
      - port: 8008
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http
        x_forwarded: true

        resources:
          - names: [client, federation]
            compress: false

      - port: 9090
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [metrics]
            compress: false

      - port: 9093
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [replication]
            compress: false
    {{- if .Values.config.extraListeners }}
      {{ .Values.config.extraListeners | toYaml | nindent 6 }}
    {{- end }}

    ## Files ##

    media_store_path: "/synapse/data/media"
    uploads_path: "/synapse/data/uploads"
    {{- if .Values.config.recaptcha }}

    ## Captcha ##

    recaptcha_public_key: {{ .Values.config.recaptcha.publicKey | quote }}
    enable_registration_captcha: true
    {{- end }}

    ## Turn ##
    # The public URIs of the TURN server to give to clients
    #
    #turn_uris: []
    {{- if .Values.config.turnUris }}
    turn_uris:
       {{ toYaml .Values.config.turnUris | nindent 6 }}
    {{- else if .Values.coturn.turnUris }}
    turn_uris:
      {{- range $k, $v := .Values.coturn.turnUris }}
      - turn:{{ $.Values.config.publicBaseurl | default (printf "%s" ( $.Values.publicServerName | default $.Values.serverName)) }}:{{$v}}?transport={{$k}}
      {{end}}
    {{end}}
    ## Registration ##

    enable_registration: {{ .Values.config.enableRegistration | default false }}

    ## Metrics ###

    enable_metrics: {{ .Values.config.enable_metrics | default true }}

    ## Signing Keys ##

    signing_key_path: "/synapse/keys/signing.key"

    # The trusted servers to download signing keys from.
    trusted_key_servers: {{- .Values.config.trustedKeyServers | toYaml | nindent 6 }}

    ## Workers ##
    # Add a random shared secret to authenticate traffic.
    worker_replication_secret: {{ randAlphaNum 24 | quote }}

    {{- $default := .Values.workers.default }}
    {{- range $worker, $config := .Values.workers }}
      {{- if $config.enabled }}
        {{- $name := $worker | replace "_" "-" }}

        {{- if or (eq $worker "pusher") (eq ($config.app | default "") "pusher") }}
    # For pusher worker
    pusher_instances:
      {{- range $i, $e := until ($config.replicaCount | default $default.replicaCount | int) }}
      - {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-{{ $i }}
      {{- end }}

        {{- else if or (eq $worker "appservice") (eq ($config.app | default "") "appservice") }}
    # For appservice worker
    notify_appservices_from_worker: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "federation_sender") (eq ($config.app | default "") "federation_sender") }}
    # For federation_sender worker
    federation_sender_instances:
      {{- range $i, $e := until ($config.replicaCount | default $default.replicaCount | int) }}
      - {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-{{ $i }}
      {{- end }}

        {{- else if or (eq $worker "media_repository") (eq ($config.app | default "") "media_repository") }}
    # For media_repository worker
    enable_media_repo: false
    media_instance_running_background_jobs: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "user_dir") (eq ($config.app | default "") "user_dir") }}
    # For user_dir worker
    update_user_directory_from_worker: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "background_worker") (eq ($config.app | default "") "background_worker") }}
    # For background worker
    run_background_tasks_on: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.extraConfig }}

    ## Extra config ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}
    {{- if .Values.coturn.enabled }}
    ## TURN ##

    # The shared secret used to compute passwords for the TURN server
    #
    #turn_shared_secret: "YOUR_SHARED_SECRET"
    turn_shared_secret: "j8dOQy5TgYv0x7r9LL3so08jZReoZ9JgbpjdFO73toyqloQuCZywGihhbqYU7jZL"

    # The Username and password if the TURN server needs them and
    # does not use a token
    #
    #turn_username: "TURNSERVER_USERNAME"
    #turn_password: "TURNSERVER_PASSWORD"

    # How long generated TURN credentials last
    #
    turn_user_lifetime: 1h

    # Whether guests should be allowed to use the TURN server.
    # This defaults to True, otherwise VoIP will be unreliable for guests.
    # However, it does introduce a slight security risk as it allows users to
    # connect to arbitrary endpoints without having first signed up for a
    # valid account (e.g. by passing a CAPTCHA).
    #
    turn_allow_guests: False

    {{- end }}
