{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{-  $recommendedLogging := (dict) -}}
{{- if .Values.config.useRecommendedLogging -}}
  {{- $recommendedLogging = .Files.Get "files/default_logging.yaml" | fromYaml -}}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
  log.yaml: |
    version: 1
    formatters:
      {{- if .Values.config.useStructuredLogging }}
      structured:
        class: synapse.logging.TerseJsonFormatter
      {{- else }}
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
      {{- end }}
    handlers:
      console:
        class: logging.StreamHandler
        formatter: {{ if .Values.config.useStructuredLogging }}structured{{ else }}precise{{ end }}
    loggers:
      synapse:
        level: {{ .Values.config.logLevel | default "INFO" }}

      {{- /* empty value creates an failing "{}" */}}
      {{- if or .Values.config.extraLoggers $recommendedLogging -}}
        {{- /* first value has higher priority in merge */}}
        {{- merge (dict) .Values.config.extraLoggers $recommendedLogging | toYaml | nindent 6 }}
      {{- end }}

    root:
        level: {{ .Values.config.logLevel | default "INFO" }}
        handlers: [console]
  homeserver.yaml: |
    # NOTE:
    # Secrets are stored in separate configs to better fit K8s concepts

    ## Server ##

    server_name: {{ required "You need to specify a serverName" .Values.serverName | quote }}
    public_baseurl: {{ include "matrix-synapse.publicBaseURL" . | quote }}
    pid_file: /homeserver.pid
    web_client: False
    soft_file_limit: 0
    log_config: "/synapse/config/log.yaml"
    report_stats: {{ required "You need to specify config.reportStats" .Values.config.reportStats }}

    instance_map:
      main:
        host: {{ include "matrix-synapse.replicationname" . | quote }}
        port: 9093
        tls: false
    {{- $default := .Values.workers.default }}
    {{- range $worker, $config := .Values.workers }}
        {{- if and $config.enabled $config.listeners (has "replication" $config.listeners) }}
        {{- $name := $worker | replace "_" "-" }}
          {{- range $i, $e := until ($config.replicaCount | default $default.replicaCount | int) }}
            {{- $worker_name := printf "%s-%d" (include "matrix-synapse.workername" (dict "global" $ "worker" $name)) $i }}
      {{ $worker_name }}:
        host: {{ $worker_name | quote }}
        port: 9093
        tls: false
          {{- end }}
      {{- end }}
    {{- end }}


    ## Ports ##

    listeners:
      - port: 8008
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http
        x_forwarded: true

        resources:
          - names: [client, federation]
            compress: false

      - port: 9090
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [metrics]
            compress: false

      - port: 9093
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [replication]
            compress: false
    {{- if .Values.config.extraListeners }}
      {{ .Values.config.extraListeners | toYaml | nindent 6 }}
    {{- end }}

    ## Files ##

    media_store_path: "/synapse/data/media"
    uploads_path: "/synapse/data/uploads"
    {{- if and .Values.config.recaptcha.privateKey .Values.config.recaptcha.publicKey }}

    ## Captcha ##

    recaptcha_public_key: {{ .Values.config.recaptcha.publicKey | quote }}
    enable_registration_captcha: true
    {{- end }}

    ## Registration ##

    {{ if .Values.mas.enabled -}}
    enable_registration: false
    {{- else -}}
    enable_registration: {{ .Values.config.enableRegistration | default false }}
    {{- end }}

    ## Metrics ###

    enable_metrics: {{ .Values.config.enable_metrics | default true }}

    ## Signing Keys ##

    signing_key_path: "/synapse/keys/signing.key"

    # The trusted servers to download signing keys from.
    trusted_key_servers: {{- .Values.config.trustedKeyServers | toYaml | nindent 6 }}

    ## Workers ##

    {{- $default := .Values.workers.default }}
    {{- range $worker, $config := .Values.workers }}
      {{- if $config.enabled }}
        {{- $name := $worker | replace "_" "-" }}

        {{- if or (eq $worker "pusher") (eq ($config.app | default "") "pusher") }}
    # For pusher worker
    pusher_instances:
      {{- range $i, $e := until ($config.replicaCount | default $default.replicaCount | int) }}
      - {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-{{ $i }}
      {{- end }}

        {{- else if or (eq $worker "appservice") (eq ($config.app | default "") "appservice") }}
    # For appservice worker
    notify_appservices_from_worker: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "federation_sender") (eq ($config.app | default "") "federation_sender") }}
    # For federation_sender worker
    federation_sender_instances:
      {{- range $i, $e := until ($config.replicaCount | default $default.replicaCount | int) }}
      - {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-{{ $i }}
      {{- end }}

        {{- else if or (eq $worker "media_repository") (eq ($config.app | default "") "media_repository") }}
    # For media_repository worker
    enable_media_repo: false
    media_instance_running_background_jobs: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "user_dir") (eq ($config.app | default "") "user_dir") }}
    # For user_dir worker
    update_user_directory_from_worker: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- else if or (eq $worker "background_worker") (eq ($config.app | default "") "background_worker") }}
    # For background worker
    run_background_tasks_on: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}-0

        {{- end }}
      {{- end }}
    {{- end }}
    {{ $extraConfig := .Values.extraConfig }}
    {{- if .Values.mas.enabled -}}
      {{ $passwordDict := dict "password_config" (dict "enabled" false) }}
      {{ $extraConfig := mergeOverwrite $extraConfig $passwordDict }}
    {{- end -}}

    {{- /* Entfernen von per default leeren Variable aus ExtraConfig Dictionary
    Synapse does not starts when federation_custom_ca_list is empty.
    https://helm.sh/docs/chart_template_guide/function_list/#unset */}}
    {{- if not .Values.extraConfig.federation_custom_ca_list }}
      {{ $_ := unset $extraConfig "federation_custom_ca_list" }}
    {{- else }}
    {{- /* Korrektur von manuellen Fehlern, falls unterschiedliche Einträge mit und ohne
    führenden "/" in federation_custom_ca_list hinterlegt wurde.
    So findet auch Synapse die korrekten Mounts. */}}
      {{- $caList := list }}
      {{- range .Values.extraConfig.federation_custom_ca_list }}
        {{- $caList = printf "/%s" ( trimPrefix "/" . ) | append $caList }}
      {{- end }}
      {{ $caDict := dict "federation_custom_ca_list" ($caList) }}
      {{ $extraConfig := mustMergeOverwrite $extraConfig $caDict }}
    {{- end }}
    
    {{/* Handled in built-in experimental_features.yaml. */}}
    {{ $extraConfig := omit $extraConfig "experimental_features" }}
    
    {{- with $extraConfig }}

    ## Extra config ##
      {{ . | toYaml | nindent 4 }}
    {{- end }}