{{- if .Values.contentscanner.enabled }}
{{- $config := .Values.contentscanner -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matrix-synapse.contentscannername" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component:  {{ include "matrix-synapse.contentscannername" . }}
spec:
  replicas: {{ .Values.contentscanner.replicaCount }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.contentscannerselectorLabels" . | nindent 6 }}
  serviceName: {{ include "matrix-synapse.contentscannername" . }}
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.contentscannerselectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/contentscanner-configuration.yaml") . | sha256sum }}
    spec:
      {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      securityContext:
        fsGroup: 1334
      containers:
      - name: matrix-content-scanner
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: "{{ $config.image.pullPolicy }}"
        ports:
        - containerPort: 8080
          name: contentscanner
          protocol: TCP
        volumeMounts:
          - name: scannerconfig
            mountPath: /config
          - name: temp
            mountPath: /tmp            
          - name: crypto
            mountPath: /crypto
          - name: scannerscript
            mountPath: /opt
      volumes:
       - name: temp
         emptyDir: {}        
       - name: crypto
         emptyDir: {}
       - name: scannerscript
         configMap:
           name: scanner
           defaultMode: 0755
       - name: scannerconfig
         configMap:
           name: contentscannerconfig
{{- end }}
