{{/* SPDX-FileCopyrightText: 2022–2024 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $needsVolumePermissions := and .Values.volumePermissions.enabled (or .Values.persistence.enabled .Values.persistence.existingClaim) (not .Values.workers.media_repository.enabled ) }}
{{- if (and .Values.postgresql.enabled (and (not .Values.postgresql.auth.password) (not .Values.postgresql.auth.existingSecret))) -}}
  {{- fail "You must specify a static postgres password or existing secret if using the included postgres chart" -}}
{{- end -}}
{{- if not .Values.redis.auth.enabled -}}
  {{- fail "Redis without authentication is not supported by this chart" -}}
{{- end -}}
{{- $redisSecretName := include "matrix-synapse.redis.secret-name" . -}}
{{- $redisPassword := include "matrix-synapse.redis.password" . -}}
{{- if eq (empty $redisSecretName) (empty $redisPassword) -}}
  {{- fail (print
    "INVARIANT VIOLATION! Of Redis secret-name and Redis password there must "
    "be exactly one. ($redisSecretName: " $redisSecretName ", $redisPassword: "
    $redisPassword ")"
  )}}
{{- end -}}
{{- if not .Values.redis.auth.enabled -}}
  {{- fail "Redis without authentication is not supported by this chart" -}}
{{- end -}}
{{- $userconfigname :=  printf "%s-%s" (include "matrix-synapse.fullname" .) "users" }}
{{- $adminconfigname := printf "%s-%s" (include "matrix-synapse.fullname" .) "admins" }}
{{- $uniqCaSecrets := list }}
{{- range .Values.extraConfig.federation_custom_ca_list }}
  {{- /* extract secret name from cert path - between first both slashes, put them in a list and make it unique */}}
  {{- $uniqCaSecrets = uniq (append $uniqCaSecrets (split "/" ( trimPrefix "/" . ))._0) }}
{{- end }}
---
# Server: {{ required "A valid serverName is required" .Values.serverName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
spec:
  replicas: 1
  strategy:
    {{- toYaml .Values.synapse.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: synapse
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        checksum/demomode: {{ include (print $.Template.BasePath "/demomode/demomode.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/signing-key-job: {{ include (print $.Template.BasePath "/signing-key-job.yaml") . | sha256sum }}
        checksum/ca-secrets: {{ print $uniqCaSecrets | sha256sum }}
        {{- with .Values.synapse.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        {{- include "matrix-synapse.monitoringLabels" . | nindent 8 }}
        app.kubernetes.io/component: synapse
        {{- with .Values.synapse.labels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.synapse.podSecurityContext | nindent 8 }}
    {{- if and $needsVolumePermissions (not (hasKey .Values.synapse.podSecurityContext "fsGroup" )) }}
      initContainers:
        - name: volume-permissions
          command:
            - sh
            - -c
            - |
              chown {{ .Values.volumePermissions.uid }}:{{ .Values.volumePermissions.gid }} -R /synapse/data
          image: "{{ printf "%s/%s:%s" .Values.volumePermissions.image.registry .Values.volumePermissions.image.repository .Values.volumePermissions.image.tag }}"
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy }}
          resources:
            {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.volumePermissions.securityContext | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /synapse/data
    {{- end }}
      containers:
        - name: synapse
          command:
            - sh
            - -c
            - |
              export POSTGRES_PASSWORD=$(echo "${POSTGRES_PASSWORD:-}" | sed 's/\//\\\//g' | sed 's/\&/\\\&/g') && \
              export REDIS_PASSWORD=$(echo "${REDIS_PASSWORD:-}" | sed 's/\//\\\//g' | sed 's/\&/\\\&/g') && \
              cat /synapse/secrets/*.yaml | \
                sed -e "s/@@POSTGRES_PASSWORD@@/${POSTGRES_PASSWORD:-}/" \
                    -e "s/@@REDIS_PASSWORD@@/${REDIS_PASSWORD:-}/" \
                       > /synapse/config/conf.d/secrets.yaml

              {{- if .Values.synapse.extraCommands }}

              {{ range .Values.synapse.extraCommands }}
              {{ . }}
              {{- end }}
              {{- end }}

              exec python3 -B -m synapse.app.homeserver \
                          -c /synapse/config/homeserver.yaml \
                          -c /synapse/config/conf.d/
          env:
          {{- if or .Values.postgresql.enabled .Values.externalPostgresql.existingSecret }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.postgresql.enabled }}
                  name: {{ .Values.postgresql.auth.existingSecret | default (include "matrix-synapse.postgresql.fullname" .) }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey | default "password" }}
                  {{- else }}
                  name: {{ .Values.externalPostgresql.existingSecret }}
                  key: {{ .Values.externalPostgresql.existingSecretPasswordKey }}
                  {{- end }}
          {{- end }}
          {{- if and
              ($redisSecretName := include "matrix-synapse.redis.secret-name" .)
              ($redisSecretKey := include "matrix-synapse.redis.secret-key" .)
          }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $redisSecretName }}
                  key: {{ $redisSecretKey }}
          {{- end }}
          {{- if .Values.demomode.enabled }}
            - name: ADMINS
              valueFrom:
                configMapKeyRef:
                  name: {{ $adminconfigname }}
                  key: admins.csv
            - name: USERS
              valueFrom:
                configMapKeyRef:
                  name: {{ $userconfigname }}
                  key: users.csv
          {{- end }}
          {{- with .Values.synapse.extraEnv }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository ( include "matrix-synapse.imageTag" . )}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.synapse.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
            - name: replication
              containerPort: 9093
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- with .Values.synapse.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.synapse.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.synapse.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /synapse/config
            - name: tmpconf
              mountPath: /synapse/config/conf.d
            - name: secrets
              mountPath: /synapse/secrets
            - name: signingkey
              mountPath: /synapse/keys
            - name: media
              mountPath: /synapse/data
            - name: tmpdir
              mountPath: /tmp
          {{- range $uniqCaSecrets }}
            - name: {{ printf "fed-ca-%s" .  }}
              mountPath: /{{ . }}
          {{- end }}
          {{- if .Values.demomode.enabled }}
            - name: demoscript
              mountPath: /script
          {{- end }}
          {{- with .Values.synapse.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.synapse.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "matrix-synapse.fullname" . }}
        - name: secrets
          secret:
            secretName: {{ include "matrix-synapse.fullname" . }}
        - name: signingkey
          secret:
            secretName: {{ .Values.signingkey.existingSecret | default (include "matrix-synapse.workername" (dict "global" . "worker" "signingkey")) | quote }}
            items:
              - key: {{ .Values.signingkey.existingSecretKey | default "signing.key" | quote }}
                path: signing.key
          {{- range $uniqCaSecrets }}
        - name: {{ printf "fed-ca-%s" .  }}
          secret:
            secretName: {{ . }}
          {{- end }}
        - name: tmpconf
          emptyDir:
            sizeLimit: 10Mi
        {{- $mediaworker := false }}
        {{- range $worker, $config := .Values.workers }}
          {{- if eq $worker "media_repository" }}
            {{- $mediaworker = ($config.enabled | default false) }}
          {{- end }}
        {{- end }}
        - name: tmpdir
          emptyDir:
            {{- if not $mediaworker }}
            sizeLimit: {{ mulf ( mustRegexFind "[0-9]+" .Values.extraConfig.max_upload_size ) 5 }}{{ mustRegexFind "[A-Z]+" .Values.extraConfig.max_upload_size }}
            {{- else }}
            sizeLimit: 10Mi
            {{- end }}
            medium: Memory
        - name: media
        {{- if and .Values.persistence.enabled (not $mediaworker) }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "matrix-synapse.fullname" .) }}
        {{- else }}
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}
        {{- with .Values.synapse.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.demomode.enabled }}
        - name: demoscript
          configMap:
            name: {{ include "matrix-synapse.externalname" (dict "global" . "external" "demomode") }}-script
            defaultMode: 0755
        {{- end }}
      {{- with .Values.synapse.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.synapse.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.synapse.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
