{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $needsVolumePermissions := and .Values.volumePermissions.enabled (or .Values.persistence.enabled .Values.persistence.existingClaim) (not .Values.workers.media_repository.enabled ) }}
{{- if not .Values.redis.auth.enabled -}}
  {{- fail "Redis without authentication is not supported by this chart" -}}
{{- end -}}
{{- $uniqCaSecrets := list }}
{{- range .Values.extraConfig.federation_custom_ca_list }}
  {{- /* extract secret name from cert path - between first both slashes, put them in a list and make it unique */}}
  {{- $uniqCaSecrets = uniq (append $uniqCaSecrets (split "/" ( trimPrefix "/" . ))._0) }}
{{- end }}
---
# Server: {{ required "A valid serverName is required" .Values.serverName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: synapse
spec:
    {{- if and .Values.mas.enabled .Values.mas.migration.enabled }}
  replicas: 0
    {{- else }}
  replicas: 1
    {{- end }}
  strategy:
    {{- toYaml .Values.synapse.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: synapse
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/signing-key-job: {{ include (print $.Template.BasePath "/signing-key-job.yaml") . | sha256sum }}
        checksum/ca-secrets: {{ print $uniqCaSecrets | sha256sum }}
        {{- with .Values.synapse.annotations }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        {{- include "matrix-synapse.monitoringLabels" . | nindent 8 }}
        app.kubernetes.io/component: synapse
        {{- with .Values.synapse.labels }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.synapse.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if and
            $needsVolumePermissions
            (not (hasKey .Values.synapse.podSecurityContext "fsGroup"))
        }}
        - name: volume-permissions
          command:
            - sh
            - -c
            - |
              chown {{ .Values.volumePermissions.uid }}:{{ .Values.volumePermissions.gid }} -R /synapse/data
          image: "{{ printf "%s/%s:%s" .Values.volumePermissions.image.registry .Values.volumePermissions.image.repository .Values.volumePermissions.image.tag }}"
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy }}
          resources:
            {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.volumePermissions.securityContext | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /synapse/data
        {{- end }}
        - name: generate-pgpass
          securityContext:
            {{- toYaml .Values.synapse.securityContext | nindent 12 }}
          command:
            - sh
            - -c
            - |
              # Generate pgpass file.
              # Ref: https://www.postgresql.org/docs/current/libpq-pgpass.html
              pgpass_escape() {
                sed 's/\\/\\\\/; s/:/\\:/'
              }
              printf '\
              # hostname:port:database:username:password
              *:*:*:%s:%s
              ' \
                "$(echo "$POSTGRES_USER" | pgpass_escape)" \
                "$(pgpass_escape < /synapse/secrets/postgresql/password)" \
              > /synapse/pgpass/pgpass
              # PostgreSQL requires restrictive permissions on the passfile.
              chmod 0400 /synapse/pgpass/pgpass
          env:
            - name: POSTGRES_USER
              value: {{ include "matrix-synapse.postgresql.username" . | quote }}
          image: {{ quote (printf "%s/%s:%s"
            .Values.image.registry .Values.image.repository .Values.image.tag
          )}}
          resources:
            {{- toYaml .Values.synapse.resources | nindent 12 }}
          volumeMounts:
            - name: pgpass
              mountPath: /synapse/pgpass
            - name: secrets
              mountPath: /synapse/secrets
      containers:
        - name: synapse
          command:
            - sh
            - -c
            - |
              {{- range .Values.synapse.extraCommands }}
              {{- . | nindent 14 }}
              {{- end }}

              exec python3 -B -m synapse.app.homeserver \
                          -c /synapse/config/homeserver.yaml \
                          -c /synapse/config/experimental-features.yaml \
                          -c /synapse/config/secret-config.yaml
          {{- with .Values.synapse.extraEnv }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          image: {{ quote (printf "%s/%s:%s"
            .Values.image.registry .Values.image.repository .Values.image.tag
          )}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.synapse.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
            - name: replication
              containerPort: 9093
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: health
              containerPort: 9099
              protocol: TCP
          {{- with .Values.synapse.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.synapse.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.synapse.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /synapse/config
            - name: secrets
              mountPath: /synapse/secrets
            - name: pgpass
              mountPath: /synapse/pgpass/pgpass
              subPath: pgpass
            - name: signingkey
              mountPath: /synapse/keys
            - name: media
              mountPath: /synapse/data
            - name: tmpdir
              mountPath: /tmp
          {{- range $uniqCaSecrets }}
            - name: {{ printf "fed-ca-%s" .  }}
              mountPath: /{{ . }}
          {{- end }}
          {{- with .Values.synapse.extraVolumeMounts }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.synapse.resources | nindent 12 }}
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ include "matrix-synapse.fullname" . }}
                  items:
                    - key: log.yaml
                      path: log.yaml
                    - key: homeserver.yaml
                      path: homeserver.yaml
              - secret:
                  name: {{ include "matrix-synapse.fullname" . }}
                  items:
                    - key: config.yaml
                      path: secret-config.yaml
                    - key: experimental-features.yaml
                      path: experimental-features.yaml
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ include "matrix-synapse.postgresql.secret-name" . | quote }}
                  items:
                    - key: {{ include "matrix-synapse.postgresql.secret-key" . | quote }}
                      path: postgresql/password
              - secret:
                  name: {{ include "matrix-synapse.redis.secret-name" . | quote }}
                  items:
                    - key: {{ include "matrix-synapse.redis.secret-key" . | quote }}
                      path: redis
              {{- if and
                  ($secretName := include "matrix-synapse.registrationSharedSecret.secretName" .)
                  ($secretKey := include "matrix-synapse.registrationSharedSecret.secretKey" .)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: registration
              {{- end }}
              {{- if and
                  ($secretName := include "matrix-synapse.macaroonSecretKey.secretName" .)
                  ($secretKey := include "matrix-synapse.macaroonSecretKey.secretKey" .)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: macaroon
              {{- end }}
              - secret:
                  name: {{ quote .Values.config.formSecret.existingSecret }}
                  items:
                    - key: {{ quote .Values.config.formSecret.existingSecretKey }}
                      path: form-secret
              - secret:
                  name: {{ quote .Values.config.workerReplicationSecret.existingSecret }}
                  items:
                    - key: {{ quote .Values.config.workerReplicationSecret.existingSecretKey }}
                      path: worker-replication-secret
              {{- if and
                  ($secretName := include "matrix-synapse.mas.matrixSharedSecret.secretName" .)
                  ($secretKey := include "matrix-synapse.mas.matrixSharedSecret.secretKey" .)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: mas-shared-secret
              {{- end }}
        - name: signingkey
          secret:
            secretName: {{ .Values.signingkey.existingSecret | default (include "matrix-synapse.workername" (dict "global" . "worker" "signingkey")) | quote }}
            items:
              - key: {{ .Values.signingkey.existingSecretKey | default "signing.key" | quote }}
                path: signing.key
          {{- range $uniqCaSecrets }}
        - name: {{ printf "fed-ca-%s" .  }}
          secret:
            secretName: {{ . }}
          {{- end }}
        - name: pgpass
          emptyDir:
            sizeLimit: 10Mi
        {{- $mediaworker := false }}
        {{- range $worker, $config := .Values.workers }}
          {{- if eq $worker "media_repository" }}
            {{- $mediaworker = ($config.enabled | default false) }}
          {{- end }}
        {{- end }}
        - name: tmpdir
          emptyDir:
            {{- if not $mediaworker }}
            sizeLimit: {{ mulf ( mustRegexFind "[0-9]+" .Values.extraConfig.max_upload_size ) 5 }}{{ mustRegexFind "[A-Z]+" .Values.extraConfig.max_upload_size }}
            {{- else }}
            sizeLimit: 10Mi
            {{- end }}
            medium: Memory
        - name: media
        {{- if and .Values.persistence.enabled (not $mediaworker) }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "matrix-synapse.fullname" .) }}
        {{- else }}
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}
        {{- with .Values.synapse.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      {{- with .Values.synapse.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.synapse.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.synapse.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
