{{- if .Values.ingress.enabled -}}
{{- $fullName := include "matrix-synapse.fullname" . -}}
{{- $scannerName := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-content-scanner") -}}
{{- $wkName := include "matrix-synapse.externalname" (dict "global" . "external" "wellknown-nginx") -}}
{{- $chubName := include "matrix-synapse.externalname" (dict "global" . "external" "confighub-nginx") -}}
{{- $masName := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") -}}
{{- $v1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- $matrixUri := .Values.publicServerName | default .Values.serverName }}
{{- if $v1Ingress -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    {{- if has $matrixUri .hosts }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- $csHosts := .Values.ingress.csHosts }}
  {{- if $.Values.ingress.includeServerName }}
    {{- $csHosts = concat (list (.Values.publicServerName | default .Values.serverName)) $csHosts }}
  {{- end }}
  {{- $s2sHosts := .Values.ingress.hosts }}
  {{- if .Values.ingress.includeServerName }}
    {{- $s2sHosts = concat (list (.Values.publicServerName | default .Values.serverName)) $s2sHosts }}
  {{- end }}
  {{- $wkHosts := .Values.ingress.wkHosts }}
  {{- if .Values.ingress.includeServerName }}
    {{- $wkHosts = concat (list .Values.serverName) $wkHosts }}
  {{- end }}
  {{- /* Add .well-known to Synapse FQDN for client configuration */}}
  {{- $wkHosts = uniq (concat (list ( .Values.publicServerName | default .Values.serverName )) $wkHosts ) }}
  {{- $hosts := uniq (concat $s2sHosts $csHosts $wkHosts) }}
  {{- range $hosts }}
    {{- $host := . }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- $default := $.Values.workers.default }}
        {{- range $worker, $config := $.Values.workers }}
          {{- $name := $worker | replace "_" "-" }}
          {{- if and $config.enabled $config.listeners (or $config.paths $config.csPaths) }}
            {{- $service := include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
            {{- if has $host $csHosts }}
              {{- $csPaths := $config.csPaths }}
              {{- if $.Values.mas.enabled }}
                {{- range $csPath := $csPaths }}
                  {{- range $path := $.Values.mas.paths }}
                    {{- /* csPath starts with path, path from MAS has more priority */}}
                    {{- if hasPrefix $path $csPath }}
                      {{- $csPaths = without $csPaths $csPath }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- range $csPaths }}
                {{- /* do not include if path is "/_synapse/admin"
                admin API has its own config file "ingress-admin.yaml" */}}
                {{- if (not ( contains "/_synapse/admin" . )) }}
                  {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- else }}
          - path: {{ . | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
            {{- if has $host $s2sHosts }}
              {{- range $config.paths }}
                {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- else }}
          - path: {{ . | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if has . $csHosts }}
        {{- with $.Values.ingress.csPaths }}
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if has . $s2sHosts }}
        {{- with $.Values.ingress.paths }}
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}

        {{- if and (has . $csHosts) $.Values.contentscanner.enabled }}
          - path: /_matrix/media_proxy/unstable/
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $scannerName }}
                port:
                  number: 8080
            pathType: Prefix
          {{- else }}
              serviceName: {{ $scannerName }}
              servicePort: 8080
          {{- end }}
        {{- end }}

        {{- /* map paths like login to mas instead of Synapse */}}
        {{- if $.Values.mas.enabled }}
          {{- range $.Values.mas.paths }}
            {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
              {{- if $v1Ingress }}
              service:
                name: {{ $masName }}
                port:
                  number: 8080
            pathType: ImplementationSpecific
              {{- else }}
              serviceName: {{ $masName }}
              servicePort: 8080
              {{- end }}
            {{- else }}
          - path: {{ . | quote }}
            backend:
              {{- if $v1Ingress }}
              service:
                name: {{ $masName }}
                port:
                  number: 8080
            pathType: ImplementationSpecific
              {{- else }}
              serviceName: {{ $masName }}
              servicePort: 8080
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if has . $wkHosts }}
          {{- if $.Values.wellknown.enabled }}
          - path: "/.well-known/matrix"
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $wkName }}
                port:
                  number: 80
            pathType: ImplementationSpecific
            {{- else }}
              serviceName: {{ $wkName }}
              servicePort: 80
            {{- end }}
          {{- else }}
          - path: "/.well-known/matrix"
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: ImplementationSpecific
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if and (has . $csHosts) ($.Values.confighub.enabled) }}
          - path: /_matrix/cmaintenance
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $chubName }}
                port:
                  number: 80
            pathType: Prefix
          {{- else }}
              serviceName: {{ $chubName }}
              servicePort: 80
          {{- end }}
          - path: /_matrix/cconfig
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $chubName }}
                port:
                  number: 80
            pathType: Prefix
          {{- else }}
              serviceName: {{ $chubName }}
              servicePort: 80
          {{- end }}
        {{- end }}

        {{- if or (has . $csHosts) (has . $s2sHosts) }}
          - path: /_matrix
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
          {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}

        {{- if and (has . $csHosts) $.Values.ingress.includeUnderscoreSynapse }}
          - path: /_synapse/client
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
          {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
