{{- if .Values.ingress.enabled -}}
{{- $fullName := include "matrix-synapse.fullname" . -}}
{{- $scannerName := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-content-scanner") -}}
{{- $wkName := include "matrix-synapse.externalname" (dict "global" . "external" "wellknown-nginx") -}}
{{- $v1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- $schadcodescan := $.Values.contentscanner.enabled -}}
{{- $isSynapseAdmin := $.Values.synapse_admin.enabled -}}
{{- $adminName := include "matrix-synapse.externalname" (dict "global" . "external" "synapse-admin") -}}
{{- $adminUri := include "synapse-admin.host" . -}}
{{- $matrixUri := .Values.publicServerName | default .Values.serverName }}
{{- if $v1Ingress -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "matrix-synapse.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    {{- if or (has $adminUri .hosts) (has $matrixUri .hosts) }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- $csHosts := .Values.ingress.csHosts }}
  {{- if and $.Values.ingress.includeServerName $isSynapseAdmin }}
    {{- $csHosts = concat (list (.Values.publicServerName | default .Values.serverName)) $csHosts (list $adminUri) }}
  {{- else if .Values.ingress.includeServerName }}
    {{- $csHosts = concat (list (.Values.publicServerName | default .Values.serverName)) $csHosts }}
  {{- end }}
  {{- $s2sHosts := .Values.ingress.hosts }}
  {{- if .Values.ingress.includeServerName }}
    {{- $s2sHosts = concat (list .Values.serverName) $s2sHosts }}
  {{- end }}
  {{- $wkHosts := .Values.ingress.wkHosts }}
  {{- if .Values.ingress.includeServerName }}
    {{- $wkHosts = concat (list .Values.serverName) $wkHosts }}
  {{- end }}
  {{- $hosts := uniq (concat $s2sHosts $csHosts $wkHosts) }}
  {{- range $hosts }}
  {{- $inPublicServerName := true }}
  {{- if and (eq . $adminUri ) $isSynapseAdmin }}
    {{- $inPublicServerName = false }}
  {{- end }}
    {{- $host := . }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- $default := $.Values.workers.default }}
        {{- range $worker, $config := $.Values.workers }}
          {{- $name := $worker | replace "_" "-" }}
          {{- if and $config.enabled $config.listeners (or $config.paths $config.csPaths) }}
            {{- $service := include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
            {{- if has $host $csHosts }}
              {{- range $config.csPaths }}
#if 2 hosts and one the actual one is NOT synapse-admin-host and path doesnt include "/_synapse/admin"
#OR single url and no synapse-admin is disabled
                {{- if or (not $inPublicServerName) (and ( not (contains "/_synapse/admin" .)) $inPublicServerName $isSynapseAdmin) (and $inPublicServerName (not $isSynapseAdmin)) }}
                  {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
                    {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                    {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                    {{- end }}
                  {{- else }}
          - path: {{ . | quote }}
            backend:
                    {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                    {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- if has $host $s2sHosts }}
              {{- range $config.paths }}
                {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- else }}
          - path: {{ . | quote }}
            backend:
                  {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
                  {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if has . $csHosts }}
        {{- with $.Values.ingress.csPaths }}
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if has . $s2sHosts }}
        {{- with $.Values.ingress.paths }}
          {{ . | toYaml | nindent 10 }}
        {{- end }}
        {{- end }}

        {{- if $schadcodescan }}
          - path: /_matrix/media_proxy/unstable/
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $scannerName }}
                port:
                  number: 8080
            pathType: Prefix
          {{- else }}
              serviceName: {{ $scannerName }}
              servicePort: 8080
          {{- end }}
        {{- end }}

        {{- if has . $wkHosts }}
          {{- if $.Values.wellknown.enabled }}
          - path: /.well-known/matrix
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $wkName }}
                port:
                  number: 80
            pathType: Prefix
            {{- else }}
              serviceName: {{ $wkName }}
              servicePort: 80
            {{- end }}
          - path: /_matrix/cmaintenance
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $wkName }}
                port:
                  number: 80
            pathType: Prefix
            {{- else }}
              serviceName: {{ $wkName }}
              servicePort: 80
            {{- end }}
          {{-   else }}
          - path: /.well-known/matrix
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
            {{- end }}
          - path: /_matrix/cmaintenance
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
            {{- end }}
          {{- end }}
        {{- end }}

        {{- if or (has . $csHosts) (has . $s2sHosts) }}
          - path: /_matrix
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
          {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}

        {{- if and (has . $csHosts) $.Values.ingress.includeUnderscoreSynapse }}
          - path: /_synapse/client
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
          {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}

#if host is synapse_admin or no synapse_admin enabled and host is matrix-host
        {{- if or (and (has . $csHosts) $isSynapseAdmin (not $inPublicServerName)) (and (has . $csHosts) $inPublicServerName (not $isSynapseAdmin)) }}
          - path: /_synapse
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
          {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
          - path: /
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $adminName }}
                port:
                  number: 8080
            pathType: Prefix
          {{- else }}
              serviceName: {{ $adminName }}
              servicePort: 8080
          {{- end }}
        {{- end }}

  {{- end }}
{{- end }}
