{{- if .Values.ingress.enabled -}}
{{- $fullName := include "matrix-synapse.fullname" . -}}
{{- $v1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- $masName := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") -}}
{{- $adminUri := .Values.adminAPIServerName | required "A valid URI for the synapse Admin API (adminAPIServerName) is required." -}}

  {{- if $v1Ingress -}}
apiVersion: networking.k8s.io/v1
  {{- else -}}
apiVersion: networking.k8s.io/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotationsAdminAPI }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
      {{- if has $adminUri .hosts }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- if .secretName }}
      secretName: {{ .secretName }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $adminUri | quote }}
      http:
        paths:
  {{- $default := $.Values.workers.default }}
  {{- range $worker, $config := $.Values.workers }}
    {{- $name := $worker | replace "_" "-" }}
    {{- if and $config.enabled $config.listeners (or $config.paths $config.csPaths) }}
      {{- $service := include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
      {{- $csPaths := $config.csPaths }}
      {{- if $.Values.mas.enabled }}
        {{- range $csPath := $csPaths }}
          {{- range $path := $.Values.mas.paths }}
            {{- /* csPath starts with path, path from MAS has more priority */}}
            {{- if hasPrefix $path $csPath }}
              {{- $csPaths = without $csPaths $csPath }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- range $csPaths }}
        {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
          {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
          {{- end }}
        {{- else }}
          - path: {{ . | quote }}
            backend:
          {{- if $v1Ingress }}
              service:
                name: {{ $service }}
                port:
                  number: 8083
            pathType: ImplementationSpecific
          {{- else }}
              serviceName: {{ $service }}
              servicePort: 8083
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if and $.Values.mas.enabled }}
    {{- range $.Values.mas.paths }}
      {{- if $.Values.ingress.traefikPaths }}
          - path: {{ printf "/{path:%s}" (trimPrefix "/" .) | quote }}
            backend:
              {{- if $v1Ingress }}
              service:
                name: {{ $masName }}
                port:
                  number: 8080
            pathType: ImplementationSpecific
              {{- else }}
              serviceName: {{ $masName }}
              servicePort: 8080
              {{- end }}
            {{- else }}
          - path: {{ . | quote }}
            backend:
              {{- if $v1Ingress }}
              service:
                name: {{ $masName }}
                port:
                  number: 8080
            pathType: ImplementationSpecific
              {{- else }}
              serviceName: {{ $masName }}
              servicePort: 8080
              {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

          - path: /_synapse
            backend:
  {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
  {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
  {{- end }}

          - path: /_matrix
            backend:
  {{- if $v1Ingress }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
  {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
  {{- end }}
{{- end }}
