---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-default
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    error_log  /dev/stderr;
    pid /tmp/nginx.pid;
    events {}
    http {
      access_log  /dev/stdout;
      server_tokens off;
      include /etc/nginx/sites-enabled/default.conf;
      include mime.types;
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-d
  namespace: {{ .Release.Namespace }}
data:
  cors_headers.conf: |
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "frame-ancestors 'none'";
