{{- if .Values.schadcodescanner.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix-synapse.schadcodescannername" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.schadcodescanner.service.port }}
    targetPort: {{ .Values.schadcodescanner.service.port }}
    protocol: TCP
    name: clamav
  selector:
    {{- include "matrix-synapse.schadcodescannerselectorLabels" . | nindent 4 }}
{{- end }}
