{{- if and .Values.contentscanner.enabled .Values.schadcodescanner.enabled }}
{{- $config := .Values.schadcodescanner }}
{{- $component := "schadcodescanner" -}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "schadcodescanner") -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/schadcodescanner-configuration.yaml") . | sha256sum }}
    spec:
    {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      securityContext:
        {{- $config.podSecurityContext | toYaml | nindent 8 }}
      initContainers:
      - name: clamav-permissions
        image: "{{ $.Values.volumePermissions.image.repository }}:{{ $.Values.volumePermissions.image.tag }}"
        imagePullPolicy: "{{ $.Values.volumePermissions.image.pullPolicy | default  "IfNotPresent" }}"
        volumeMounts:
          - name: signatures
            mountPath: /clamav/database
        command:
          - sh
          - -c
          - |
            chown {{ $config.clamavSecurityContext.runAsUser | default "1111" }}:{{ $config.clamavSecurityContext.runAsGroup | default "1111" }}  -R /clamav/database;
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        resources:
          {{- $.Values.volumePermissions.resources | toYaml | nindent 10 }}
      containers:
      - name: clamav
        image: "{{ $config.clamavImage.repository }}:{{ $config.clamavImage.tag }}"
        imagePullPolicy: "{{ $config.clamavImage.pullPolicy | default  "IfNotPresent" }}"
        securityContext:
          {{- $config.clamavSecurityContext | default "" | toYaml | nindent 10 }}
        {{- if .Values.schadcodescanner.extraEnv }}
        env:
          {{- with .Values.schadcodescanner.extraEnv }}
              {{- . | toYaml | nindent 12 }}
          {{- end }}
        {{- end }}
        resources:
          {{- toYaml $config.resourcesClamav | nindent 10 }}
        volumeMounts:
          - name: clamsocket
            mountPath: /run/clamav/
          - name: signatures
            mountPath: /clamav/database
          - name: config-volume
            mountPath: /clamav/config/
          - name: clamav-tmp
            mountPath: /tmp
        startupProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          exec:
            command:
              - /usr/bin/clamdscan
              - '-p 1'
              - '--quiet'
              - '-c'
              - /clamav/config/clamdcheck.conf
        livenessProbe:
          periodSeconds: 10
          exec:
            command:
              - /usr/bin/clamdscan
              - '-p 1'
              - '--quiet'
              - '-c'
              - /clamav/config/clamdcheck.conf
        readinessProbe:
          periodSeconds: 3
          exec:
            command:
              - /usr/bin/clamdscan
              - '-p 1'
              - '--quiet'
              - '-c'
              - /clamav/config/clamdcheck.conf
      - name: c-icap-server
        image: "{{ $config.icapImage.repository }}:{{ $config.icapImage.tag }}"
        imagePullPolicy: "{{ $config.icapImage.pullPolicy | default  "IfNotPresent" }}"
        securityContext:
          {{- $config.icapSecurityContext | default "" | toYaml | nindent 10 }}
        resources:
          {{- toYaml $config.resourcesCicap | nindent 10 }}
        ports:
          - name: c-icap-clamav
            containerPort: {{ $config.service.port }}
            protocol: TCP
        startupProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: {{ $config.service.port }}
        livenessProbe:
          periodSeconds: 10
          tcpSocket:
            port: {{ $config.service.port }}
        readinessProbe:
          periodSeconds: 10
          tcpSocket:
            port: {{ $config.service.port }}
        volumeMounts:
          - name: clamsocket
            mountPath: /run/clamav/
          - name: config-volume
            mountPath: /clamav/config/
          - name: icap-volume
            mountPath: /run/c-icap/
          - name: icap-tmp
            mountPath: /tmp
      volumes:
      - name: clamsocket
        emptyDir:
          sizeLimit: 50M
      - name: icap-volume
        emptyDir:
          sizeLimit: 5M
      - name: clamav-tmp
        emptyDir:
          sizeLimit: {{ mulf .Values.schadcodescanner.limits.scanSize 5 }}M
          medium: Memory
      - name: icap-tmp
        emptyDir:
          sizeLimit: {{ mulf .Values.schadcodescanner.limits.scanSize 5 }}M
          medium: Memory
      - name: config-volume
        projected:
          sources:
          - configMap:
              name: {{ $name }}
      - name: signatures
        persistentVolumeClaim:
      {{- if .Values.schadcodescanner.persistence.existingClaim }}
          claimName: {{ .Values.schadcodescanner.persistence.existingClaim }}
      {{- else }}
          claimName: {{ $name }}
      {{- end }}
      {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- if hasKey $config "autoscaling" }}
  {{- if $config.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ $name }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: StatefulSet
    name: {{ $name }}
  minReplicas: {{ $config.autoscaling.minReplicas }}
  maxReplicas: {{ $config.autoscaling.maxReplicas }}
  metrics:
  {{- if $config.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if $config.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
{{- end }}

{{- end }}
