{{- if .Values.schadcodescanner.enabled }}
{{- $component := "schadcodescanner" -}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "schadcodescanner") -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
data:
  c-icap.conf: |
    PidFile /run/c-icap/c-icap.pid
    CommandsSocket /run/c-icap/c-icap.ctl
    User cicap
    Timeout 300
    MaxKeepAliveRequests 100
    KeepAliveTimeout 600
    StartServers 1
    MaxServers 1
    MinSpareThreads     10
    MaxSpareThreads     20
    ThreadsPerChild     10
    MaxRequestsPerChild  0
    Port 1344
    ServerName {{ $name }}
    TmpDir /var/tmp
    MaxMemObject 131072
    DebugLevel 1
    Pipelining on
    SupportBuggyClients off
    ModulesDir /usr/lib/x86_64-linux-gnu/c_icap
    ServicesDir /usr/lib/x86_64-linux-gnu/c_icap
    TemplateDir /usr/share/c_icap/templates/
    TemplateDefaultLanguage en
    LoadMagicFile /etc/c-icap/c-icap.magic
    RemoteProxyUsers off
    RemoteProxyUserHeader X-Authenticated-User
    RemoteProxyUserHeaderEncoded on
    {{- if $.Values.ipv4Only }}
    acl all src 0.0.0.0/0.0.0.0
    {{- else }}
    acl all src ::/::
    {{- end }}
    acl PERMIT_REQUESTS type REQMOD RESPMOD OPTIONS
    icap_access allow all PERMIT_REQUESTS
    ServerLog /dev/stdout
    AccessLog /dev/stdout
    Service echo srv_echo.so
    Include /clamav/config/virus_scan.conf

  virus_scan.conf: |
    Service antivirus_module virus_scan.so
    ServiceAlias srv_clamav virus_scan
    ServiceAlias  avscan virus_scan?allow204=on&sizelimit=off&mode=simple
    virus_scan.ScanFileTypes TEXT DATA EXECUTABLE ARCHIVE GIF JPEG MSOFFICE
    virus_scan.SendPercentData 5
    virus_scan.StartSendPercentDataAfter 2M
    virus_scan.MaxObjectSize  5M
    virus_scan.DefaultEngine clamd
    Include /clamav/config/clamd_mod.conf

  clamd_mod.conf: |
    Module common clamd_mod.so
    clamd_mod.ClamdSocket /run/clamav/clamd.sock

  clamdcheck.conf: |
    LocalSocket /run/clamav/clamd.sock

  clamd.conf: |
    LogTime yes
    LogClean yes
    LogSyslog no
    LogVerbose no
    LogFileMaxSize 0
    LogFile /dev/stdout
    DatabaseDirectory /clamav/database
    LocalSocket /run/clamav/clamd.sock
    User clamav
    ExitOnOOM yes
    Foreground yes
    MaxScanSize {{.Values.schadcodescanner.limits.scanSize}}M
    MaxFileSize {{.Values.schadcodescanner.limits.fileSize}}M
    #  Close the connection when the data size limit is exceeded.
    #  The value should match your MTA's limit for a maximum attachment size.
    #  Default: 25M
    StreamMaxLength {{.Values.schadcodescanner.limits.scanSize}}
    # Maximum length the queue of pending connections may grow to.
    # Default: 200
    MaxConnectionQueueLength {{.Values.schadcodescanner.limits.connectionQueueLength}}
    # Maximum number of threads running at the same time.
    # Default: 10
    MaxThreads {{.Values.schadcodescanner.limits.maxThreads}}
    # This option specifies how long to wait (in milliseconds) if the send buffer
    # is full.
    # Keep this value low to prevent clamd hanging.
    #
    # Default: 500
    SendBufTimeout {{.Values.schadcodescanner.limits.sendBufTimeout}}

  freshclam.conf: |
    LogTime yes
    LogVerbose yes
    NotifyClamd /clamav/config/clamd.conf
    Checks 24
    LogSyslog no
    DatabaseOwner root
    DatabaseMirror database.clamav.net
    {{- range $mirror := .Values.schadcodescanner.freshclam.mirrors }}
    PrivateMirror {{ $mirror }}
    {{- end }}
    # ReceiveTimeout 60
    DatabaseDirectory /clamav/database

{{- end }}
