{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $masClientSecret := randAlphaNum 24 }}
{{- $masMatrixSecret := randAlphaNum 24 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- if .Values.config.recaptcha }}
    ## Captcha ##

    recaptcha_private_key: {{ .Values.config.recaptcha.privateKey | quote }}
    {{- end }}

    ## Registration ##

    registration_shared_secret: {{ .Values.config.registrationSharedSecret | default (randAlphaNum 24) | quote }}

    ## Workers ##
    # Add a random shared secret to authenticate traffic.
    worker_replication_secret: {{ randAlphaNum 24 | quote }}

    ## API Configuration ##

    {{- if .Values.config.macaroonSecretKey }}

    macaroon_secret_key: {{ .Values.config.macaroonSecretKey | quote }}
    {{- end }}

    {{- $postgresHost := include "matrix-synapse.postgresql.host" . }}
    {{- $postgresDB   := include "matrix-synapse.postgresql.database" . }}
    {{- $postgresUser := include "matrix-synapse.postgresql.username" . }}
    {{- $postgresPort := include "matrix-synapse.postgresql.port" . }}
    {{- $postgresPass := include "matrix-synapse.postgresql.password" . }}
    {{- $postgresSSLMode := include "matrix-synapse.postgresql.sslmode" . }}
    {{- $postgresExtraArgs := include "matrix-synapse.postgresql.extraArgs" . }}

    ## Database configuration ##

    database:
      name: "psycopg2"
      args:
        user: {{ $postgresUser | quote }}
        {{- if and $postgresPass (not .Values.postgresql.auth.existingSecret) }}
        password: {{ $postgresPass | quote }}
        {{- else }}
        password: "@@POSTGRES_PASSWORD@@"
        {{- end }}
        database: {{ $postgresDB | quote }}
        host: {{ $postgresHost | quote }}
        port: {{ $postgresPort }}
        sslmode: {{ $postgresSSLMode | quote }}
        cp_min: 5
        cp_max: 10
        {{- $postgresExtraArgs | nindent 8 }}

    {{- $redisHost := include "matrix-synapse.redis.host" . }}
    {{- $redisPort := include "matrix-synapse.redis.port" . }}
    {{- $redisPass := include "matrix-synapse.redis.password" . }}

    ## Redis configuration ##

    redis:
      enabled: true
      host: {{ $redisHost | quote }}
      {{- if $redisPass }}
      password: {{ $redisPass | quote }}
      {{- else }}
      password: "@@REDIS_PASSWORD@@"
      {{- end }}
      port: {{ $redisPort }}

    {{- with .Values.extraSecrets }}

    ## Extra secrets ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}

  experimental-features.yaml: |
    {{- $expFeatures := (dict) }}
    {{- if hasKey $.Values.extraConfig "experimental_features"}}
      {{- $expFeatures = .Values.extraConfig.experimental_features }}
    {{- end }}

    {{- if .Values.call.enabled }}
      {{- $expFeatures = mergeOverwrite $expFeatures (dict "msc3266_enabled" true) }}
    {{- end }}

    {{- if .Values.mas.enabled }}
      {{- $expFeatures = omit $expFeatures "msc3861" }}
    {{- end }}

    experimental_features:

    {{- /* due to https://github.com/element-hq/synapse/issues/11203 */}}
    {{- with $expFeatures }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}

  {{- if .Values.mas.enabled }}
    {{- $internalMasUri := include
      "matrix-synapse.externalname"
      (dict "global" . "external" "matrix-authentication-service") 
    }}
      ## Matrix-Authentication-Service
      msc3861:
        enabled: true

        # Synapse will call `{issuer}/.well-known/openid-configuration` to get the OIDC configuration
        issuer: "https://{{ include "matrix-synapse.masUri" . }}"
        issuer_metadata:
          authorization_endpoint: http://{{ $internalMasUri }}:8080/authorize
          token_endpoint: http://{{ $internalMasUri }}:8080/oauth2/token
          jwks_uri: http://{{ $internalMasUri }}:8080/oauth2/keys.json
          registration_endpoint: http://{{ $internalMasUri }}:8080/oauth2/registration
          scopes_supported: [openid, email]
          revocation_endpoint: http://{{ $internalMasUri }}:8080/oauth2/revoke
          introspection_endpoint: http://{{ $internalMasUri }}:8080/oauth2/introspect
          userinfo_endpoint: http://{{ $internalMasUri }}:8080/oauth2/userinfo
          org.matrix.matrix-authentication-service.graphql_endpoint: >-
            http://{{ $internalMasUri }}:8080/graphql

        # Matches the `client_id` in the auth service config
        client_id: 0000000000000000000SYNAPSE
        # Matches the `client_auth_method` in the auth service config
        client_auth_method: client_secret_basic
        # Matches the `client_secret` in the auth service config
        client_secret: "{{ $masClientSecret }}"

        # Matches the `matrix.secret` in the auth service config
        admin_token: "{{ $masMatrixSecret }}"

        # URL to advertise to clients where users can self-manage their account
        account_management_url: "https://{{ include "matrix-synapse.masUri" . }}/account"
  {{- end }}

{{- if .Values.mas.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  mas-secret.yaml: |
    matrix:
      # The homeserver name, as per the `server_name` in the Synapse configuration file
      homeserver: {{ .Values.serverName | quote }}
      # Shared secret used to authenticate the service to the homeserver
      # This must be of high entropy, because leaking this secret would allow anyone to perform admin actions on the homeserver
      secret: {{ $masMatrixSecret }}
      # URL to which the homeserver is accessible from the service
      endpoint: "http://{{ include "matrix-synapse.fullname" . }}:8008"
    clients:
      - client_id: 0000000000000000000SYNAPSE
        client_auth_method: client_secret_basic
        client_secret: {{ $masClientSecret | quote }}
    {{- with .Values.mas.clients }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    database:
      # Full connection string as per
      # https://www.postgresql.org/docs/13/libpq-connect.html#id-1.7.3.8.3.6
      #uri: postgresql://user:password@hostname:5432/database?sslmode=require
      # -- OR --
    {{- $postgresHost := include "matrix-synapse.maspostgresql.host" . }}
    {{- $postgresDB   := include "matrix-synapse.maspostgresql.database" . }}
    {{- $postgresUser := include "matrix-synapse.maspostgresql.username" . }}
    {{- $postgresPass := include "matrix-synapse.maspostgresql.password" . }}
    {{- $postgresPort := include "matrix-synapse.maspostgresql.port" . }}
    {{- $postgresSSLMode := include "matrix-synapse.maspostgresql.sslmode" . }}
    {{- $postgresExtraArgs := include "matrix-synapse.maspostgresql.extraArgs" . }}

      ## Database configuration ##

      username: {{ $postgresUser | quote }}
      {{- if and $postgresPass (not .Values.postgresql.auth.existingSecret) }}
      password: {{ $postgresPass | quote }}
      {{- else }}
      password: "@@POSTGRES_PASSWORD@@"
      {{- end }}
      database: {{ $postgresDB | quote }}
      host: {{ $postgresHost | quote }}
      port: {{ $postgresPort }}
      # Additional parameters for the connection pool
      min_connections: 0
      max_connections: 10
      idle_timeout: 600
      max_lifetime: 1800

    upstream_oauth2:
      providers:
        {{- .Values.mas.upstream_oauth2_provider | toYaml | nindent 8 }}

    {{- with .Values.mas.email }}

    email:
      {{- . | toYaml | nindent 6 }}
    {{- end }}

{{- end }}

{{- /* Auto-generate the internal Redis Secret if required, but not existing. */}}
{{- /* This is a convenience feature for quick bringup via the tutorial. */}}
{{- if .Values.redis.enabled }}
  {{- $secretName := include "matrix-synapse.redis.secret-name" . }}
  {{- $passwordKey := include "matrix-synapse.redis.secret-key" . }}
  {{- $password := randAlphaNum 42 }}
  {{- if $secretName }}
    {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
    {{- if not $existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $passwordKey }}: {{ $password | quote }}
...
    {{- end }}
  {{- end }}
{{- end }}
