{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $insideArgoCD := include "matrix-synapse.insideArgoCD" . }}
{{- $masSecret := randAlphaNum 24 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ## Registration ##

    {{- with include "matrix-synapse.registrationSharedSecret" . }}
    registration_shared_secret: {{ . | default (randAlphaNum 24) | quote }}
    {{- end }}

    ## API Configuration ##

    {{- with include "matrix-synapse.macaroonSecretKey" . }}
    macaroon_secret_key: {{ . | quote }}
    {{- end }}

    {{- with .Values.extraSecrets }}

    ## Extra secrets ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}

  experimental-features.yaml: |
    {{- $expFeatures := (dict) }}
    {{- if hasKey $.Values.extraConfig "experimental_features"}}
      {{- $expFeatures = .Values.extraConfig.experimental_features }}
    {{- end }}

    {{- if .Values.call.enabled }}
      {{- $expFeatures = mergeOverwrite $expFeatures (dict "msc3266_enabled" true) }}
      {{- $expFeatures = mergeOverwrite $expFeatures (dict "msc4222_enabled" true) }}
    {{- end }}

    experimental_features:

    {{- /* due to https://github.com/element-hq/synapse/issues/11203 */}}
    {{- with $expFeatures }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}

{{- if or .Values.mas.enabled .Values.mas.migration.enabled }}
{{- $extraArgs := (include "maspostgresql.extraArgs" . | fromYaml) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  mas-secret.yaml: |
    # MAS configuration file reference:
    # https://element-hq.github.io/matrix-authentication-service/reference/configuration.html

    database:
      # Full connection string as per
      # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS
      uri: {{ include "matrix-synapse.maspostgresql.uri" . | quote }}

      # -- OR --
      # Separate parameters
      # host: {{ include "matrix-synapse.maspostgresql.host" . | quote }}
      # port: {{ include "matrix-synapse.maspostgresql.port" . }}
      # database: {{ include "matrix-synapse.maspostgresql.database" . | quote }}
      # username: {{ include "matrix-synapse.maspostgresql.username" . | quote }}
      # Whether to use SSL to connect to the database
      # ssl_mode: {{ toJson $extraArgs.sslmode }}
      # ssl_ca_file: {{ toJson $extraArgs.sslrootcert }}

      # Client certificate to present to the server when SSL is enabled
      # ssl_certificate_file: {{ toJson $extraArgs.sslcert }}
      # ssl_key_file: {{ toJson $extraArgs.sslkey }}

      # Additional parameters for the connection pool
      min_connections: {{ include "matrix-synapse.maspostgresql.min_connections" . }}
      max_connections: {{ include "matrix-synapse.maspostgresql.max_connections" . }}
      connect_timeout: {{ include "matrix-synapse.maspostgresql.connect_timeout" . }}
      idle_timeout: {{ include "matrix-synapse.maspostgresql.idle_timeout" . }}
      max_lifetime: {{ include "matrix-synapse.maspostgresql.max_lifetime" . }}


    {{- $extraConfig := deepCopy (
      include "matrix-synapse.filteredMasConfig" (dict "global" . "secrets" true) | fromYaml
    )}}
    {{- if and .Values.adminPortal.enabled .Values.mas.enabled }}
      {{- $bumapClient := (dict
        "client_id" .Values.adminPortal.clientID
        "client_auth_method" "none"
        "redirect_uris" (list
          (printf "https://%s/callback" .Values.adminPortal.uri)
        )
      )}}

      {{- /* ensure `clients` key exists */}}
      {{- $extraConfig = merge $extraConfig (dict "clients" (list)) }}

      {{- $extraConfig = mergeOverwrite $extraConfig (dict
        "clients" (append $extraConfig.clients $bumapClient)
      )}}
    {{- end }}

    {{- with $extraConfig }}

    ## Extra config ##
      {{ . | toYaml | nindent 4 }}
    {{- end }}

{{- end }}

{{- /* Auto-generate the internal Redis Secret if required, but not existing. */}}
{{- /* This is a convenience feature for quick bringup via the tutorial. */}}
{{- if and .Values.redis.enabled (not $insideArgoCD) }}
  {{- $secretName := include "matrix-synapse.redis.secret-name" . }}
  {{- $passwordKey := include "matrix-synapse.redis.secret-key" . }}
  {{- $legacyPassword := .Values.redis.auth.password }}

  {{- $createNewSecret := include "matrix-synapse.assertExistingSecret" (dict
    "global" .
    "secretName" $secretName
    "secretPath" "redis.auth.existingSecret"
    "keys" (list
      (dict
        "secretKey" $passwordKey
        "legacyValue" $legacyPassword
        "legacyPath" "redis.auth.password"
      )
    )
  )}}

  {{- $password := $legacyPassword | default (randAlphaNum 42) }}

  {{- if $createNewSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $passwordKey }}: {{ $password | quote }}
...
  {{- end }}
{{- end }}

{{- /* Auto-generate the external Redis Secret if required, but not existing. */}}
{{- /* This is a migration path and can be removed with externalRedis.password. */}}
{{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not $insideArgoCD) }}
  {{- $secretName := include "matrix-synapse.redis.secret-name" . }}
  {{- $passwordKey := include "matrix-synapse.redis.secret-key" . }}
  {{- $legacyPassword := .Values.externalRedis.password }}

  {{- $createNewSecret := include "matrix-synapse.assertExistingSecret" (dict
    "global" .
    "secretName" $secretName
    "secretPath" "externalRedis.existingSecret"
    "keys" (list
      (dict
        "secretKey" $passwordKey
        "legacyValue" $legacyPassword
        "legacyPath" "externalRedis.password"
      )
    )
  )}}

  {{- if $createNewSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $passwordKey }}: {{ $legacyPassword | quote }}
...
  {{- end }}
{{- end }}


{{- /* Synapse auto-generated Secret keys. */}}
{{- $synapseAutoGenSecretKeys := list
  (dict
    "name" (include "matrix-synapse.registrationSharedSecret.secretName" .)
    "key" (include "matrix-synapse.registrationSharedSecret.secretKey" .)
    "default" (randAlphaNum 42)
  )
  (dict
    "name" (include "matrix-synapse.macaroonSecretKey.secretName" .)
    "key" (include "matrix-synapse.macaroonSecretKey.secretKey" .)
    "default" (randAlphaNum 42)
  )
  (dict
    "name" .Values.config.formSecret.existingSecret
    "key" .Values.config.formSecret.existingSecretKey
    "default" (randAlphaNum 42)
  )
  (dict
    "name" .Values.config.workerReplicationSecret.existingSecret
    "key" .Values.config.workerReplicationSecret.existingSecretKey
    "default" (randAlphaNum 42)
  )
}}


{{- $postgresqlAutoGenSecretKeys := list }}
{{- if .Values.postgresql.enabled }}
  {{- /* Auto-generate the internal PostgreSQL Secret if required, but not existing. */}}
  {{- /* This is a convenience feature for quick bringup via the tutorial. */}}
  {{- $postgresqlAutoGenSecretKeys = list
    (dict
      "name" (include "matrix-synapse.postgresql.secret-name" .)
      "key" .Values.postgresql.customUser.secretKeys.name
      "default" "synapse"
    )
    (dict
      "name" (include "matrix-synapse.postgresql.secret-name" .)
      "key" .Values.postgresql.customUser.secretKeys.database
      "default" "synapse_db"
    )
    (dict
      "name" (include "matrix-synapse.postgresql.secret-name" .)
      "key" (include "matrix-synapse.postgresql.secret-key" .)
      "default" (randAlphaNum 42)
    )
    (dict
      "name" .Values.postgresql.auth.existingSecret
      "key" .Values.postgresql.auth.secretKeys.adminPasswordKey
      "default" (randAlphaNum 42)
    )
  }}
{{- else if .Values.externalPostgresql.password }}
  {{- /* Legacy PostgreSQL Secret auto-generation. */}}
  {{- /* Remove together with in-line secrets. */}}
  {{- $postgresqlAutoGenSecretKeys = list (dict
    "name" .Values.externalPostgresql.existingSecret
    "key" .Values.externalPostgresql.existingSecretPasswordKey
    "default" .Values.externalPostgresql.password
  )}}
{{- end }}
{{- if .Values.maspostgresql.enabled }}
  {{- /* Auto-generate the internal PostgreSQL Secret if required, but not existing. */}}
  {{- /* This is a convenience feature for quick bringup via the tutorial. */}}
  {{- $postgresqlAutoGenSecretKeys = append $postgresqlAutoGenSecretKeys
    (dict
      "name" (include "matrix-synapse.maspostgresql.secret-name" .)
      "key" .Values.maspostgresql.customUser.secretKeys.name
      "default" "mas"
    ) }}
  {{- $postgresqlAutoGenSecretKeys = append $postgresqlAutoGenSecretKeys
    (dict
      "name" (include "matrix-synapse.maspostgresql.secret-name" .)
      "key" .Values.maspostgresql.customUser.secretKeys.database
      "default" "mas_synapse"
    ) }}
  {{- $postgresqlAutoGenSecretKeys = append $postgresqlAutoGenSecretKeys
    (dict
      "name" (include "matrix-synapse.maspostgresql.secret-name" .)
      "key" (include "matrix-synapse.maspostgresql.secret-key" .)
      "default" (randAlphaNum 42)
    )
  }}
  {{- if or
    ( ne .Values.postgresql.auth.existingSecret .Values.maspostgresql.auth.existingSecret )
    ( ne .Values.postgresql.auth.secretKeys.adminPasswordKey .Values.maspostgresql.auth.secretKeys.adminPasswordKey)
  }}
    {{- $postgresqlAutoGenSecretKeys = append
          $postgresqlAutoGenSecretKeys
          (dict
            "name" .Values.maspostgresql.auth.existingSecret
            "key" .Values.maspostgresql.auth.secretKeys.adminPasswordKey
            "default" (randAlphaNum 42)
          )
    }}
  {{- end }}
{{- else if .Values.externalmasPostgresql.password }}
  {{- /* Legacy PostgreSQL Secret auto-generation. */}}
  {{- /* Remove together with in-line secrets. */}}
  {{- $postgresqlAutoGenSecretKeys = list (dict
    "name" .Values.externalmasPostgresql.existingSecret
    "key" .Values.externalmasPostgresql.existingSecretPasswordKey
    "default" .Values.externalmasPostgresql.password
  )}}
{{- end }}


{{- /* Legacy Call Secret auto-generation. */}}
{{- /* Remove together with in-line secrets. */}}
{{- $callAutoGenSecretKeys := list }}
{{- if and .Values.call.enabled .Values.call.livekit.key .Values.call.livekit.secret }}
  {{- $callAutoGenSecretKeys = list
    (dict
      "name" .Values.call.existingSecret
      "key" .Values.call.secretKeys.livekitKey
      "default" .Values.call.livekit.key
    )
    (dict
      "name" .Values.call.existingSecret
      "key" .Values.call.secretKeys.livekitSecret
      "default" .Values.call.livekit.secret
    )
  }}
{{- end }}


{{- /* MAS auto-generated Secret keys. */}}
{{- $masAutoGenSecretKeys := list }}
{{- if .Values.mas.enabled }}
  {{- /* Encryption is a 32-bytes hex-encoded string. */}}
  {{- $encryptionDefault := printf "%x" (b64dec (randBytes 32)) }}

  {{- /* Generate all key types supported by both MAS and `genPrivateKey`.
    rsa and ec_p256 can be generated here, ec_p384 and ec_k256 can not. */}}
  {{- $masAutoGenSecretKeys = list
    (dict
      "name" .Values.mas.encryption.existingSecret
      "key" .Values.mas.encryption.existingSecretKey
      "default" $encryptionDefault
    )
    (dict
      "name" .Values.mas.matrixSharedSecret.existingSecret
      "key" .Values.mas.matrixSharedSecret.existingSecretKey
      "default" (randAlphaNum 42)
    )
    (dict
      "name" .Values.mas.signingkeys.existingSecret
      "key" "0000-mas-signingkey-rsa.pem"
      "default" (genPrivateKey "rsa")
    )
    (dict
      "name" .Values.mas.signingkeys.existingSecret
      "key" "0001-mas-signingkey-ec.pem"
      "default" (genPrivateKey "ecdsa")
    )
  }}
{{- end }}


{{- /* List of all Secret keys that are auto-generated if missing. */}}
{{- $autoGenSecrets := concat
  $synapseAutoGenSecretKeys
  $postgresqlAutoGenSecretKeys
  $callAutoGenSecretKeys
  $masAutoGenSecretKeys
}}

{{- /* Find the names and corresponding keys of all Secrets to be created. */}}
{{- $secretNameToKeys := dict }}
{{- range $autoGenSecrets }}
  {{- if not .name }}
    {{- continue }}
  {{- end }}

  {{- $keyList := or (get $secretNameToKeys .name) list }}
  {{- $keyList = append $keyList . }}
  {{- $secretNameToKeys = set $secretNameToKeys .name $keyList }}
{{- end }}

{{- /* Auto-generate Secrets if not existing. */}}
{{- range $secretName, $keys := $secretNameToKeys }}
  {{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}

  {{- if $existingSecret }}
    {{- range $keys }}
      {{- if not (hasKey $existingSecret.data .key) }}
        {{- fail (print
          "Das bereits existierende Secret `" $secretName "` muss den "
          "Schlüssel `" .key "` enthalten. Um das Geheimnis im Secret zu "
          "ändern, nutzen Sie z.B. `kubectl --namespace=" $.Release.Namespace
          " edit secret " $secretName "` und editieren Sie `data` bzw. "
          "`stringData`."
        )}}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if and (not $existingSecret) (not $insideArgoCD) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
stringData:
  {{- range $keys }}
  {{ .key | quote }}: {{ .default | quote }}
  {{- end }}
...
  {{- end }}
{{- end }}
