{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $insideArgoCD := include "matrix-synapse.insideArgoCD" . }}
{{- $masSecret := randAlphaNum 24 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    ## Registration ##

    {{- with include "matrix-synapse.registrationSharedSecret" . }}
    registration_shared_secret: {{ . | default (randAlphaNum 24) | quote }}
    {{- end }}

    ## API Configuration ##

    {{- with include "matrix-synapse.macaroonSecretKey" . }}
    macaroon_secret_key: {{ . | quote }}
    {{- end }}

    {{- $postgresHost := include "matrix-synapse.postgresql.host" . }}
    {{- $postgresDB   := include "matrix-synapse.postgresql.database" . }}
    {{- $postgresUser := include "matrix-synapse.postgresql.username" . }}
    {{- $postgresPort := include "matrix-synapse.postgresql.port" . }}
    {{- $postgresExtraArgs := include "matrix-synapse.postgresql.extraArgs" . }}

    ## Database configuration ##

    database:
      name: "psycopg2"
      args:
        user: {{ $postgresUser | quote }}
        password: "@@POSTGRES_PASSWORD@@"
        database: {{ $postgresDB | quote }}
        host: {{ $postgresHost | quote }}
        port: {{ $postgresPort }}
        cp_min: 5
        cp_max: 10
        {{- $postgresExtraArgs | nindent 8 }}

    {{- if .Values.mas.enabled }}
      {{- $internalMasUri := printf "http://%s:8080/" (include
        "matrix-synapse.externalname"
        (dict "global" . "external" "matrix-authentication-service")
      )}}
    ## Matrix-Authentication-Service
    matrix_authentication_service:
      enabled: true
      # The base URL where Synapse will contact MAS
      endpoint: {{ $internalMasUri | quote }}
      # The shared secret used to authenticate MAS requests,
      # must be the same as `matrix.secret` in the MAS configuration
      secret: "{{ $masSecret }}"
    {{- end }}

    {{- with .Values.extraSecrets }}

    ## Extra secrets ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}

  experimental-features.yaml: |
    {{- $expFeatures := (dict) }}
    {{- if hasKey $.Values.extraConfig "experimental_features"}}
      {{- $expFeatures = .Values.extraConfig.experimental_features }}
    {{- end }}

    {{- if .Values.call.enabled }}
      {{- $expFeatures = mergeOverwrite $expFeatures (dict "msc3266_enabled" true) }}
    {{- end }}

    experimental_features:

    {{- /* due to https://github.com/element-hq/synapse/issues/11203 */}}
    {{- with $expFeatures }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}

{{- if .Values.mas.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-synapse.externalname" (dict "global" . "external" "matrix-authentication-service") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  mas-secret.yaml: |
    # MAS configuration file reference:
    # https://element-hq.github.io/matrix-authentication-service/reference/configuration.html

    matrix:
      # The homeserver name, as per the `server_name` in the Synapse configuration file
      homeserver: {{ .Values.serverName | quote }}
      # Shared secret used to authenticate the service to the homeserver
      # This must be of high entropy, because leaking this secret would allow anyone to perform admin actions on the homeserver
      secret: {{ $masSecret }}
      # URL to which the homeserver is accessible from the service
    {{- if .Values.workers.generic_worker.enabled }}
      endpoint: "http://{{ include "matrix-synapse.workername" (dict "global" . "worker" "generic-worker") }}:8083"
    {{- else }}
      endpoint: "http://{{ include "matrix-synapse.fullname" . }}:8008"
    {{- end }}

    {{- with .Values.mas.clients }}
    clients:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    database:
      # Full connection string as per
      # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS
      uri: {{ include "matrix-synapse.maspostgresql.uri" . | quote }}

      # -- OR --
      # Separate parameters
      # host: {{ include "matrix-synapse.maspostgresql.host" . | quote }}
      # port: {{ include "matrix-synapse.maspostgresql.port" . }}
      # database: {{ include "matrix-synapse.maspostgresql.database" . | quote }}
      # username: {{ include "matrix-synapse.maspostgresql.username" . | quote }}
      # password: {{ include "matrix-synapse.maspostgresql.password" . | quote }}

      # Whether to use SSL to connect to the database
      # ssl_mode: {{ toJson .Values.mas.postgresql.extraArgs.sslmode }}
      # ssl_ca_file: {{ toJson .Values.mas.postgresql.extraArgs.sslrootcert }}

      # Client certificate to present to the server when SSL is enabled
      # ssl_certificate_file: {{ toJson .Values.mas.postgresql.extraArgs.sslcert }}
      # ssl_key_file: {{ toJson .Values.mas.postgresql.extraArgs.sslkey }}

      # Additional parameters for the connection pool
      min_connections: {{ .Values.mas.postgresql.min_connections }}
      max_connections: {{ .Values.mas.postgresql.max_connections }}
      connect_timeout: {{ .Values.mas.postgresql.connect_timeout }}
      idle_timeout: {{ .Values.mas.postgresql.idle_timeout }}
      max_lifetime: {{ .Values.mas.postgresql.max_lifetime }}

    upstream_oauth2:
      providers:
        {{- .Values.mas.upstream_oauth2_provider | toYaml | nindent 8 }}

    {{- with .Values.mas.email }}

    email:
      {{- . | toYaml | nindent 6 }}
    {{- end }}

{{- end }}

{{- /* Auto-generate the internal Redis Secret if required, but not existing. */}}
{{- /* This is a convenience feature for quick bringup via the tutorial. */}}
{{- if and .Values.redis.enabled (not $insideArgoCD) }}
  {{- $secretName := include "matrix-synapse.redis.secret-name" . }}
  {{- $passwordKey := include "matrix-synapse.redis.secret-key" . }}
  {{- $legacyPassword := .Values.redis.auth.password }}

  {{- $createNewSecret := include "matrix-synapse.assertExistingSecret" (dict
    "global" .
    "secretName" $secretName
    "secretPath" "redis.auth.existingSecret"
    "keys" (list
      (dict
        "secretKey" $passwordKey
        "legacyValue" $legacyPassword
        "legacyPath" "redis.auth.password"
      )
    )
  )}}

  {{- $password := $legacyPassword | default (randAlphaNum 42) }}

  {{- if $createNewSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $passwordKey }}: {{ $password | quote }}
...
  {{- end }}
{{- end }}

{{- /* Auto-generate the external Redis Secret if required, but not existing. */}}
{{- /* This is a migration path and can be removed with externalRedis.password. */}}
{{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not $insideArgoCD) }}
  {{- $secretName := include "matrix-synapse.redis.secret-name" . }}
  {{- $passwordKey := include "matrix-synapse.redis.secret-key" . }}
  {{- $legacyPassword := .Values.externalRedis.password }}

  {{- $createNewSecret := include "matrix-synapse.assertExistingSecret" (dict
    "global" .
    "secretName" $secretName
    "secretPath" "externalRedis.existingSecret"
    "keys" (list
      (dict
        "secretKey" $passwordKey
        "legacyValue" $legacyPassword
        "legacyPath" "externalRedis.password"
      )
    )
  )}}

  {{- if $createNewSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $passwordKey }}: {{ $legacyPassword | quote }}
...
  {{- end }}
{{- end }}


{{- /* Auto-generate the internal PostgreSQL Secret if required, but not existing. */}}
{{- /* This is a convenience feature for quick bringup via the tutorial. */}}
{{- if and .Values.postgresql.enabled (not $insideArgoCD) }}
  {{- /* Best-effort retrieval of the internal maybe-auto-generated passwords. */}}
  {{- $prevSecretName := printf "%s-postgresql" .Release.Name | trunc 63 | trimSuffix "-" }}
  {{- $prevSecret := lookup "v1" "Secret" .Release.Namespace $prevSecretName }}
  {{- $prevUserPassword := dig "data" "password" "" $prevSecret | b64dec }}
  {{- $prevAdminPassword := dig "data" "postgres-password" "" $prevSecret | b64dec }}

  {{- $secretName := include "matrix-synapse.postgresql.secret-name" . }}
  {{- $userPasswordKey := include "matrix-synapse.postgresql.secret-key" . }}
  {{- $adminPasswordKey := .Values.postgresql.auth.secretKeys.adminPasswordKey }}
  {{- $legacyUserPassword := .Values.postgresql.auth.password }}
  {{- $legacyAdminPassword := .Values.postgresql.auth.postgresPassword }}

  {{- $createNewSecret := include "matrix-synapse.assertExistingSecret" (dict
    "global" .
    "secretName" $secretName
    "secretPath" "postgresql.auth.existingSecret"
    "keys" (list
      (dict
        "secretKey" $userPasswordKey
        "legacyValue" $legacyUserPassword
        "legacyPath" "postgresql.auth.password"
      )
      (dict
        "secretKey" $adminPasswordKey
        "legacyValue" $legacyAdminPassword
        "legacyPath" "postgresql.auth.postgresPassword"
      )
    )
  )}}

  {{- $userPassword := $legacyUserPassword
    | default $prevUserPassword
    | default (randAlphaNum 42)
  }}
  {{- $adminPassword := $legacyAdminPassword
    | default $prevAdminPassword
    | default (randAlphaNum 42)
  }}

  {{- if $createNewSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  {{ $userPasswordKey }}: {{ $userPassword | quote }}
  {{ $adminPasswordKey }}: {{ $adminPassword | quote }}
...
  {{- end }}
{{- end }}


{{- /* Synapse auto-generated Secret keys. */}}
{{- $synapseAutoGenSecretKeys := list
  (dict
    "name" (include "matrix-synapse.registrationSharedSecret.secretName" .)
    "key" (include "matrix-synapse.registrationSharedSecret.secretKey" .)
    "default" (randAlphaNum 42)
  )
  (dict
    "name" (include "matrix-synapse.macaroonSecretKey.secretName" .)
    "key" (include "matrix-synapse.macaroonSecretKey.secretKey" .)
    "default" (randAlphaNum 42)
  )
  (dict
    "name" .Values.config.formSecret.existingSecret
    "key" .Values.config.formSecret.existingSecretKey
    "default" (randAlphaNum 42)
  )
  (dict
    "name" .Values.config.workerReplicationSecret.existingSecret
    "key" .Values.config.workerReplicationSecret.existingSecretKey
    "default" (randAlphaNum 42)
  )
}}


{{- /* Legacy PostgreSQL Secret auto-generation. */}}
{{- /* Remove together with in-line secrets. */}}
{{- $postgresqlAutoGenSecretKeys := list }}
{{- if and (not .Values.postgresql.enabled) .Values.externalPostgresql.password }}
  {{- $postgresqlAutoGenSecretKeys = list (dict
    "name" .Values.externalPostgresql.existingSecret
    "key" .Values.externalPostgresql.existingSecretPasswordKey
    "default" .Values.externalPostgresql.password
  )}}
{{- end }}


{{- /* Legacy Call Secret auto-generation. */}}
{{- /* Remove together with in-line secrets. */}}
{{- $callAutoGenSecretKeys := list }}
{{- if and .Values.call.enabled .Values.call.livekit.key .Values.call.livekit.secret }}
  {{- $callAutoGenSecretKeys = list
    (dict
      "name" .Values.call.existingSecret
      "key" .Values.call.secretKeys.livekitKey
      "default" .Values.call.livekit.key
    )
    (dict
      "name" .Values.call.existingSecret
      "key" .Values.call.secretKeys.livekitSecret
      "default" .Values.call.livekit.secret
    )
  }}
{{- end }}


{{- /* List of all Secret keys that are auto-generated if missing. */}}
{{- $autoGenSecrets := concat
  $synapseAutoGenSecretKeys
  $postgresqlAutoGenSecretKeys
  $callAutoGenSecretKeys
}}

{{- /* Find the names and corresponding keys of all Secrets to be created. */}}
{{- $secretNameToKeys := dict }}
{{- range $autoGenSecrets }}
  {{- if not .name }}
    {{- continue }}
  {{- end }}

  {{- $keyList := or (get $secretNameToKeys .name) list }}
  {{- $keyList = append $keyList . }}
  {{- $secretNameToKeys = set $secretNameToKeys .name $keyList }}
{{- end }}

{{- /* Auto-generate Secrets if not existing. */}}
{{- range $secretName, $keys := $secretNameToKeys }}
  {{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace $secretName }}

  {{- if $existingSecret }}
    {{- range $keys }}
      {{- if not (hasKey $existingSecret.data .key) }}
        {{- fail (print
          "Das bereits existierende Secret `" $secretName "` muss den "
          "Schlüssel `" .key "` enthalten. Um das Geheimnis im Secret zu "
          "ändern, nutzen Sie z.B. `kubectl --namespace=" $.Release.Namespace
          " edit secret " $secretName "` und editieren Sie `data` bzw. "
          "`stringData`."
        )}}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if not $existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
stringData:
  {{- range $keys }}
  {{ .key }}: {{ .default | quote }}
  {{- end }}
...
  {{- end }}
{{- end }}
