{{- if .Values.monitoringService }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-synapse
  labels:
   synapse-matrix: http
spec:
  jobLabel: k8s-synapse-matrix
  selector:
    matchExpressions:
    - {key: synapse-matrix, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: /_synapse/metrics
    interval: 15s
{{- end }}
