{{- if .Values.monitoringService }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-synapse
  labels:
    matrix-synapse: monitoring
spec:
  jobLabel: k8s-matrix-synapse
  selector:
    matchExpressions:
    - {key: matrix-synapse, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: /_synapse/metrics
    interval: 15s
{{- end }}
