{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $insideArgoCD := (or .Values.argoCD (.Capabilities.APIVersions.Has "argoproj.io/v1alpha1")) }}
{{- $secretName := include "matrix-synapse.workername" (dict "global" . "worker" "signingkey") }}

{{- if .Values.signingkey.job.enabled }}
  {{- if .Values.signingkey.existingSecret }}
    {{- fail "Can't specify both signingkey.job.enabled and signingkey.existingSecret" }}
  {{- end }}
{{- $name := include "matrix-synapse.workername" (dict "global" . "worker" "signingkey-job") }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}

{{ if .Values.signingkey.serviceAccount.create }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ $secretName }}
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
  {{- if or .Values.signingkey.job.annotations (not $insideArgoCD) }}
    {{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    {{- end }}
    {{- with .Values.signingkey.job.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.labels" . | nindent 8 }}
        app.kubernetes.io/component: signingkey-job
        to-apiserver: allowed
    spec:
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.signingkey.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
      containers:
        - command:
            - sh
            - -c
            - |
              echo "Generating signing key..."
              if which generate_signing_key.py >/dev/null; then
                generate_signing_key.py -o /synapse/keys/signing.key
              else
                generate_signing_key -o /synapse/keys/signing.key
              fi
          image: {{ quote (printf "%s/%s:%s"
            .Values.signingkey.job.generateImage.registry
            .Values.signingkey.job.generateImage.repository
            .Values.signingkey.job.generateImage.tag
          )}}
          imagePullPolicy: {{ .Values.signingkey.job.generateImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.signingkey.securityContext | nindent 12 }}
          name: signing-key-generate
          {{- with .Values.signingkey.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.signingkey.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.signingkey.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /synapse/keys
              name: matrix-synapse-keys
        - command:
            - sh
            - -c
            - |
              printf "Checking rights to update secret... "
              kubectl auth can-i update secret/${SECRET_NAME}
              /scripts/signing-key.sh
          env:
            - name: SECRET_NAME
              value: {{ $secretName }}
          image: "{{ printf "%s/%s:%s" .Values.signingkey.job.publishImage.registry .Values.signingkey.job.publishImage.repository ( .Values.signingkey.job.publishImage.tag | default "latest ") }}"
          imagePullPolicy: {{ .Values.signingkey.job.publishImage.pullPolicy }}
          securityContext:
            {{- toYaml .Values.signingkey.securityContext | nindent 12 }}
          name: signing-key-upload
          {{- with .Values.signingkey.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.signingkey.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.signingkey.resources }}
          resources:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /scripts
              name: scripts
              readOnly: true
            - mountPath: /synapse/keys
              name: matrix-synapse-keys
              readOnly: true
      restartPolicy: Never
      serviceAccount: {{ include "matrix-synapse.signingkeyServiceAccountName" . }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "matrix-synapse.fullname" . }}-scripts
            defaultMode: 0755
        - name: matrix-synapse-keys
          emptyDir:
            sizeLimit: 1Mi
  parallelism: 1
  completions: 1
  backoffLimit: 1
{{- end }}

# Create secret if signing key job is enabled, or if we're running in ArgoCD and we don't have an existing secret
{{- if or .Values.signingkey.job.enabled (and (not .Values.signingkey.existingSecret) $insideArgoCD) }}
---
apiVersion: v1
kind: Secret
metadata:
{{- if not $insideArgoCD }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: never
    helm.sh/resource-policy: keep
    argocd.argoproj.io/hook: Skip
    argocd.argoproj.io/hook-delete-policy: Never
{{- end }}
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: signingkey-job
{{ $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{ if $secret -}}
  data:
    signing.key: {{ (b64dec (index $secret.data "signing.key")) | b64enc }}
{{ end -}}
{{- end }}
