{{- if $.Values.sygnal.enabled }}
{{- if $.Values.sygnal.ios_push.enabled }}
{{- $iosKey := $.Values.sygnal.ios_push.ioskey_filename | required "sygnal.ios_push.ioskey_filename ist notwendig für den Sygnal Push Service für iOS." }}

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: ioskey
data:
  {{ $iosKey }}: {{ required "Es ist der Schlüsselinhalt mit anzugeben unter sygnal.ios_push.ioskey_keyvalue" $.Values.sygnal.ios_push.ioskey_keyvalue | toYaml | quote }}

{{ end  }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: matrix-sygnal
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: matrix-sygnal
stringData:
  sygnal.yaml: |
    ##
    # This is a configuration for Sygnal, the reference Push Gateway for Matrix
    # See: matrix.org
    ##

    ## Logging #
    #
    log:
      # Specify a Python logging 'dictConfig', as described at:
      #   https://docs.python.org/3.7/library/logging.config.html#logging.config.dictConfig
      #
      setup:
        version: 1
        formatters:
          normal:
            format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
        handlers:
          # This handler prints to Standard Error
          #
          stderr:
            class: "logging.StreamHandler"
            formatter: "normal"
            stream: "ext://sys.stderr"

          # This handler prints to Standard Output.
          #
          stdout:
            class: "logging.StreamHandler"
            formatter: "normal"
            stream: "ext://sys.stdout"

        loggers:
          # sygnal.access contains the access logging lines.
          # Comment out this section if you don't want to give access logging
          # any special treatment.
          #
          sygnal.access:
            propagate: false
            handlers: ["stdout"]
            level: "INFO"

          # sygnal contains log lines from Sygnal itself.
          # You can comment out this section to fall back to the root logger.
          #
          sygnal:
            propagate: false
            handlers: ["stderr"]

        root:
          # Specify the handler(s) to send log messages to.
          handlers: ["stderr"]
          level: "INFO"

        disable_existing_loggers: false


      access:
        # Specify whether or not to trust the IP address in the `X-Forwarded-For`
        # header. In general, you want to enable this if and only if you are using a
        # reverse proxy which is configured to emit it.
        #
        x_forwarded_for: false

    ## HTTP Server (Matrix Push Gateway API) #
    #
    http:
      # Specify a list of interface addresses to bind to.
      bind_addresses: ['0.0.0.0']

      # Specify the port number to listen on.
      #
      port: 5000

    ## Proxying for outgoing connections #
    #
    # Specify the URL of a proxy to use for outgoing traffic
    # (e.g. to Apple & Google) if desired.
    # Currently only HTTP proxies with CONNECT capability are supported.
    #
    # If you do not specify a value, the `HTTPS_PROXY` environment variable will
    # be used if present. Otherwise, no proxy will be used.
    #
    # Default is unspecified.
    #
    ##proxy:
    {{- if $.Values.sygnal.proxy }}
    proxy: {{ $.Values.sygnal.proxy | quote }}
    {{- end }}
    ## Metrics #
    #
    metrics:
      ## Prometheus #
      #
      prometheus:
        # Specify whether or not to enable Prometheus.
        #
        {{- if .Values.monitoringService }}
        enabled: true
        {{- else }}
        enabled: false
        {{- end }}

        # Specify an address for the Prometheus HTTP Server to listen on.
        #
        address: '0.0.0.0'

        # Specify a port for the Prometheus HTTP Server to listen on.
        #
        port: 9090

      ## OpenTracing #
      #
      opentracing:
        # Specify whether or not to enable OpenTracing.
        #
        enabled: false

        # Specify an implementation of OpenTracing to use. Currently only 'jaeger'
        # is supported.
        #
        implementation: jaeger

        # Specify the service name to be reported to the tracer.
        #
        service_name: sygnal

        # Specify configuration values to pass to jaeger_client.
        #
        jaeger:
          sampler:
            type: 'const'
            param: 1
          #        local_agent:
          #          reporting_host: '127.0.0.1'
          #          reporting_port:
          logging: true

      ## Sentry #
      #
      sentry:
        # Specify whether or not to enable Sentry.
        #
        enabled: false


    #######################################################################
    ############################# Apps - Config ###########################
    #######################################################################
    apps:
    {{- $apns := $.Values.sygnal.apns | required "Es müssen Daten für die Push-Notifications hinterlegt werden!" -}}
    {{- with $apns }}
    ## APNs aus value ##
      {{ . | toYaml | nindent 6 }}
    {{- end }}

{{ end  }}
