{{- if .Values.synapse_admin.enabled }}
---
apiVersion: v1
kind: Service
metadata: 
  name: synapse-admin
  labels:
    app: synapse-admin
spec: 
  selector:
    app: synapse-admin
  ports: 
    - name: "admin-port"
      port: 8080
      targetPort: 80
{{- end }}
