{{- if  .Values.synapse_admin.enabled }}
{{- $adminUri := .Values.synapse_admin.adminUri | required "synapse_admin.adminUri is required." -}}
{{- $v1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- if $v1Ingress -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: synapse-admin
  labels:
    app: synapse-admin
spec:
  ingressClassName: nginx
  rules:
    - host: {{ $adminUri }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse-admin
                port:
                  number: 8080
{{- end }}
