{{- if .Values.synapse_admin.enabled }}
{{- $adminName := include "matrix-synapse.externalname" (dict "global" . "external" "synapse-admin") -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $adminName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $adminName }}
spec:
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $adminName }}
  ports:
    - name: "admin-port"
      port: 8080
      targetPort: 8080
{{- end }}
