{{- if and .Values.ingress.enabled .Values.webclient.enabled }}
{{- $webclientUri := .Values.webclient.uri | required "webclient.uri is required." -}}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}
{{- $v1Ingress := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}

---
{{- if $v1Ingress -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.webclient.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  {{- range .Values.ingress.tls }}
    {{- if has $webclientUri .hosts }}
  tls:
    - hosts:
        - {{ $webclientUri }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ $webclientUri }}
      http:
        paths:
          - path: /
            backend:
            {{- if $v1Ingress }}
              service:
                name: {{ $webclientName }}
                port:
                  number: 8080
            pathType: Prefix
            {{- else }}
              serviceName: {{ $webclientName }}
              servicePort: 8080
            {{- end }}
{{- end }}
