{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}

# The config.json file is to be put into Kubernetes as a config file in such a way that
# the element web instance can read it.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "{{- printf "https://%s" (.Values.publicServerName | default .Values.serverName) }}",
                "server_name": "BuM Demo"
            }
        },
        "disable_custom_urls": true,
        "disable_guests": true,
        "disable_3pid_login": true,
        "brand": "BundesMessenger",
        "defaultCountryCode": "DE",
        "show_labs_settings": false,
        "features": { },
        "default_federate": true,
        "room_directory": {
            "servers": []
        },
        "branding": {
          "showMatrixBrand": false,
          "home_title": "Willkommen im BundesMessenger",
          "home_byline": "Dein Messenger für unser Land",
          "welcome_background_url": "bwi/img/bm_background.svg",
          "auth_header_logo_url": "bwi/img/dlms_logo.svg",
          "auth_footer_links": [
            {
              "text": "Handgemacht mit \u2764 von der BWI",
              "url": https://bwi.de
            }
          ]
        },
        "bwi_themes": [
          {
            "name": "light",
            "is_dark": false,
            "default": true,
            "colors": {
              "accent": "#004972",
              "quinary-content": "#EEEEEE"
            }
          },
          {
            "name": "dark",
            "is_dark": true,
            "default": true,
            "colors": {
              "accent": "#217DB1",
              "primary-content": "#FFFFFF",
              "secondary-content": "#EEEEEE",
              "tertiary-content": "#DDDDDD"
            }
          }
        ],
        "default_theme": "bwi-light",
        "suppressNotification": [
          "MESSAGE_EDIT", "org.matrix.msc3381.poll.response", "m.room.redaction", "m.reaction"
        ],
        "enabledLanguages": ["de", "en"]
    }
  nginx.conf: |
    user www-data;
    error_log  /dev/stderr;
    events {}
    http {
      access_log  /dev/stdout;
      server_tokens off;
      include /etc/nginx/sites-enabled/default.conf;
      include mime.types;
    }
  default.conf: |
     # Default server configuration
     #
     server {
             listen 8080 default_server;
             {{- if not .Values.ipv4Only }}
             listen [::]:8080 default_server;
             {{- end }}
             # SSL configuration
             #
             # listen 443 ssl default_server;
             # listen [::]:443 ssl default_server;
             #
             # Note: You should disable gzip for SSL traffic.
             # See: https://bugs.debian.org/773332
             #
             # Read up on ssl_ciphers to ensure a secure configuration.
             # See: https://bugs.debian.org/765782
             #
             # Self signed certs generated by the ssl-cert package
             # Don't use them in a production server!
             #
             # include snippets/snakeoil.conf;
     
             root /usr/share/nginx/html/;
     
             # Add index.php to the list if you are using PHP
             index index.html index.htm index.nginx-debian.html;
     
             server_name _;
             #livenessProbe auf /status mal selbst gemacht 
             location /status {
               return 200;
             }
             location ~ /config.{{ .Values.webclient.uri }}.json {
                rewrite /config.{{ .Values.webclient.uri }}.json /config.json break;
             }
             location = /favicon.ico {
                alias /app/bwi/img/favicon.ico;
             }
             location / {
                     # First attempt to serve request as file, then
                     # as directory, then fall back to displaying a 404.
                     try_files $uri $uri/ =404;
             }
     
             # pass PHP scripts to FastCGI server
             #
             #location ~ \.php$ {
             #       include snippets/fastcgi-php.conf;
             #
             #       # With php-fpm (or other unix sockets):
             #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
             #       # With php-cgi (or other tcp sockets):
             #       fastcgi_pass 127.0.0.1:9000;
             #}
     
             # deny access to .htaccess files, if Apache's document root
             # concurs with nginx's one
             #
             #location ~ /\.ht {
             #       deny all;
             #}
     }


{{- end }}
