{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}
{{- $displayName := .Values.webclient.displayName | default "Messenger deiner Organisation" }}
# The config.json file is to be put into Kubernetes as a config file in such a way that
# the element web instance can read it.


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $webclientName }}-tempconf
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
data:
  temp.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "{{- printf "https://%s" (.Values.publicServerName | default .Values.serverName) }}",
          "server_name": {{ $displayName | quote }}
        }
      },
      "enable_presence_by_hs_url": {
        "{{- printf "https://%s" (.Values.publicServerName | default .Values.serverName) }}": false
      },
      "permalink_prefix": "{{- printf "https://%s/latest" (.Values.publicServerName | default .Values.serverName) }}"
    }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
data:
  default.conf: |
     # Default server configuration
     #
     server {
             listen 8080 default_server;
             {{- if not .Values.ipv4Only }}
             listen [::]:8080 default_server;
             {{- end }}
             # SSL configuration
             #
             # listen 443 ssl default_server;
             # listen [::]:443 ssl default_server;
             #
             # Note: You should disable gzip for SSL traffic.
             # See: https://bugs.debian.org/773332
             #
             # Read up on ssl_ciphers to ensure a secure configuration.
             # See: https://bugs.debian.org/765782
             #
             # Self signed certs generated by the ssl-cert package
             # Don't use them in a production server!
             #
             # include snippets/snakeoil.conf;

             root /usr/share/nginx/html/;

             # Add index.php to the list if you are using PHP
             index index.html index.htm index.nginx-debian.html;

             server_name _;
             #livenessProbe auf /status mal selbst gemacht, logging aus
             location /status {
               return 200;
               access_log off;
             }
             location ~ /config.{{ .Values.webclient.uri }}.json {
                rewrite /config.{{ .Values.webclient.uri }}.json /config.json break;
             }
             location = /favicon.ico {
                alias /app/bwi/img/favicon.ico;
             }
             location / {
                     # First attempt to serve request as file, then
                     # as directory, then fall back to displaying a 404.
                     try_files $uri $uri/ =404;
             }

             # pass PHP scripts to FastCGI server
             #
             #location ~ \.php$ {
             #       include snippets/fastcgi-php.conf;
             #
             #       # With php-fpm (or other unix sockets):
             #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
             #       # With php-cgi (or other tcp sockets):
             #       fastcgi_pass 127.0.0.1:9000;
             #}

             # deny access to .htaccess files, if Apache's document root
             # concurs with nginx's one
             #
             #location ~ /\.ht {
             #       deny all;
             #}
     }


{{- end }}
