{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
spec:
  selector:
    app.kubernetes.io/component: {{ $webclientName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
{{- end }}
