{{- if .Values.webclient.enabled }}
{{- $webclientName := include "matrix-synapse.externalname" (dict "global" . "external" "webclient") -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $webclientName }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $webclientName }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $webclientName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $webclientName }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.webclient.podSecurityContext | nindent 8 }}
      containers:
      - name: element
        image: "{{ $.Values.webclient.image.repository }}:{{  $.Values.webclient.image.tag }}"
        imagePullPolicy: {{ $.Values.webclient.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.webclient.securityContext | nindent 12 }}
        volumeMounts:
        - name: files
          mountPath: /app/config.json
          subPath: config.json
        - name: files
          mountPath: /etc/nginx/sites-enabled/default.conf
          subPath: default.conf
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tmp
          mountPath: /tmp
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
            httpGet:
                path: /
                port: http
            initialDelaySeconds: 2
            periodSeconds: 3
        livenessProbe:
            httpGet:
                path: /status
                port: http
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: files
        configMap:
          name: {{ $webclientName }}
      - name: nginx-conf
        configMap: 
          name: nginx-default-conf
{{- end }}
