{{- if .Values.wellknown.enabled }}
{{- $wkName := include "matrix-synapse.externalname" (dict "global" . "external" "wellknown-nginx") -}}
{{- $component := "wellknown-nginx" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wkName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    component: {{ $component }}
data:
  bundesmessenger.conf: |
    server {
      listen 8080 default_server;
      {{- if not .Values.ipv4Only }}
      listen [::]:8080 default_server;
      {{- end }}
      server_name _;

      root {{ .Values.wellknown.htdocsPath }};
      #Noch kein LUA-Support
      #{{- if .Values.monitoringService }}
      #listen 9090;
      #location /metrics {
      #  content_by_lua_block {
      #    metric_connections:set(ngx.var.connections_reading, {"reading"})
      #    metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      #    metric_connections:set(ngx.var.connections_writing, {"writing"})
      #    prometheus:collect()
      #  }
      #}
      #{{- end }}
      #livenessProbe auf /status mal selbst gemacht, logging aus
      location /status {
        return 200;
        access_log off;
      }
      location /_matrix/cmaintenance {
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        add_header Content-Type application/json;
        rewrite ^/_matrix/cmaintenance /maintenance.json break;
      }
      {{- $keys := concat (list "client" "server") (keys .Values.wellknown.extraData ) }}
      {{- range $key := initial $keys }}
      location ~ ^/\.well-known/matrix/{{ $key }} {
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        add_header Content-Type application/json;
        rewrite ^/\.well-known/matrix/{{ $key }} /{{ $key }}.json break;
      }
      {{- end }}
      location ~ ^/\.well-known/matrix/{{ last $keys }} {
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With,Content-Type, Accept, Authorization";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        add_header Content-Type application/json;
        rewrite ^/\.well-known/matrix/{{ last $keys }} /{{ last $keys }}.json break;
      }
    }
  server.json: |-
{{-   if .Values.wellknown.server }}
{{ toJson .Values.wellknown.server | nindent 4 }}
{{-   else }}
{{ dict "m.server" (printf "%s:%d" (.Values.wellknown.host | default (.Values.publicServerName | default .Values.serverName)) (.Values.wellknown.port | default 443)) | toJson | indent 4 }}
{{-   end }}
  client.json: |-
{{-   if .Values.wellknown.client }}
{{ toJson .Values.wellknown.client | nindent 4 }}
{{-   else }}
    {
      "m.homeserver": {
        "base_url": "{{- printf "https://%s" (.Values.publicServerName | default .Values.serverName) }}"
      },
      "io.element.e2ee": {
        "secure_backup_required": "true",
        "secure_backup_setup_methods": ["passphrase"],
        "outbound_keys_pre_sharing_mode": "on_room_opening"
      },
      "de.bwi": {
        "data_privacy_url": "{{- printf "https://%s" ( .Values.dataPrivacyUrl | required "a valid URL for data protection regulations / privacy policy (dataPrivacyUrl) is required. ") }}"
      }
    }
{{-   end }}
  maintenance.json: |-
    {
      "downtime": [
        {
          "warning_start_time": "2022-12-14T11:00:00Z",
          "start_time": "2022-12-23T11:00:00Z",
          "end_time": "2022-12-24T20:00:00Z",
          "type": "MAINTENANCE_STANDARD",
          "description": "Weihnachtswartung 2022"
        }
      ],
      "versions": {
        "ios": {
          "update_before": "1.17.0",
          "warn_before": "1.19.0"
        },
        "android": {
          "update_before": "1.17.0",
          "warn_before": "1.19.0"
        }
      }
    }
{{-   range $key, $value := .Values.wellknown.extraData }}
  {{ $key }}.json: |-
{{-     if $value | kindIs "string" -}}
    {{ $value | nindent 4 }}
{{-     else -}}
    {{ $value | toJson | nindent 4 }}
{{-     end -}}
{{-   end -}}
{{- end -}}
