{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $any := false }}
{{- range $worker, $config := .Values.workers }}
  {{- if $config.enabled }}
    {{- $any = true }}
  {{- end }}
{{- end }}

{{- if $any }}
{{- $uniqueApps := list "appservice" "user_dir" "background_worker" -}}
{{- $wkName := include "matrix-synapse.workername" (dict "global" . "worker" "workers") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wkName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
{{- $default := .Values.workers.default -}}
{{- range $worker, $config := .Values.workers -}}
  {{- if $config.enabled -}}
    {{- $name := $worker | replace "_" "-" }}

    {{- /* check that workers do not have replicaCount > 1 */}}
    {{- $isUnique := le ($config.replicaCount | default $default.replicaCount | int) 1 }}
    {{- if and (has $worker $uniqueApps) (not $isUnique) }}
      {{- fail (printf "Replica count must be 1 for worker %s." $worker) }}
    {{- end }}

  {{ $name }}.worker.yaml: |
    worker_app: synapse.app.generic_worker

    # worker_name: assigned at runtime for each replica via a separate config.

    worker_listeners:
      - port: 9090
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [metrics]
            compress: false

      - port: 9099
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [health]
            compress: false
    {{- if $config.listeners }}
      {{- if has "replication" $config.listeners }}

      - port: 9093
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http
        x_forwarded: true

        resources:
          - names: [replication]
            compress: false
      {{- end }}

      - port: 8083
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http
        x_forwarded: true

        resources:
          - names:
              {{- toYaml (without $config.listeners "replication") | nindent 14 }}
            compress: false
    {{- end }}

    worker_log_config: /synapse/config/log.yaml
    {{- if or $config.extraConfig $default.extraConfig }}

    # Extra config
    {{ toYaml ($config.extraConfig | default $default.extraConfig) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
