{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $needsVolumePermissions := and .Values.volumePermissions.enabled (or .Values.persistence.enabled .Values.persistence.existingClaim) }}
{{- $releaseName := .Release.Name }}
{{- $uniqCaSecrets := list }}
{{- range .Values.extraConfig.federation_custom_ca_list }}
  {{- /* extract secret name from cert path - between first both slashes, put them in a list and make it unique */}}
  {{- $uniqCaSecrets = uniq (append $uniqCaSecrets (split "/" ( trimPrefix "/" . ))._0) }}
{{- end }}

{{- $workerConfigs := omit .Values.workers "default" }}
{{- range $worker, $config := $workerConfigs }}
  {{- if not $config.enabled }}
    {{- continue }}
  {{- end }}

  {{- $name := $worker | replace "_" "-" }}
  {{- $replicaSize := $config.replicaCount }}
  {{- if $config.autoscaling.enabled }}
    {{- $replicaSize = max $replicaSize $config.autoscaling.minReplicas }}
  {{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  replicas: {{ $replicaSize }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") $ | sha256sum }}
        checksum/worker-config: {{ include (print $.Template.BasePath "/worker-configuration.yaml") $ | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
        checksum/signing-key-job: {{ include (print $.Template.BasePath "/signing-key-job.yaml") $ | sha256sum }} 
        checksum/ca-secrets: {{ print $uniqCaSecrets | sha256sum }}
      {{- with $config.annotations }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrix-synapse.selectorLabels" $ | nindent 8 }}
        {{- include "matrix-synapse.monitoringLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
      {{- with $config.labels }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" $ }}
      {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      securityContext:
        {{- $config.podSecurityContext | toYaml | nindent 8 }}
      initContainers:
      {{- if and $needsVolumePermissions (not (hasKey $config.podSecurityContext "fsGroup" )) (eq $name "media-repository") }}
        - name: volume-permissions
          command:
            - sh
            - -c
            - |
              chown {{ $.Values.volumePermissions.uid }}:{{ $.Values.volumePermissions.gid }} -R /synapse/data;
          image: "{{ printf "%s/%s:%s" $.Values.volumePermissions.image.registry $.Values.volumePermissions.image.repository $.Values.volumePermissions.image.tag }}"
          imagePullPolicy: {{ $.Values.volumePermissions.image.pullPolicy }}
          securityContext:
          {{- $.Values.volumePermissions.securityContext | toYaml | nindent 12 }}
          resources: {{ $.Values.volumePermissions.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /synapse/data
      {{- end }}
        - name: update-config
          securityContext:
            {{- $config.securityContext | toYaml | nindent 12 }}
          command:
            - sh
            - -c
            - |
              cat /tmp/{{ $name }}.worker | sed "s/@@HOSTNAME@@/${HOSTNAME}/" > /synapse/config/{{ $name }}.worker
          image: "{{ printf "%s/%s:%s" $.Values.image.registry $.Values.image.repository ( include "matrix-synapse.imageTag" $ )}}"
          volumeMounts:
          - mountPath: "/tmp/"
            name: temp-worker-config
          - mountPath: "/synapse/config/"
            name: worker-config
      containers:
        - name: {{ $name }}
          command:
            - sh
            - -c
            - |
              cat /synapse/secrets/*.yaml | \
                sed -e "s/@@POSTGRES_PASSWORD@@/${POSTGRES_PASSWORD:-}/" \
                    -e "s/@@REDIS_PASSWORD@@/${REDIS_PASSWORD:-}/" \
                       > /synapse/config/conf.d/secrets.yaml

              {{- range $config.extraCommands }}
              {{- . | nindent 14 }}
              {{- end }}

              exec python3 -B -m synapse.app.generic_worker \
                          -c /synapse/config/homeserver.yaml \
                          -c /synapse/config/conf.d/ \
                          -c /synapse/config/{{ $name }}.worker
          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if and
              ($postgresSecretName := include "matrix-synapse.postgresql.secret-name" $)
              ($postgresSecretKey := include "matrix-synapse.postgresql.secret-key" $)
          }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $postgresSecretName }}
                  key: {{ $postgresSecretKey }}
          {{- end }}
          {{- if and
              ($redisSecretName := include "matrix-synapse.redis.secret-name" $)
              ($redisSecretKey := include "matrix-synapse.redis.secret-key" $)
          }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $redisSecretName }}
                  key: {{ $redisSecretKey }}
          {{- end }}
          {{- with $config.extraEnv }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          securityContext:
            {{- $config.securityContext | toYaml | nindent 12 }}
          image: "{{ printf "%s/%s:%s" $.Values.image.registry $.Values.image.repository ( include "matrix-synapse.imageTag" $ )}}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- if $config.listeners }}
            {{- if without $config.listeners "replication" }}
            - name: listener
              containerPort: 8083
              protocol: TCP
            {{- end }}
            {{- if has "replication" $config.listeners }}
            - name: replication
              containerPort: 9093
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- $config.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /synapse/config/homeserver.yaml
              subPath: homeserver.yaml
            - name: config
              mountPath: /synapse/config/log.yaml
              subPath: log.yaml
            - name: worker-config
              mountPath: /synapse/config/{{ $name }}.worker
              subPath: {{ $name }}.worker
            - name: tmpconf
              mountPath: /synapse/config/conf.d
            - name: secrets
              mountPath: /synapse/secrets
            - name: signingkey
              mountPath: /synapse/keys
            - mountPath: /tmp/
              name: tempdir
          {{- if eq $name "media-repository" }}
            - name: media
              mountPath: /synapse/data
          {{- end }}
          {{- range $uniqCaSecrets }}
            - name: {{ printf "fed-ca-%s" .  }}
              mountPath: /{{ . }}
          {{- end }}
          {{- with $config.volumeMounts }}
            {{ . | toYaml | nindent 12 }}
          {{- end }}
      {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "matrix-synapse.fullname" $ }}
        - name: worker-config
          emptyDir:
            sizeLimit: 10Mi
        - name: temp-worker-config
          configMap:
            name: {{ include "matrix-synapse.workername" (dict "global" $ "worker" "workers") }}
        - name: secrets
          secret:
            secretName: {{ include "matrix-synapse.fullname" $ }}
        - name: signingkey
          secret:
            secretName: {{ $.Values.signingkey.existingSecret | default (include "matrix-synapse.workername" (dict "global" $ "worker" "signingkey")) | quote }}
            items:
              - key: {{ $.Values.signingkey.existingSecretKey | default "signing.key" | quote }}
                path: signing.key
        - name: tmpconf
          emptyDir:
            sizeLimit: 10Mi
      {{- range $uniqCaSecrets }}
        - name: {{ printf "fed-ca-%s" .  }}
          secret:
            secretName: {{ . }}
      {{- end }}
        - name: tempdir
          emptyDir:
            {{- if regexMatch $name "media-repository" }}
            sizeLimit: {{ mulf ( mustRegexFind "[0-9]+" $.Values.extraConfig.max_upload_size ) 5 }}{{ mustRegexFind "[A-Z]+" $.Values.extraConfig.max_upload_size }}
            {{- else }}
            sizeLimit: 10Mi
            {{- end }}
            medium: Memory
      {{- if regexMatch $name "media-repository" }}
        - name: media
        {{- if $.Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $.Values.persistence.existingClaim | default (include "matrix-synapse.fullname" $) }}
        {{- else }}
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}
      {{- end }}
      {{- with $config.volumes }}
        {{ . | toYaml | nindent 8 }}
      {{- end }}
...

{{- if hasKey $config "autoscaling" }}
  {{- if $config.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: StatefulSet
    name: {{ $releaseName }}-{{ $name }}
  minReplicas: {{ $config.autoscaling.minReplicas }}
  maxReplicas: {{ $config.autoscaling.maxReplicas }}
  metrics:
    {{- if $config.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $config.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
...
  {{- end }}
{{- end }}

{{- end }}
