{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- $needsVolumePermissions := and .Values.volumePermissions.enabled (or .Values.persistence.enabled .Values.persistence.existingClaim) }}
{{- $releaseName := .Release.Name }}
{{- $uniqCaSecrets := list }}
{{- range .Values.extraConfig.federation_custom_ca_list }}
  {{- /* extract secret name from cert path - between first both slashes, put them in a list and make it unique */}}
  {{- $uniqCaSecrets = uniq (append $uniqCaSecrets (split "/" ( trimPrefix "/" . ))._0) }}
{{- end }}
{{- $migrationPhase := and .Values.mas.enabled .Values.mas.migration.enabled -}}
{{- $default := .Values.workers.default }}
{{- $workerConfigs := omit .Values.workers "default" }}
{{- range $worker, $config := $workerConfigs }}
  {{ $config = merge $config $default }}
  {{- if not $config.enabled }}
    {{- continue }}
  {{- end }}
  {{- $name := $worker | replace "_" "-" }}
  {{- $replicaSize := $config.replicaCount }}
  {{- if and (hasKey $config "autoscaling" ) $config.autoscaling.enabled }}
    {{- $replicaSize = max $replicaSize $config.autoscaling.minReplicas }}
  {{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
    # Scale-Down bei aktiver Migration
    {{- if $migrationPhase }}
  replicas: 0
    {{- else }}
  replicas: {{ $replicaSize }}
    {{- end }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") $ | sha256sum }}
        checksum/worker-config: {{ include (print $.Template.BasePath "/worker-configuration.yaml") $ | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
        checksum/signing-key-job: {{ include (print $.Template.BasePath "/signing-key-job.yaml") $ | sha256sum }}
        checksum/ca-secrets: {{ print $uniqCaSecrets | sha256sum }}
      {{- with $config.annotations }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matrix-synapse.selectorLabels" $ | nindent 8 }}
        {{- include "matrix-synapse.monitoringLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $name }}
      {{- with $config.labels }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" $ }}
      automountServiceAccountToken: false
      {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      securityContext:
        {{- $config.podSecurityContext | toYaml | nindent 8 }}
      initContainers:
      {{- if and $needsVolumePermissions (not (hasKey $config.podSecurityContext "fsGroup" )) (eq $name "media-repository") }}
        - name: volume-permissions
          command:
            - sh
            - -c
            - |
              chown {{ $.Values.volumePermissions.uid }}:{{ $.Values.volumePermissions.gid }} -R /synapse/data;
          image: "{{ printf "%s/%s:%s" $.Values.volumePermissions.image.registry $.Values.volumePermissions.image.repository $.Values.volumePermissions.image.tag }}"
          imagePullPolicy: {{ $.Values.volumePermissions.image.pullPolicy }}
          securityContext:
          {{- $.Values.volumePermissions.securityContext | toYaml | nindent 12 }}
          resources: {{ $.Values.volumePermissions.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: media
              mountPath: /synapse/data
      {{- end }}
        - name: update-config
          securityContext:
            {{- $config.securityContext | toYaml | nindent 12 }}
          command:
            - sh
            - -c
            - |
              # Assign a unique worker name.
              # HOSTNAME contains the pod index and is thus unique per replica.
              echo "worker_name: $HOSTNAME" > /synapse/config/replica/worker-name.yaml
          image: {{ quote (printf "%s/%s:%s"
            $.Values.image.registry $.Values.image.repository $.Values.image.tag
          )}}
          resources:
            {{- $config.resources | toYaml | nindent 12 }}
          volumeMounts:
          - name: replica-worker-config
            mountPath: /synapse/config/replica
        - name: generate-pgpass
          securityContext:
            {{- $config.securityContext | toYaml | nindent 12 }}
          command:
            - sh
            - -c
            - |
              # Generate pgpass file.
              # Ref: https://www.postgresql.org/docs/current/libpq-pgpass.html
              pgpass_escape() {
                sed 's/\\/\\\\/; s/:/\\:/'
              }
              printf '\
              # hostname:port:database:username:password
              *:*:*:%s:%s
              ' \
                "$(echo "$POSTGRES_USER" | pgpass_escape)" \
                "$(pgpass_escape < /synapse/secrets/postgresql/password)" \
              > /synapse/pgpass/pgpass
              # PostgreSQL requires restrictive permissions on the passfile.
              chmod 0400 /synapse/pgpass/pgpass
          env:
            - name: POSTGRES_USER
              value: {{ include "matrix-synapse.postgresql.username" $ | quote }}
          image: {{ quote (printf "%s/%s:%s"
            $.Values.image.registry $.Values.image.repository $.Values.image.tag
          )}}
          resources:
            {{- $config.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: pgpass
              mountPath: /synapse/pgpass
            - name: secrets
              mountPath: /synapse/secrets
      containers:
        - name: {{ $name }}
          command:
            - sh
            - -c
            - |
              {{- range $config.extraCommands }}
              {{- . | nindent 14 }}
              {{- end }}

              exec python3 -B -m synapse.app.generic_worker \
                          -c /synapse/config/homeserver.yaml \
                          -c /synapse/config/experimental-features.yaml \
                          -c /synapse/config/secret-config.yaml \
                          -c /synapse/config/worker/{{ $name }}.yaml \
                          -c /synapse/config/replica/worker-name.yaml
          {{- with $config.extraEnv }}
          env:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          securityContext:
            {{- $config.securityContext | toYaml | nindent 12 }}
          image: {{ quote (printf "%s/%s:%s"
            $.Values.image.registry $.Values.image.repository $.Values.image.tag
          )}}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: health
              containerPort: 9099
              protocol: TCP
          {{- if $config.listeners }}
            {{- if without $config.listeners "replication" }}
            - name: listener
              containerPort: 8083
              protocol: TCP
            {{- end }}
            {{- if has "replication" $config.listeners }}
            - name: replication
              containerPort: 9093
              protocol: TCP
            {{- end }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.startupProbe }}
          startupProbe:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- $config.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /synapse/config
            - name: replica-worker-config
              mountPath: /synapse/config/replica
            - name: secrets
              mountPath: /synapse/secrets
            - name: pgpass
              mountPath: /synapse/pgpass/pgpass
              subPath: pgpass
            - name: signingkey
              mountPath: /synapse/keys
            - mountPath: /tmp/
              name: tempdir
          {{- if eq $name "media-repository" }}
            - name: media
              mountPath: /synapse/data
          {{- end }}
          {{- range $uniqCaSecrets }}
            - name: {{ printf "fed-ca-%s" .  }}
              mountPath: /{{ . }}
          {{- end }}
          {{- with $config.volumeMounts }}
            {{ . | toYaml | nindent 12 }}
          {{- end }}
      {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ include "matrix-synapse.fullname" $ }}
                  items:
                    - key: log.yaml
                      path: log.yaml
                    - key: homeserver.yaml
                      path: homeserver.yaml
              - secret:
                  name: {{ include "matrix-synapse.fullname" $ }}
                  items:
                    - key: config.yaml
                      path: secret-config.yaml
                    - key: experimental-features.yaml
                      path: experimental-features.yaml
              - configMap:
                  name: {{ include 
                    "matrix-synapse.workername" (dict "global" $ "worker" "workers") }}
                  items:
                    - key: {{ $name }}.worker.yaml
                      path: worker/{{ $name }}.yaml
        - name: replica-worker-config
          emptyDir:
            sizeLimit: 10Mi
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ include "matrix-synapse.postgresql.secret-name" $ | quote }}
                  items:
                    - key: {{ include "matrix-synapse.postgresql.secret-key" $ | quote }}
                      path: postgresql/password
              - secret:
                  name: {{ include "matrix-synapse.redis.secret-name" $ | quote }}
                  items:
                    - key: {{ include "matrix-synapse.redis.secret-key" $ | quote }}
                      path: redis
              {{- if and
                  ($secretName := include "matrix-synapse.registrationSharedSecret.secretName" $)
                  ($secretKey := include "matrix-synapse.registrationSharedSecret.secretKey" $)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: registration
              {{- end }}
              {{- if and
                  ($secretName := include "matrix-synapse.macaroonSecretKey.secretName" $)
                  ($secretKey := include "matrix-synapse.macaroonSecretKey.secretKey" $)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: macaroon
              {{- end }}
              - secret:
                  name: {{ quote $.Values.config.formSecret.existingSecret }}
                  items:
                    - key: {{ quote $.Values.config.formSecret.existingSecretKey }}
                      path: form-secret
              - secret:
                  name: {{ quote $.Values.config.workerReplicationSecret.existingSecret }}
                  items:
                    - key: {{ quote $.Values.config.workerReplicationSecret.existingSecretKey }}
                      path: worker-replication-secret
              {{- if and
                  ($secretName := include "matrix-synapse.mas.matrixSharedSecret.secretName" $)
                  ($secretKey := include "matrix-synapse.mas.matrixSharedSecret.secretKey" $)
              }}
              - secret:
                  name: {{ quote $secretName }}
                  items:
                    - key: {{ quote $secretKey }}
                      path: mas-shared-secret
              {{- end }}
        - name: signingkey
          secret:
            secretName: {{ $.Values.signingkey.existingSecret | default (include "matrix-synapse.workername" (dict "global" $ "worker" "signingkey")) | quote }}
            items:
              - key: {{ $.Values.signingkey.existingSecretKey | default "signing.key" | quote }}
                path: signing.key
        - name: pgpass
          emptyDir:
            sizeLimit: 10Mi
      {{- range $uniqCaSecrets }}
        - name: {{ printf "fed-ca-%s" .  }}
          secret:
            secretName: {{ . }}
      {{- end }}
        - name: tempdir
          emptyDir:
            {{- if regexMatch $name "media-repository" }}
            sizeLimit: {{ mulf ( mustRegexFind "[0-9]+" $.Values.extraConfig.max_upload_size ) 5 }}{{ mustRegexFind "[A-Z]+" $.Values.extraConfig.max_upload_size }}
            {{- else }}
            sizeLimit: 10Mi
            {{- end }}
            medium: Memory
      {{- if regexMatch $name "media-repository" }}
        - name: media
        {{- if $.Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $.Values.persistence.existingClaim | default (include "matrix-synapse.fullname" $) }}
        {{- else }}
          emptyDir:
            sizeLimit: 1Gi
        {{- end }}
      {{- end }}
      {{- with $config.volumes }}
        {{ . | toYaml | nindent 8 }}
      {{- end }}
...

{{- if hasKey $config "autoscaling" }}
  {{- if $config.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ include "matrix-synapse.workername" (dict "global" $ "worker" $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: StatefulSet
    name: {{ $releaseName }}-{{ $name }}
  minReplicas: {{ $config.autoscaling.minReplicas }}
  maxReplicas: {{ $config.autoscaling.maxReplicas }}
  metrics:
    {{- if $config.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $config.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
...
  {{- end }}
{{- end }}

{{- end }}
