{{- $any := false }}
{{- range $worker, $config := .Values.workers }}
  {{- if $config.enabled }}
    {{- $any = true }}
  {{- end }}
{{- end }}

{{- if $any }}
{{- $uniqueApps := list "appservice" "user_dir" "background_worker" -}}
{{- $wkName := include "matrix-synapse.workername" (dict "global" . "worker" "workers") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wkName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
{{- $default := .Values.workers.default -}}
{{- range $worker, $config := .Values.workers -}}
  {{- if $config.enabled -}}
    {{- $name := $worker | replace "_" "-" }}
    {{- $app := $config.app | default $worker }}

    # check that workers do not have replicaCount > 1
    {{- if and (gt ($config.replicaCount | default $default.replicaCount | int) 1) (has $app $uniqueApps) -}}
    {{-   fail (printf "Replica count must be 1 for worker %s." $app) -}}
    {{- end }}

  {{ $name }}.worker: |
    worker_app: "synapse.app.{{ (not (not $config.generic)) | ternary "generic_worker" $app }}"

    worker_name: "@@HOSTNAME@@"

    worker_replication_host: {{ include "matrix-synapse.replicationname" $ | quote }}
    worker_replication_http_port: 9093

    worker_listeners:
      - port: 9090
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http

        resources:
          - names: [metrics]
            compress: false
    {{- if $config.listeners }}

      - port: 8083
        tls: false
        {{- if $.Values.ipv4Only }}
        bind_addresses: ['0.0.0.0']
        {{- else }}
        bind_addresses: ['::']
        {{- end }}
        type: http
        x_forwarded: true

        resources:
          - names:
              {{- toYaml $config.listeners | nindent 14 }}
            compress: false
    {{- end }}

    worker_log_config: /synapse/config/log.yaml
    {{- if $config.extraConfig }}

    # Extra config
    {{ toYaml $config.extraConfig | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
