serverName: example.org
publicServerName: matrix.example.org
adminAPIServerName: admin-api.example.org
dataPrivacyUrl: example.com/privacy
imprintUrl: example.com/imprint

image:
  pullSecrets:
    - name: test-secret

monitoring:
  enabled: true
  labels:
    release: kube-prom-stack

synapse:
  annotations:
    test-annotation: synapse

extraConfig:
  federation_custom_ca_list:
    - /SECRETNAME1/myCA1.pem

workers:
  default:
    annotations:
      test-annotation: default-workers
  generic_worker:
    replicaCount: 1
    # Kubernetes v1.23+.
    # autoscaling:
    #  enabled: true
  appservice:
    enabled: true
  pusher:
    enabled: true

synapse_admin:
  enabled: true
  uri: admin-client.example.org

webclient:
  enabled: true
  uri: web.example.org

call:
  enabled: true
  uri: call.example.org

contentscanner:
  enabled: true

schadcodescanner:
  enabled: true

sygnal:
  enabled: true
  fcmkey_filename: bum.json
  fcmkey_keyvalue:
    type: "service_account"
    project_id: "dummy"
  ioskey_filename: AuthKey.p8
  ioskey_keyvalue: "TFMwdExTMUNSVWRKVGlCUVVrbFdRVlJGSUV0c2Rmc2QK"
  apps:
    de.opencode.dvs.gcm:
      type: gcm
      api_key: example-value
      service_account_file: /bum.json
    de.opencode.dvs.ios:
      type: apns
      keyfile: /AuthKey.p8
      key_id: example
      team_id: example
      topic: example

wellknown:
  enabled: true

postgresql:
  enabled: true
  auth:
    existingSecret: postgresql-secret

networkpolicies:
  enabled: true

# optional pullSecrets
# image:
#   pullSecrets:
#     - name: bum-git
# redis:
#   image:
#     pullSecrets: bum-git

# only to validate template
demomode:
  enabled: true

mas:
  enabled: true
  # upstream_oauth2_provider:
  #     - id: 01HFRQFT5QFMJFGF01P7JAV2ME
  #       human_name: Authentik
  #       issuer: "https://<authentik-domain>/application/o/<app-slug>/" # TO BE FILLED
  #       client_id: "<client-id>" # TO BE FILLED
  #       client_secret: "<client-secret>" # TO BE FILLED
  #       scope: "openid profile email"
  #       claims_imports:
  #         localpart:
  #           action: require
  #           template: "{{ user.preferred_username }}"
  #         displayname:
  #           action: suggest
  #           template: "{{ user.name }}"
  #         email:
  #           action: suggest
  #           template: "{{ user.email }}"
  #           set_email_verification: always
  #     - id: "01HFS67GJ145HCM9ZASYS9DC3J"
  #       issuer: "https://gitlab.com"
  #       human_name: "GitLab"
  #       brand_name: "gitlab"
  #       token_endpoint_auth_method: "client_secret_post"
  #       client_id: "<client-id>" # TO BE FILLED
  #       client_secret: "<client-secret>" # TO BE FILLED
  #       scope: "openid profile email"
  #       claims_imports:
  #         displayname:
  #           action: suggest
  #           template: "{{ user.name }}"
  #         localpart:
  #           action: ignore
  #         email:
  #           action: suggest
  #           template: "{{ user.email }}"

additionalConfig:
  verifyJWT:
    - Token1
    - Token2
  dsgvoExport:
    enabled: true
