serverName: example.org
publicServerName: matrix.example.org
adminAPIServerName: admin-api.example.org
dataPrivacyUrl: example.com/privacy
imprintUrl: example.com/imprint

monitoring:
  enabled: true
  labels:
    release: kube-prom-stack

synapse:
  annotations:
    test-annotation: synapse

workers:
  default:
    annotations:
      test-annotation: default-workers
  generic_worker:
    replicaCount: 1
    # Kubernetes v1.23+.
    # autoscaling:
    #  enabled: true
  appservice:
    enabled: true
  pusher:
    enabled: true

synapse_admin:
  enabled: true
  uri: admin-client.example.org

webclient:
  enabled: true
  uri: web.example.org

contentscanner:
  enabled: true

schadcodescanner:
  enabled: true

sygnal:
  enabled: true
  apps:
    de.opencode.dvs.gcm:
      type: gcm
      api_key: example-value

wellknown:
  enabled: true

postgresql:
  enabled: true

networkpolicies:
  enabled: true

# optional pullSecrets
# image:
#   pullSecrets:
#     - name: bum-git
# redis:
#   image:
#     pullSecrets: bum-git

# only to validate template
demomode:
  enabled: true

mas:
  enabled: true

additionalConfig:
  dsgvoExport:
    enabled: true