{{/* SPDX-FileCopyrightText: 2022–2024 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.contentscanner.enabled }}
{{- $config := .Values.contentscanner -}}
{{- $component := "matrix-content-scanner" -}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-content-scanner") -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.contentscanner.replicaCount }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  serviceName: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/matrix-content-scanner/contentscanner-configuration.yaml") . | sha256sum }}
    spec:
      {{- include "matrix-synapse.imagePullSecrets" $ | nindent 6 }}
      securityContext:
        {{- $config.podSecurityContext | toYaml | nindent 8 }}
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      containers:
      - name: {{ $name }}
        image: "{{ printf "%s/%s:%s" $config.image.registry $config.image.repository $config.image.tag }}"
        imagePullPolicy: "{{ $config.image.pullPolicy }}"
        securityContext:
          {{- $config.securityContext | toYaml | nindent 10 }}
        resources:
          {{- toYaml $config.resources | nindent 10 }}
        ports:
        - containerPort: 8080
          name: contentscanner
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: contentscanner
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          periodSeconds: 3
          tcpSocket:
            port: contentscanner
        volumeMounts:
          - name: scannerconfig
            mountPath: /data
          - name: temp
            mountPath: /tmp
          - name: crypto
            mountPath: /crypto
          - name: scannerscript
            mountPath: /opt
        {{- with .Values.contentscanner.extraVolumeMounts }}
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      volumes:
        - name: temp
          emptyDir:
            sizeLimit: {{ mulf .Values.schadcodescanner.limits.scanSize 5 }}M
            medium: Memory
        - name: crypto
          emptyDir:
            sizeLimit: 1Mi
        - name: scannerscript
          configMap:
            name: {{ $name }}-scannerscript
            defaultMode: 0755
            items:
            - key: scanner.sh
              path: scanner.sh
            - key: scanner_bypass.sh
              path: scanner_bypass.sh
        - name: scannerconfig
          configMap:
            name: {{ $name }}
            items:
            - key: config.yaml
              path: config.yaml
      {{- with .Values.contentscanner.extraVolumes }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
