{{/* SPDX-FileCopyrightText: 2022–2024 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.contentscanner.enabled }}
{{- $component := "matrix-content-scanner" -}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "matrix-content-scanner") -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: contentscanner
  selector:
    {{- include "matrix-synapse.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
{{- end }}
