{{/* SPDX-FileCopyrightText: 2022–2024 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.call.enabled }}
{{- $callName := include "matrix-synapse.externalname" (dict "global" . "external" "call") -}}
{{- $component := "call" -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $callName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  selector:
    {{- include "matrix-synapse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
{{- end }}
