{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.ingress.enabled .Values.call.enabled }}
{{- $jwtServiceName := include "matrix-synapse.externalname" (dict "global" . "external" "call-jwt-service") -}}
{{- $component := "call" -}}
{{- $matrixHostName := include "matrix-synapse.publicServerName" . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $jwtServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    {{- if has $matrixHostName .hosts }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- $csHosts := .Values.ingress.csHosts }}
  {{- if $.Values.ingress.includeServerName }}
    {{- $csHosts = concat (list $matrixHostName) $csHosts }}
  {{- end }}
  {{- range $csHosts }}
    {{- $host := . }}
    - host: {{ . | quote }}
      http:
        paths:
          {{/* deprecated */}}
          - path: "/sfu/get"
            backend:
              service:
                name: {{ $jwtServiceName }}
                port:
                  number: 8080
            pathType: Prefix
          - path: "/get_token"
            backend:
              service:
                name: {{ $jwtServiceName }}
                port:
                  number: 8080
            pathType: Prefix
  {{- end }}
{{- end }}
