{{/* SPDX-FileCopyrightText: 2022–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if .Values.call.enabled }}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "call-jwt-service") -}}
{{- $component := "call-jwt-service" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  replicas: {{ .Values.call.jwtService.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "matrix-synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      annotations:
        {{- with lookup "v1" "Secret" .Release.Namespace .Values.call.existingSecret }}
        checksum/secrets: {{ sha256sum (toJson .) }}
        {{- else }}
        checksum/secrets: {{
          sha256sum (include (print $.Template.BasePath "/secrets.yaml") .) }}
        {{- end }}
      labels:
        {{- include "matrix-synapse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
    spec:
      serviceAccountName: {{ include "matrix-synapse.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- include "matrix-synapse.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.call.jwtService.podSecurityContext | nindent 8 }}
      containers:
        - name: lk-jwt-service
          env:
            - name: LIVEKIT_URL
              value: {{ .Values.call.livekit.url | quote }}
            - name: LIVEKIT_KEY_FROM_FILE
              value: /secret/livekit-key
            - name: LIVEKIT_SECRET_FROM_FILE
              value: /secret/livekit-secret
          {{- with .Values.call.jwtService.extraEnv }}
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ printf "%s/%s:%s" .Values.call.jwtService.image.registry .Values.call.jwtService.image.repository .Values.call.jwtService.image.tag  }}"
          imagePullPolicy: {{ .Values.call.jwtService.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.call.jwtService.securityContext | nindent 12 }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 30
          volumeMounts:
            - mountPath: /secret
              name: secret
            - mountPath: /tmp
              name: tmp
          {{- with .Values.call.jwtService.extraVolumeMounts }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.call.jwtService.resources | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 10Mi
            medium: Memory
        - name: secret
          projected:
            sources:
              - secret:
                  name: {{ .Values.call.existingSecret }}
                  items:
                    - key: {{ .Values.call.secretKeys.livekitKey }}
                      path: livekit-key
              - secret:
                  name: {{ .Values.call.existingSecret }}
                  items:
                    - key: {{ .Values.call.secretKeys.livekitSecret }}
                      path: livekit-secret
        {{- with .Values.call.jwtService.extraVolumes }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
    {{- with .Values.call.jwtService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.call.jwtService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.call.jwtService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
