{{/* SPDX-FileCopyrightText: 2024–2025 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.call.enabled (not .Values.call.existingSecret)}}
{{- $name := include "matrix-synapse.externalname" (dict "global" . "external" "call-jwt-service") -}}
{{- $component := "call-jwt-service" -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
type: Opaque
data:
  livekit-url: {{ .Values.call.livekit.url | b64enc | quote }}
  livekit-key: {{ .Values.call.livekit.key | b64enc | quote }}
  livekit-secret: {{ .Values.call.livekit.secret | b64enc | quote }}

{{- end }}
