{{/* SPDX-FileCopyrightText: 2022–2026 BWI GmbH */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}
{{- if and .Values.ingress.enabled .Values.call.enabled .Values.call.standalone.enabled }}
{{- $callUri := .Values.call.standalone.uri | required "call.standalone.uri is required." -}}
{{- $callName := include "matrix-synapse.externalname" (dict "global" . "external" "call-standalone") -}}
{{- $component := "call-standalone" -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $callName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    {{- if has $callUri .hosts }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ $callUri | quote }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ $callName }}
                port:
                  number: 8080
            pathType: Prefix
{{- end }}
