{{- if .Values.wellknown.enabled }}
{{- $wkName := include "matrix-synapse.externalname" (dict "global" . "external" "wellknown-nginx") -}}
{{- $component := "wellknown-nginx" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wkName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    component: {{ $component }}
data:
  bundesmessenger.conf: |
    server {
      listen 8080 default_server;
      {{- if not .Values.ipv4Only }}
      listen [::]:8080 default_server;
      {{- end }}
      server_name _;

      root {{ .Values.wellknown.htdocsPath }};
      {{- /* Noch kein LUA-Support */ -}}
      {{- if .Values.monitoring.enabled }}
      #listen 9090;
      #location /metrics {
      #  content_by_lua_block {
      #    metric_connections:set(ngx.var.connections_reading, {"reading"})
      #    metric_connections:set(ngx.var.connections_waiting, {"waiting"})
      #    metric_connections:set(ngx.var.connections_writing, {"writing"})
      #    prometheus:collect()
      #  }
      #}
      {{- end }}
      # livenessProbe auf /status, logging deaktiviert
      location /status {
        return 200;
        access_log off;
      }
      {{- $keys := concat (list "client" "server") (keys .Values.wellknown.extraData ) }}
      {{- range $key := initial $keys }}
      location ~ ^/\.well-known/matrix/{{ $key }} {
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        add_header Content-Type application/json;
        rewrite ^/\.well-known/matrix/{{ $key }} /{{ $key }}.json break;
      }
      {{- end }}
      location ~ ^/\.well-known/matrix/{{ last $keys }} {
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With,Content-Type, Accept, Authorization";
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Origin "*";
        add_header Content-Type application/json;
        rewrite ^/\.well-known/matrix/{{ last $keys }} /{{ last $keys }}.json break;
      }
    }
  server.json: |-
{{-   if .Values.wellknown.server }}
{{ toPrettyJson .Values.wellknown.server | nindent 4 }}
{{-   else }}
{{ dict "m.server" (printf "%s:%d" (.Values.wellknown.host | default (.Values.publicServerName | default .Values.serverName)) (.Values.wellknown.port | default 443)) | toPrettyJson | indent 4 }}
{{-   end }}
  client.json: |-
{{-   if .Values.wellknown.client }}
{{ toPrettyJson .Values.wellknown.client | nindent 4 }}
{{-   else }}
    {
      "m.homeserver": {
        "base_url": "{{- printf "https://%s" ( .Values.publicServerName | default .Values.serverName ) }}"
      },
      {{- if .Values.mas.enabled }}
      "org.matrix.msc2965.authentication": {
        "issuer": "https://{{ include "matrix-synapse.masUri" . }}",
        "account": "https://{{ include "matrix-synapse.masUri" . }}/account"
      },
      {{- end }}
      "io.element.e2ee": {
        "secure_backup_required": true,
        "secure_backup_setup_methods": ["passphrase"],
        "outbound_keys_pre_sharing_mode": "on_room_opening"
      },
      {{- if .Values.additionalConfig.locationSharing.enabled }}
      "m.tile_server": {
        {{- if .Values.additionalConfig.locationSharing.map_style_url }}
        "map_style_url": {{ .Values.additionalConfig.locationSharing.map_style_url | quote }}
        {{- else }}
        "map_style_url": "{{- printf "https://%s" ( .Values.publicServerName | default .Values.serverName ) }}/_matrix/cconfig/style.json"
        {{- end }}
      },
      {{- end }}
      "de.bwi": {
        "data_privacy_url": "{{- printf "https://%s" ( .Values.dataPrivacyUrl | required "a valid URL for data protection regulations / privacy policy (dataPrivacyUrl) is required. ") }}",
        "imprint_url": "{{- printf "https://%s" ( .Values.imprintUrl | required "a valid URL for imprint (imprintUrl) is required. ") }}"
      }
    }
{{-   end }}
{{-   range $key, $value := .Values.wellknown.extraData }}
  {{ $key }}.json: |-
{{-     if $value | kindIs "string" -}}
    {{ $value | nindent 4 }}
{{-     else -}}
    {{ $value | toPrettyJson | nindent 4 }}
{{-     end -}}
{{-   end -}}
{{- end -}}
